lib/src/Base/Stat/ProductCovarianceModel.cxx, lib/src/Base/Stat/ProductCovarianceModel.hxx, python/src/ProductCovarianceModel_doc.i.in
TODO: TensorizedCovarianceModel to allow that
=> Do not allow ProductCovarianceModel of dim > 1

ChangeLog, lib/src/Uncertainty/Distribution/GammaFactory.cxx
http://trac.openturns.org/ticket/798
=> Fix Trac bug 798

distro/debian/rules, lib/Doxyfile.in, lib/include/CMakeLists.txt, lib/src/Base/Common/Log.cxx, lib/src/Base/Common/Log.hxx, lib/src/Base/Common/Path.hxx, lib/test/t_Log_std.cxx, python/src/Bisection_doc.i.in, python/src/Brent_doc.i.in, python/src/CMakeLists.txt, python/src/ComparisonOperator_doc.i.in, python/src/LinearModelTest_doc.i.in, python/src/Log.i, python/src/Log_doc.i.in, python/src/NormalityTest_doc.i.in, python/src/OptimizationProblemImplementation_doc.i.in, python/src/Path.i, python/src/Path_doc.i.in, python/src/PlatformInfo.i, python/src/PlatformInfo_doc.i.in, python/src/Secant_doc.i.in, python/src/TTY.i, python/src/TTY_doc.i.in, utils/copyright.sh
& Platforminfo, plus related fixes
=> Added Log, Path & TTY doctrings

lib/src/Base/Stat/NumericalSampleImplementation.cxx, lib/src/Uncertainty/Distribution/UserDefined.cxx
Use case: I wanted the VisualTest.DrawempiricalCDF graph to retain my sample description in the marginal legend.
=> Sample description

ChangeLog, python/src/KrigingAlgorithm_doc.i.in
These changes had been forgotten in #17.
=> Fix KrigingAlgorithm docstring to use newer Optim API

python/doc/pyplots/UserDefinedSpectralModel.py, python/doc/user_manual/stochastic_process.rst, python/src/CMakeLists.txt, python/src/SpectralModelFactoryImplementation_doc.i.in, python/src/UserDefinedSpectralModel.i, python/src/UserDefinedSpectralModel_doc.i.in, python/src/WelchFactory_doc.i.in
It contains the documentation of the UserDefinedSpectralModel and SpectralModelFactory classes.
=> Spectral model doc

python/src/Basis.i, python/src/ComplexMatrixImplementation.i, python/src/Copula.i, python/src/CorrelationMatrix.i, python/src/CovarianceMatrix.i, python/src/Description.i, python/src/Indices.i, python/src/Interval.i, python/src/Mesh.i, python/src/NumericalMathFunction.i, python/src/NumericalPoint.i, python/src/NumericalSample.i, python/src/PolygonArray.i, python/src/SklarCopula.i, python/src/TypedCollectionInterfaceObject.i, python/src/TypedInterfaceObject.i
=> Check arguments converted via typemaps

lib/src/Base/Stat/ProductCovarianceModel.cxx, lib/src/Base/Stat/ProductCovarianceModel.hxx
The PR fixes get/setParameter method of ProductCovarianceModel
=> Fixed ProductCovarianceModel. [gs]etParameter

lib/src/Base/Optim/TNC/TNC.cxx
If the problem has no bounds, spawn a new instance with infinite bounds.
Also check for constraints in checkProblem instead of callback.
Removed invalid initialization of starting point in case some bounds are
infinite.
=> TNC to handle problem bounds correctly

python/src/BaseOptimTemplateDefs.i
Small commit that fixes missing swig templates for the new optimization classes
=> Fix missing definition of swig template for OptimizationProblem/OptimizationSolver

lib/src/Uncertainty/Algorithm/Analytical/Analytical.cxx
It's a regression from aec7de2
=> Fix standard space origin evaluation

lib/src/Base/Stat/CovarianceModelImplementation.cxx, lib/src/Base/Stat/ExponentialModel.cxx, lib/src/Base/Stat/ExponentialModel.hxx, python/src/ExponentialModel_doc.i.in
The following PR fixes a bug in CovarianceModelImplementation::setParameter and introduce new constructor to ExponentialModel
=> Bugfix covariance model

lib/src/Base/Func/SpecFunc/SpecFunc.cxx
Use of thw Boost library if available for the evaluation of SpecFuncc::LogBesselK
=> Perform modified log Bessel function

python/doc/math_notations.sty, python/src/ARMALikelihoodFactory_doc.i.in, python/src/AggregatedNumericalMathEvaluationImplementation_doc.i.in, python/src/CMakeLists.txt, python/src/CovarianceModelImplementation_doc.i.in, python/src/DickeyFullerTest.i, python/src/DickeyFullerTest_doc.i.in, python/src/ExponentialModel_doc.i.in, python/src/NonStationaryCovarianceModelFactory_doc.i.in, python/src/NormalCopula_doc.i.in, python/src/ProcessImplementation_doc.i.in, python/src/QuadraticCumul_doc.i.in, python/src/RandomVectorImplementation_doc.i.in, python/src/SecondOrderModelImplementation_doc.i.in, python/src/SpectralModelFactoryImplementation_doc.i.in, python/src/StationaryCovarianceModelFactory_doc.i.in, python/src/Student_doc.i.in, python/src/WelchFactory_doc.i.in
Added the documentation for the Dickey Fuller test and enforced the use of the \Tr LaTeX command for transposition.
=> Stoch proc doc

python/src/Collection.i, python/src/ComplexTensor.i, python/src/IdentityMatrix.i, python/src/Matrix.i, python/src/NumericalSample.i, python/src/SymmetricTensor.i, python/src/Tensor.i
Resolves http://trac.openturns.org/ticket/808
=> Fix Tensor item accessor

lib/src/Base/Algo/KarhunenLoeveP1Factory.cxx, lib/src/Uncertainty/Algorithm/MetaModel/GeneralizedLinearModelAlgorithm.cxx
abs comes from stdlib.h on operates on int
=> Use std::abs(double) instead of abs(int)

lib/src/Uncertainty/Distribution/TruncatedDistribution.cxx, python/test/t_TruncatedDistribution_std.expout, python/test/t_TruncatedDistribution_std.py
Fixes initialization of TruncatedDistribution attibutes in the interval constructor
=> TruncatedDistribution interval initialization

python/doc/_templates/Copula.rst_t, python/doc/_templates/Distribution.rst_t, python/doc/pyplots/ComposedCopula.py, python/doc/pyplots/CompositeDistribution.py, python/doc/pyplots/ConditionalRandomVector.py, python/doc/pyplots/MaximumEntropyOrderStatisticsCopula.py, python/doc/pyplots/MaximumEntropyOrderStatisticsDistribution.py, python/doc/pyplots/Mixture.py, python/doc/pyplots/OrdinalSumCopula.py, python/doc/user_manual/probabilistic_modelling.rst, python/doc/user_manual/stochastic_process.rst, python/src/ComposedCopula_doc.i.in, python/src/ConditionalRandomVector_doc.i.in, python/src/MaximumEntropyOrderStatisticsDistribution_doc.i.in, python/src/OrdinalSumCopula_doc.i.in
This PR fixes several typos in the Sphix documentation and add specific illustrations to several classes
=> Typos and illustrations

python/src/Weibull_doc.i.in
=> Fix shape/scale inversion in Weibull's docstring

ChangeLog, lib/src/Base/Algo/IteratedQuadrature.cxx, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Distribution/Mixture.cxx, lib/src/Uncertainty/Distribution/ProductDistribution.cxx, lib/src/Uncertainty/Distribution/ProductDistribution.hxx, lib/src/Uncertainty/Model/ContinuousDistribution.cxx, lib/src/Uncertainty/Model/DistributionImplementation.cxx, lib/test/t_ClaytonCopula_std.expout, lib/test/t_ProductDistribution_std.cxx, lib/test/t_ProductDistribution_std.expout, python/src/IteratedQuadrature_doc.i.in, python/test/t_ClaytonCopula_std.expout, python/test/t_ComposedCopula_std.expout, python/test/t_GumbelCopula_std.expout
This PR provides a specific implementation of the computeCDF() and computeProbability() methods for ProductDistribution.
=> Product distribution cdf

lib/src/Uncertainty/Distribution/NormalCopula.cxx, python/test/t_NormalCopula_std.expout, python/test/t_NormalCopula_std.py
...outside ]-1,1[ normal quantiles
=> Fix NormalCopula::computeProbability

lib/src/Uncertainty/Distribution/ComposedDistribution.cxx, lib/test/t_ComposedDistribution_std.cxx, lib/test/t_ComposedDistribution_std.expout, python/test/t_ComposedDistribution_std.expout, python/test/t_ComposedDistribution_std.py
...with a non-independent copula
=> Fix ComposedDistribution::computeSurvivalFunction

python/test/t_NumericalMathFunction_analytical.expout, python/test/t_NumericalMathFunction_analytical.py
We're not testing python3.5 yet, just 2.7/3.1 on the autobuilder.
=> Fix analytical function test on Py3.5

python/doc/bibliography.rst
http://authors.library.caltech.edu/33070/
=> Fix Au2001 reference

lib/src/Base/Func/NumericalMathFunction.cxx, lib/src/Base/Func/openturns/NumericalMathFunction.hxx, python/src/NumericalMathFunctionImplementation_doc.i.in
The method is available in NumericalMathFunctionImplementation but not
in NumericalMathFunction.
=> Add NumericalMathFunction::setParameter(NP)

python/src/TypedCollectionInterfaceObject.i, python/src/TypedInterfaceObject.i
Account for the namespace, to ease development of C++ modules
=> Swig macros for modules

python/doc/developer_guide/git_workflow.rst
Otherwise the developer guide shows every git items in the toctree:
http://openturns.github.io/developer_guide/developer_guide.html
It must be:
Architecture
Library development
Sphinx documentation
Latex documentation
Module development
Wrapper development
Git workflow
Coding rules
Windows port
Windows native port
=> Add a git section title

lib/src/Base/Func/NumericalMathEvaluationImplementation.cxx
Now it is possible to use the 2D interface for 1D functions.
=> Improved the draw() method of NumericalMathEvaluationImplementation

lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralizedLinearModelAlgorithm.hxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingAlgorithm.hxx, lib/test/t_MetaModelValidation_std.cxx, lib/test/t_MetaModelValidation_std.expout, python/test/t_MetaModelValidation_std.expout, python/test/t_MetaModelValidation_std.py
The main improvement is to delegate to LAPACK the solution of the least-squares problem for the trend computation instead of doing it by hand using a QR decomposition (it is exactly what LAPACK do, but faster).
The other improvements are cosmetic: better agreement with coding rules, renaming of protected methods and attributes.
=> Improved GeneralizedLinearModelAlgorithm and KrigingAlgorithm

.travis.yml, python/doc/conf.py.in
requires sphinx 1.4 and the dvisvgm utility.
=> Use svg math format

python/src/ExponentialCauchy_doc.i.in, python/src/FittingTest_doc.i.in, python/src/LogNormalFactory_doc.i.in, python/src/ProcessSample_doc.i.in
The PR fixes "the the" in several docstrings
=> Fix docstring

lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesAlgorithm.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesAlgorithmImplementation.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/SobolIndicesAlgorithm.hxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/SobolIndicesAlgorithmImplementation.hxx, python/src/SobolIndicesAlgorithmImplementation_doc.i.in, python/src/SobolIndicesAlgorithm_doc.i.in
Add missing getters for bootstrap size/confidence level
=> Minor fix in SobolIndicesAlgorithm

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx, python/src/CovarianceModelImplementation_doc.i.in, python/src/Matrix_doc.i.in
This PR fixes some methods with missing/incorrect docstring 
It fixes also the usage of ResourceMap in GeneralizedLinearModelAlgorithm class
=> Improve documentation for some specific methods

lib/src/Uncertainty/Distribution/MaximumDistribution.cxx, lib/src/Uncertainty/Distribution/openturns/MaximumDistribution.hxx
The MaximumDistribution has been improved in order to manage efficiently the case where the underlying random vector has independent identically distributed components.
=> Improved MaximumDistribution

ChangeLog, python/src/CovarianceModel.i, python/src/ProductCovarianceModel.i, python/src/ProductCovarianceModel_doc.i.in, python/src/TensorizedCovarianceModel.i, python/src/TensorizedCovarianceModel_doc.i.in, python/src/openturns/PythonWrappingFunctions.hxx, python/test/t_KrigingAlgorithm_cov.py
The PR fixes http://trac.openturns.org/ticket/841
=> Better use of CovarianceModelCollection

ChangeLog, python/src/AggregatedProcess.i, python/src/AggregatedProcess_doc.i.in, python/src/UncertaintyProcessTemplateDefs.i, python/src/openturns/PythonWrappingFunctions.hxx, python/test/t_AggregatedProcess_std.py
This fixes http://trac.openturns.org/ticket/842
=> Wrap Process sequence

python/src/viewer.py, python/test/t_Viewer.py
- Fixes a problem with PolygonArray when colors are defined with names instead of hex codes
- For contours, take account colors, label flag and legend.
- Control image size in pixels
=> Enhance matplotlib backend

lib/src/Base/Stat/NumericalSampleImplementation.cxx, python/test/t_NumericalSample_csv.expout, python/test/t_NumericalSample_csv.py
If the description contains quotes they're not trimmed unliked the flex/bison
implementation.
=> Trim description quotes on text import

lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosAlgorithm.cxx, lib/src/Uncertainty/Distribution/ComposedDistribution.cxx, lib/src/Uncertainty/Model/CopulaImplementation.cxx
1) Improved copula comparison.
+ It allows to detect independent copulas either at the CopulaImplementation level or at the ComposedDistribution level.
2) Fixed comments in FunctionalChaos/FunctionalChaosAlgorithm
3) Improved the simplified interface to FunctionalChaosAlgorithm
+ Now, it favors the use of sparse regression as the performace of this method has been greatly improved.
=> Improve composed distribution comparison

lib/src/Uncertainty/Distribution/GumbelAB.cxx, lib/src/Uncertainty/Distribution/Student.cxx, lib/test/t_Student_std.cxx, python/test/t_DistributionParameters_std.expout, python/test/t_DistributionParameters_std.py, python/test/t_GumbelFactory_std.expout
- Fixes an erroneous conversion in GumbelAB
- Fixes Student parameters accessors order consistency
=> Fix distribution parameters troubles

.travis.yml
related to https://github.com/sphinx-doc/sphinx/pull/2770
=> Require Python six module to install Sphinx

python/doc/developer_guide/windows_port.rst
Most of it was deprecated.
Include module compilation dependency
=> Rewrite windows port doc

ChangeLog, lib/src/Base/Stat/NumericalSampleImplementation.cxx
Fixes http://trac.openturns.org/ticket/849
=> Check NumericalSample::computeQuantile probability

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Algorithm/Simulation/SubsetSampling.cxx, lib/src/Uncertainty/Algorithm/Simulation/openturns/SubsetSampling.hxx, python/src/SubsetSampling_doc.i.in
The term conditional probability is more appropriate.
=> Subset enhancements

ChangeLog, lib/src/Uncertainty/Distribution/StudentFunctions.cxx
Attempt to fix http://trac.openturns.org/ticket/604
=> Use large-nu case sooner in NonCentralStudentCDF

ChangeLog, lib/src/Base/Type/ComplexMatrixImplementation.cxx, lib/src/Base/Type/openturns/ComplexMatrix.hxx
Fixes trac#802.
Not sure why this change is needed though. 
Other *Matrix::solveLinearSystem methods were not affected.
=> Fix problems with SWIG binding of ComplexMatrix::solveLinearSystem

lib/src/Uncertainty/Model/DistributionParameters.cxx, lib/src/Uncertainty/Model/DistributionParametersImplementation.cxx, lib/src/Uncertainty/Model/openturns/DistributionParameters.hxx, lib/src/Uncertainty/Model/openturns/DistributionParametersImplementation.hxx, python/src/ArcsineMuSigma_doc.i.in, python/src/BetaMuSigma_doc.i.in, python/src/DistributionParametersImplementation_doc.i.in, python/src/DistributionParameters_doc.i.in, python/src/GammaMuSigma_doc.i.in, python/src/GumbelAB_doc.i.in, python/src/GumbelMuSigma_doc.i.in, python/src/LogNormalMuSigmaOverMu_doc.i.in, python/src/LogNormalMuSigma_doc.i.in, python/src/WeibullMuSigma_doc.i.in, python/test/t_DistributionParameters_std.py
Allows to convert attribute values to native parameters
=> Add DistributionParameters::evaluate

lib/src/Base/Stat/AbsoluteExponential.cxx, lib/src/Base/Stat/DiracCovarianceModel.cxx, lib/src/Base/Stat/ExponentiallyDampedCosineModel.cxx, lib/src/Base/Stat/GeneralizedExponential.cxx, lib/src/Base/Stat/MaternModel.cxx, lib/src/Base/Stat/SphericalModel.cxx, lib/src/Base/Stat/SquaredExponential.cxx, lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx, lib/src/Base/Stat/openturns/DiracCovarianceModel.hxx
1) Do not define new covariance attribut in DiracCovarianceModel but use this already defined one
2) We should add nugget factor if values are very small and not exactly zero (as done in Matern)
=> Homogenization in covariance models

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Stat/HMatrix.cxx, lib/src/Base/Stat/HMatrixFactory.cxx, lib/src/Base/Stat/openturns/HMatrix.hxx
HMatrix-AdmissibilityFactor can again be used to define parameter of the standard admissiblity condition.
New HMatrix-ClusteringAlgorithm resource entry to specify clustering algorithm.
New HMatrix::dump method.
=> More customizations for hmat

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Func/SpecFunc/SpecFunc.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralizedLinearModelAlgorithm.hxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingAlgorithm.hxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingResult.hxx, lib/test/t_GeneralizedLinearModelAlgorithm_std.cxx, python/src/GeneralizedLinearModelAlgorithm_doc.i.in, python/src/GeneralizedLinearModelResult_doc.i.in, python/src/KrigingAlgorithm_doc.i.in, python/src/KrigingResult_doc.i.in, python/test/t_GeneralizedLinearModelAlgorithm_std.py
- Add a flag to optimize covariance model parameters (adutfoy/control_glm_optim)
- Homogenize covariance model, spectral model parameters names and order
- Kriging observation noise
- Add Kriging samples accessors
=> Kriging enhancements

ChangeLog, lib/etc/openturns.conf.in, lib/src/Base/Algo/Classifier.cxx, lib/src/Base/Algo/ClassifierImplementation.cxx, lib/src/Base/Algo/openturns/Classifier.hxx, lib/src/Base/Algo/openturns/ClassifierImplementation.hxx, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Func/ExpertMixture.cxx, lib/src/Base/Func/openturns/ExpertMixture.hxx, lib/src/Uncertainty/Algorithm/Classification/MixtureClassifier.cxx, lib/src/Uncertainty/Algorithm/Classification/openturns/MixtureClassifier.hxx, lib/src/Uncertainty/Distribution/BernsteinCopulaFactory.cxx, lib/src/Uncertainty/Distribution/openturns/BernsteinCopulaFactory.hxx, python/doc/pyplots/MixtureClassifier.py, python/doc/user_manual/response_surface/response_surface.rst, python/src/BernsteinCopulaFactory_doc.i.in, python/src/ClassifierImplementation_doc.i.in, python/src/Classifier_doc.i.in
Now, both grade() and classify() methods are parallelized and/or vectorized.
=> Improved Classifier/MixtureClassifier/ExpertMixture

lib/src/Base/Stat/StationaryCovarianceModel.cxx, lib/test/t_ExponentialModel_std.cxx, lib/test/t_ExponentialModel_std.expout, python/test/t_ExponentialModel_std.expout, python/test/t_ExponentialModel_std.py
When called using a RegularGrid, the diagonal blocks were not properly computed.
=> Fixed StationaryCovarianceModel::discretize()

python/src/ComplexMatrix.i, python/src/Distribution.i, python/src/DistributionImplementation.i, python/src/HermitianMatrix.i, python/src/Matrix.i, python/src/NumericalPoint.i, python/src/NumericalSample.i, python/src/SquareComplexMatrix.i, python/src/SquareMatrix.i, python/src/SymmetricMatrix.i, python/src/TriangularComplexMatrix.i, python/src/TriangularMatrix.i
It is shadowed since https://github.com/swig/swig/commit/1079ba7
=> Hide truediv from swig 3.0.11

lib/src/Base/Func/DatabaseFunction.cxx, lib/src/Base/Func/openturns/DatabaseFunction.hxx, lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosAlgorithm.cxx, python/src/DatabaseFunction_doc.i.in, python/src/NumericalMathFunction.i, python/src/ParametricFunction_doc.i.in, python/src/PythonNumericalMathEvaluationImplementation.cxx, python/src/openturns/PythonNumericalMathEvaluationImplementation.hxx, python/test/t_ANCOVA_std.py, python/test/t_FAST_std.py, python/test/t_NumericalMathFunction_python.expout, python/test/t_NumericalMathFunction_python.py, python/test/t_OptimalLHSExperiment_ishigami.py
Mainly enhances DatabaseFunction with a cache flag (as in the eval impl) and removes the specific Python parametric accessor (follow-up to http://trac.openturns.org/ticket/873)
=> Function api changes

ChangeLog, lib/src/Base/Algo/SVDMethod.cxx, lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosAlgorithm.cxx, lib/src/Uncertainty/Algorithm/Transformation/CMakeLists.txt, lib/src/Uncertainty/Algorithm/Transformation/DistributionTransformation.cxx, lib/src/Uncertainty/Algorithm/Transformation/openturns/DistributionTransformation.hxx, lib/src/Uncertainty/Algorithm/Transformation/openturns/OTTransformation.hxx, lib/src/Uncertainty/Model/EllipticalDistribution.cxx, python/doc/user_manual/isoprobabilistic_transformation.rst, python/src/CMakeLists.txt, python/src/DistributionTransformation.i, python/src/DistributionTransformation_doc.i.in, python/src/transformation_module.i, python/test/CMakeLists.txt, python/test/t_DistributionTransformation_std.expout, python/test/t_DistributionTransformation_std.py
- Add MetaModelAlgorithm::buildTransformation (factorize code for tensor)
- Check eigen values in SVD (possible numerical issue with specific doe)
=> MetaModel enhancements

lib/src/Base/Stat/CovarianceModelImplementation.cxx, lib/src/Base/Stat/SquaredExponential.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx
=> CovarianceModel serialization improvements

python/src/DrawableImplementation.i, python/src/__init__.py, python/src/viewer.py, python/test/t_Viewer.py
The PR provides minor changes : 
- Fix potential circular/recursive import in viewer
- Provide a SVG export to drawables
=> Minor cosmetics

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Process/ARMA.cxx, lib/src/Uncertainty/Process/WhiteNoise.cxx, python/src/ResourceMap_doc.i.in
Only require it in the context of an ARMA process.
=> Remove the centered WhiteNoise constraint

ChangeLog, lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/openturns/MarginalTransformationEvaluation.hxx, python/src/FunctionalChaosRandomVector_doc.i.in, python/src/viewer.py
This PR fixes some minor bugs : 
- Missing labels with Contour drawable (in the Viewer side) http://trac.openturns.org/ticket/878
- Incomplete docstring http://trac.openturns.org/ticket/879
- MarginalTranformationEvaluation::operator() : it should be evaluated with a NumericalSample argument
=> Various fixes

lib/src/Uncertainty/Algorithm/TaylorExpansionMoments.cxx, lib/src/Uncertainty/Distribution/openturns/MaximumDistribution.hxx, lib/src/Uncertainty/StatTests/VisualTest.cxx, python/doc/user_manual/probabilistic_modelling.rst, python/src/Arcsine_doc.i.in, python/src/CMakeLists.txt, python/src/ClaytonCopula_doc.i.in, python/src/CovarianceModelImplementation_doc.i.in, python/src/GeneralLinearModelResult_doc.i.in, python/src/KrigingResult_doc.i.in, python/src/MaximumDistribution.i, python/src/MaximumDistribution_doc.i.in, python/src/VisualTest_doc.i.in, python/src/WelchFactory_doc.i.in
=> Various documentation enhancements

ChangeLog, TODO, lib/include/openturns/OTtypes.hxx, lib/src/Base/Func/SpecFunc/SpecFunc.cxx, lib/src/Base/Func/SpecFunc/openturns/SpecFunc.hxx, python/src/ComplexMatrixImplementation.i, python/src/Point.i
This reverts commit 2c354398c5492029dde3df6385002d7d0a11a7f9.
=> Revert "Removed NumericalScalar, NumericalComplex"

ChangeLog, lib/src/Uncertainty/Distribution/RandomMixture.cxx, lib/test/t_RandomMixture_std.expout, python/test/t_RandomMixture_std.expout
=> Fix RandomMixture::getSample

ChangeLog, lib/src/Base/Stat/CovarianceModel.cxx, lib/src/Base/Stat/CovarianceModelImplementation.cxx, lib/src/Base/Stat/SampleImplementation.cxx, lib/src/Base/Stat/openturns/CovarianceModel.hxx, lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx, lib/src/Uncertainty/StatTests/VisualTest.cxx, lib/src/Uncertainty/StatTests/openturns/VisualTest.hxx, python/src/CovarianceModelImplementation_doc.i.in, python/src/CovarianceModel_doc.i.in, python/src/VisualTest_doc.i.in, python/src/viewer.py
- Fix Sample::sortUnique which provides default description even if intial sample provides a different one
- Perform VisualTest::DrawEmpiricalCDF (xMin/xMax are now optional)
- In CovarianceModel, fix some docstrings, setParameter method; Made also {g,s}etFullParameter and getFullParameterDescription public
=> Various fixes and enhancements

circle.yml
Fixes circleci build waiting for the numpydoc fix:
https://github.com/numpy/numpydoc/pull/93
=> Use sphinx stable

lib/src/Base/Optim/OptimizationAlgorithm.cxx, lib/src/Base/Optim/OptimizationAlgorithmImplementation.cxx, lib/src/Base/Optim/openturns/OptimizationAlgorithm.hxx, lib/src/Base/Optim/openturns/OptimizationAlgorithmImplementation.hxx, lib/src/Uncertainty/Algorithm/Simulation/Simulation.cxx, lib/src/Uncertainty/Algorithm/Simulation/openturns/Simulation.hxx, python/doc/examples/numerical_methods/control_termination.ipynb, python/doc/examples/numerical_methods/numerical_methods.rst
- FORM termination example using iteration limit
- MonteCarlo termination using time limit
=> Add callback examples

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Common/Study.cxx, lib/src/Base/Common/XMLStorageManager.cxx, lib/src/Base/Common/XMLToolbox.cxx, lib/src/Base/Common/openturns/Study.hxx, lib/src/Base/Common/openturns/XMLStorageManager.hxx, lib/src/Base/Common/openturns/XMLToolbox.hxx, lib/test/t_Study_saveload.cxx, python/src/Study_doc.i.in, python/src/XMLStorageManager_doc.i.in, python/test/t_Study_saveload.py
Using even the weakest compression leads to a 6 times smaller file!
=> Added zlib compression to XMLStorageManager

LICENSE, README.rst
=> Added a LICENSE file

python/doc/user_manual/functions.rst, python/src/__init__.py, python/src/coupling_tools.py
Completed documentation of parameters
Added active doctests
Add documentation of get
=> Enhance coupling_tools docstring

lib/src/Uncertainty/Distribution/RandomMixture.cxx, lib/test/t_GeneralizedExtremeValue_std.expout, lib/test/t_RandomMixture_std.cxx, lib/test/t_RandomMixture_std.expout, python/test/t_RandomMixture_std.expout, python/test/t_RandomMixture_std.py
The flag 'tail' was not taken into account.
Also fixed a bug in the simplification mechanism for Gamma-like atoms with negative weights.
=> Fixed a bug in computeScalarQuantile() in RandomMixture

python/src/Dirac_doc.i.in
this is required with the recent of update of numpydoc 0.7
=> Fix Dirac duplicate Notes section

.travis.yml
The build still timeouts on busy hours.
=> Disable sphinx on Travis

circle.yml, python/doc/sphinxext/execforresourcemap_directive.py
Allows to keep an eye on sphinx development, requires to use numpydoc git too.
=> Use sphinx git

lib/src/Uncertainty/Model/DistributionImplementation.cxx, python/src/PythonDistribution.cxx, python/src/openturns/PythonDistribution.hxx, python/test/t_CumulativeDistributionNetwork_std.expout, python/test/t_CumulativeDistributionNetwork_std.py, python/test/t_Distribution_python.expout, python/test/t_Distribution_python.py
- Add PythonDistribution::getMarginal(int)
- Fix DistributionImplementation::getMarginal
=> PythonDistribution enhancements

.travis.yml
We enforce bison/flex in travis. This prepares work on the conda packages
=> Use of flex/bison for parsing CSV in travis

ChangeLog, lib/src/Base/Stat/SampleImplementation.cxx, lib/test/t_Sample_csv.cxx, lib/test/t_Sample_csv.expout, python/test/t_Sample_csv.expout, python/test/t_Sample_csv.py
Bug was introduced in https://github.com/regislebrun/openturns/commit/9ea891af251523e0ce599c59ed354901acc42f74
=> Fix http://trac.openturns.org/ticket/897

ChangeLog, TODO, lib/include/CMakeLists.txt, lib/include/OTconfigure_args.hxx.in, lib/src/Base/Common/PlatformInfo.cxx, lib/src/Base/Common/openturns/PlatformInfo.hxx, lib/src/openturns-config-build.in
They prevent reproducible builds.
=> Remove unused variables from openturns-config

python/src/viewer.py
For dimension > 2, the PlotDesign should revert x & y axes
=> Fix PlotDesign

lib/src/Uncertainty/Distribution/Histogram.cxx, lib/src/Uncertainty/Distribution/openturns/Histogram.hxx, lib/test/t_Histogram_std.cxx, lib/test/t_Histogram_std.expout, python/doc/_templates/Distribution.rst_t, python/src/Histogram_doc.i.in, python/test/t_Histogram_std.expout, python/test/t_Histogram_std.py
This PR also provides a new constructor for Histogram, based on ticks/frequencies
=> Fixed ticket #912 (wrong description of Histogram constructor parameters)

ChangeLog, lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/MarginalTransformationEvaluation.cxx, python/test/t_MarginalTransformationEvaluation_std.expout, python/test/t_MarginalTransformationEvaluation_std.py
T(x) = gamma2+lambda1/lambda2*(x-gamma1)
Fixes http://trac.openturns.org/ticket/919
=> Fix MarginalTransEval exponential simplification

python/src/viewer.py
when setting labels, otherwise newer matplotlib throws
=> Fix contour plot with newer matplotlib

python/test/CMakeLists.txt
=> Test notebooks separately

python/src/BoxCoxFactory_doc.i.in, python/src/ConditionedGaussianProcess_doc.i.in, python/src/GeneralLinearModelAlgorithm_doc.i.in, python/src/GeneralLinearModelResult_doc.i.in, python/src/KrigingAlgorithm_doc.i.in, python/src/KrigingRandomVector_doc.i.in
generelized linear model --> general linear model
=> Various fixes in docstring

.travis.yml
Latests PRs seem to timeout because of them
=> [TravisCI] Split CXX/Python tests on Linux

python/doc/install.rst
so that the package manager kwnows how to update
=> Add conda-forge channel when installing

lib/src/Uncertainty/Distribution/ComposedDistribution.cxx, lib/src/Uncertainty/Distribution/ConditionalDistribution.cxx
Call computePDF(Sample) instead of looping over computePDF(Point),
this is much faster.
=> Performance improvements for ConditionalDistribution

lib/src/Base/Stat/SampleImplementation.cxx, python/test/t_Sample_csv.expout, python/test/t_Sample_csv.py
allows to read windows files from unix
=> Sample::BuildFromTextFile to handle CRLFs

python/src/CanonicalTensorEvaluation_doc.i.in, python/src/DesignProxy_doc.i.in, python/src/FieldFunction.i, python/src/FunctionImplementation_doc.i.in, python/src/LeastSquaresMethodImplementation_doc.i.in, python/src/PosteriorDistribution_doc.i.in, python/src/RankMCovarianceModel_doc.i.in, python/src/Sample_doc.i.in, python/src/SphericalModel_doc.i.in, python/src/coupling_tools.py, python/src/typ_module.i, python/src/viewer.py
Sample::asPoint and clear were missing, the others are pep257 fixes.
=> Few docstring fixes

ChangeLog, lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesAlgorithmImplementation.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesExperiment.cxx, python/doc/pyplots/JansenSensitivityAlgorithm.py, python/doc/pyplots/MartinezSensitivityAlgorithm.py, python/doc/pyplots/MauntzKucherenkoSensitivityAlgorithm.py, python/doc/pyplots/SaltelliSensitivityAlgorithm.py, python/doc/pyplots/SobolIndicesAlgorithm.py, python/doc/user_manual/statistics_on_sample.rst, python/src/Text_doc.i.in
+ Improved SobolIndicesAlgorithm::draw(). As it is not possible to customize axes, the description of each input is written on the right of each Sobol index. It fixes tickets #918 and #929.
+ Fixed the documentation of Text
=> Fix sobol sensitivity indices plot

lib/src/Base/Optim/NLopt.cxx, lib/src/Base/Optim/TNC.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx, python/src/metamodel_module.i
INFO should give reasonable amount of output, user may change log level to DEBUG to have full output.
=> Let GLMAlgo be less verbose

ChangeLog, lib/src/Uncertainty/Distribution/GeneralizedParetoFactory.cxx, lib/src/Uncertainty/Distribution/openturns/GeneralizedParetoFactory.hxx, lib/test/t_LogNormalFactory_std.cxx, lib/test/t_LogNormalFactory_std.expout, python/src/GeneralizedParetoFactory_doc.i.in, python/src/LogNormalFactory_doc.i.in, python/test/t_LogNormalFactory_std.expout, python/test/t_LogNormalFactory_std.py
The problem was in the method of exponential regression, where the case of a repeated minimum value in the sample was not correctly managed.
=> Fixed ticket #924 (Problem with GeneralizedParetoFactory)

CMakeLists.txt, cmake/gcc_sync_builtins.cxx, distro/windows/Makefile, lib/include/OTconfig.h.in, lib/include/installed-OTconfig.h.in, lib/src/Base/Common/AtomicFunctions.cxx, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Common/openturns/AtomicFunctions.hxx
=> Maintenance fixes

ChangeLog, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx, lib/src/Uncertainty/Process/GaussianProcess.cxx
=> Fix build without muParser

lib/src/Base/Stat/SampleImplementation.cxx, python/test/t_Sample_csv.py
This is a regression in cfe3591; we exit the getline loop if we do not encounter a newline character, now we continue until eof or failure.
=> ImportFromTextFile to read last line

lib/src/Base/Geom/Interval.cxx, lib/src/Base/Geom/openturns/Interval.hxx, python/src/Interval_doc.i.in, python/test/t_Interval_std.expout, python/test/t_Interval_std.py
Useful in multivariate TruncatedDistribution
cc @aurelieladier
=> Add Interval::getMarginal

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralLinearModelAlgorithm.hxx, lib/test/t_KrigingAlgorithm_std.expout, lib/test/t_KrigingAlgorithm_std_hmat.expout
Optimization bounds are computed by setCovarianceModel(), thus inputTransformation_
must be set before this method is called.
=> If input is normalized, also normalize optimization bounds

circle.yml, lib/src/Uncertainty/Distribution/KernelMixture.cxx, lib/src/Uncertainty/Distribution/Normal.cxx, lib/src/Uncertainty/Distribution/ProductDistribution.cxx, lib/src/Uncertainty/Distribution/RandomMixture.cxx, lib/src/Uncertainty/Distribution/RatioDistribution.cxx, lib/src/Uncertainty/Distribution/Student.cxx, lib/src/Uncertainty/Distribution/openturns/RandomMixture.hxx, lib/src/Uncertainty/Model/DistributionImplementation.cxx, lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx, lib/test/t_RandomMixture_std.expout, python/doc/_templates/Distribution.rst_t, python/src/CMakeLists.txt
Allows to better detect what changes on openturns.github.io, which is also gettting quite huge.
- We set SOURCE_DATE_EPOCH to 1/1/17 which is handled by sphinx, for master builds.
- Do not install the sphinx doctree dir anymore.
- ProductDistribution does not yield reproducible cdf graphs with TBB enabled, so disable it in Distribution graph template.
=> Reproducible doc builds on CircleCI

python/src/JansenSensitivityAlgorithm_doc.i.in, python/src/SobolIndicesAlgorithmImplementation_doc.i.in
Also add dots columns to matrix notations
=> Fix Jansen estimator documentation

.travis.yml, circle.yml
https://github.com/travis-ci/travis-ci/issues/8826
https://github.com/scipy/scipy/pull/8197
=> [Travis] uninstall oclint

circle.yml
=> [CircleCI] pip upgrade

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Distribution/FisherSnedecorFactory.cxx, lib/src/Uncertainty/Distribution/MaximumLikelihoodFactory.cxx, lib/src/Uncertainty/Distribution/TrapezoidalFactory.cxx, lib/src/Uncertainty/Distribution/TruncatedNormalFactory.cxx, lib/src/Uncertainty/Distribution/openturns/FisherSnedecorFactory.hxx, lib/src/Uncertainty/Distribution/openturns/TrapezoidalFactory.hxx, lib/src/Uncertainty/Distribution/openturns/TruncatedNormalFactory.hxx, python/src/TrapezoidalFactory_doc.i.in, python/src/TruncatedNormalFactory_doc.i.in
- the constraint was not taken into account
- factories using MLF did not take their solver attribute into account, removed it in favor of an RM key to set the MLF solver
=> MaximumLikelihoodFactory enhancements

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Distribution/ComposedCopula.cxx, lib/src/Uncertainty/Distribution/MarginalDistribution.cxx, python/doc/examples/data_analysis/data_analysis.rst, python/doc/examples/data_analysis/estimate_multivariate_distribution.ipynb
- ComposedCopula::getMarginal to handle non-contiguous dependency blocs
- MarginalDistribution::isCopula correctly handles the isCopula flag
use case:
https://gist.github.com/jschueller/7585cf999a0f1104d451e23c43024768
=> Copulas related enhancements

lib/src/Base/Algo/ApproximationAlgorithmImplementationFactory.cxx, lib/src/Base/Optim/OptimizationAlgorithmImplementation.cxx, lib/src/Base/Stat/FaureSequence.cxx, lib/src/Base/Stat/HaltonSequence.cxx, lib/src/Base/Stat/HaselgroveSequence.cxx, lib/src/Base/Stat/ReverseHaltonSequence.cxx, lib/src/Base/Stat/TimeSeries.cxx, lib/src/Base/Stat/openturns/HaselgroveSequence.hxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/InverseNatafIndependentCopulaEvaluation.cxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/InverseNatafIndependentCopulaGradient.cxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/InverseNatafIndependentCopulaHessian.cxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/NatafIndependentCopulaEvaluation.cxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/NatafIndependentCopulaGradient.cxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/NatafIndependentCopulaHessian.cxx, lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula/openturns/InverseNatafIndependentCopulaEvaluation.hxx, lib/src/Uncertainty/Process/ARMALikelihoodFactory.cxx, python/src/MCMC_doc.i.in
Fix serialization of some classes:
- Low discrpenacy sequence
- TimeSeries
- ApproximationAlgorithmImplementationFactory
=> Fix serialization

ChangeLog, lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Model/DistributionFactoryImplementation.cxx
Fixes http://trac.openturns.org/ticket/938
=> DistFactory::buildEstimator to handle Exceptions

python/doc/user_manual/user_manual.rst, python/src/AdaptiveStrategyImplementation_doc.i.in, python/src/BoxCoxFactory_doc.i.in, python/src/DickeyFullerTest_doc.i.in, python/src/DrawableImplementation_doc.i.in, python/src/EvaluationImplementation_doc.i.in, python/src/FixedExperiment_doc.i.in, python/src/HistoryStrategyImplementation_doc.i.in, python/src/JansenSensitivityAlgorithm_doc.i.in, python/src/KarhunenLoeveAlgorithmImplementation_doc.i.in, python/src/KrigingAlgorithm_doc.i.in, python/src/LeastSquaresStrategy_doc.i.in, python/src/LinearModelFactory_doc.i.in, python/src/LogNormalFactory_doc.i.in, python/src/LowDiscrepancySequenceImplementation_doc.i.in, python/src/MCMC_doc.i.in, python/src/Matrix_doc.i.in, python/src/Mixture_doc.i.in, python/src/ProjectionStrategyImplementation_doc.i.in, python/src/RandomVectorImplementation_doc.i.in, python/src/SORM_doc.i.in, python/src/SimulationResultImplementation_doc.i.in, python/src/SpectralGaussianProcess_doc.i.in, python/src/SymbolicFunction_doc.i.in, python/src/SymmetricTensor_doc.i.in, python/src/TaylorExpansionMoments_doc.i.in, python/src/VisualTest_doc.i.in
This fixes the doc of the total index
See text of 2.3 "alternate design" of the jansen paper
=> Fix Jansen Sobol estimator doc

python/doc/examples/numerical_methods/control_termination.ipynb, python/doc/user_manual/functions.rst, python/src/ProbabilitySimulationAlgorithm.i, python/src/Simulation.i
Allows to define a maximum duration for simulation, optimization algorithms.
Uses system time (wall time), not cpu clock time.
=> Predefined TimerCallback callback

lib/src/Base/Func/P1LagrangeEvaluation.cxx
Hopefully Mesh::getVerticesToSimplicesMap() may become obsolete.
It was used in P1LagrangeEvaluation::setMesh(), but code has been
rewritten without this method.
=> No need to use Mesh::getVerticesToSimplicesMap() here

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Geom/Mesh.cxx
Removed warnings on shadowed variables, added missing entries in openturns.conf and fixed unused function. Sorry.
=> Fix pr657 glitches

python/src/openturns/PythonWrappingFunctions.hxx
Dont try to convert the exception value directly,
look if it has an str(obj) operator.
Allows to retrieve joblib exceptions.
=> Try to convert Python exception value

ChangeLog, lib/src/Base/Graph/Drawable.cxx, lib/src/Base/Graph/DrawableImplementation.cxx, lib/src/Base/Graph/openturns/Drawable.hxx, lib/src/Base/Graph/openturns/DrawableImplementation.hxx, python/src/DrawableImplementation_doc.i.in, python/src/Drawable_doc.i.in, python/src/viewer.py, python/test/t_Viewer.py
This PR allows to force orthonormal axes and to draw the axes according to the value of Graph::getAxes(). It also provides a better implementation of color conversion in Drawable.
=> Improve viewer

lib/src/Uncertainty/Distribution/Wishart.cxx, lib/test/t_Wishart_std.expout, python/test/t_InverseWishart_std.expout, python/test/t_InverseWishart_std.py, python/test/t_Wishart_std.expout, python/test/t_Wishart_std.py
Partially adresses http://trac.openturns.org/ticket/940
=> Fix Wishart parameter accessors

ChangeLog, lib/src/Base/Algo/NearestNeighbourAlgorithm.cxx, lib/src/Base/Algo/RegularGridNearestNeighbour.cxx, lib/src/Base/Algo/openturns/RegularGridNearestNeighbour.hxx, lib/src/Base/Geom/RegularGrid.cxx, lib/src/Base/Stat/Field.cxx, lib/src/Base/Stat/FieldImplementation.cxx, lib/src/Base/Stat/openturns/Field.hxx, lib/src/Base/Stat/openturns/FieldImplementation.hxx, python/src/FieldImplementation_doc.i.in, python/src/Field_doc.i.in
Prefer RegularGridNearestNeighbour on a RegularGrid, it provides faster
instantiation and queries.
Add missing methods in RegularGridNearestNeighbour.
=> Better default NearestNeighbourAlgorithm

lib/src/Base/Algo/KarhunenLoeveP1Algorithm.cxx, lib/src/Base/Algo/KarhunenLoeveSVDAlgorithm.cxx
It now builds its KDTree, thus it should be reused when possible.
=> Reuse P1LagrangeEvaluation

lib/src/Base/Algo/KarhunenLoeveResultImplementation.cxx, lib/src/Base/Func/MonomialFunctionFactory.cxx
Call new directly to build it only once.
=> Do not call clone() on a newly built object

lib/src/Base/Stat/CovarianceModelFactoryImplementation.cxx, lib/src/Base/Stat/NonStationaryCovarianceModelFactory.cxx, lib/src/Base/Stat/SpectralModelFactoryImplementation.cxx, lib/src/Base/Stat/StationaryCovarianceModelFactory.cxx, lib/src/Base/Stat/WelchFactory.cxx, lib/src/Base/Stat/openturns/CovarianceModelFactoryImplementation.hxx, lib/src/Base/Stat/openturns/NonStationaryCovarianceModelFactory.hxx, lib/src/Base/Stat/openturns/SpectralModelFactoryImplementation.hxx, lib/src/Base/Stat/openturns/StationaryCovarianceModelFactory.hxx, lib/src/Base/Stat/openturns/WelchFactory.hxx
This is a follow-up for PR #704.
SpectralModelFactoryImplementation::build returns a SpectralModel.
=> Let CovarianceModelFactoryImplementation::build return a CovarianceModel

ChangeLog, lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, python/src/Drawable.i, python/src/DrawableImplementation.i, python/src/Graph.i, python/src/viewer.py, python/test/t_Viewer.py
Avoids to send a huge svg file when the data is big:
http://trac.openturns.org/ticket/944
=> Use PNG format for inline notebook plot 

lib/src/Base/Common/XMLStorageManager.cxx, python/test/t_Study_saveload.expout, python/test/t_Study_saveload.py
Nan/inf values are correctly written to xml, but converted to 0 when reading back.
=> Allow to serialize nan/inf values

python/src/CalibrationStrategyImplementation_doc.i.in, python/src/KrigingResult_doc.i.in
Fixes the broken sphinx build since a few days
=> Fix docstring indentation

circle.yml
Version 0.3.2 had a bug:
https://github.com/spatialaudio/nbsphinx/issues/174
=> [CircleCI] Unpin nbsphinx

ChangeLog, lib/src/Uncertainty/Distribution/ConditionalDistribution.cxx
=> Improve error message

lib/src/Base/Common/openturns/SharedPointer.hxx, lib/src/Base/Func/openturns/exprtk.hpp, lib/src/Base/Stat/SampleImplementation.cxx, lib/src/Uncertainty/Distribution/BinomialFactory.cxx
=> More gcc8 warning fixes

lib/src/Base/Algo/KarhunenLoeveResult.cxx, lib/src/Base/Algo/openturns/KarhunenLoeveResult.hxx, lib/src/Base/Algo/openturns/KarhunenLoeveResultImplementation.hxx
It is provided in documentation but not implemented.
=> Add KarhunenLoeveResult constructor

ChangeLog, lib/src/Uncertainty/Algorithm/Transformation/DistributionTransformation.cxx, lib/src/Uncertainty/Distribution/ComposedDistribution.cxx, lib/src/Uncertainty/Distribution/Mixture.cxx, lib/src/Uncertainty/Distribution/openturns/Mixture.hxx, lib/src/Uncertainty/Model/DistributionImplementation.cxx, lib/test/t_Mixture_std.cxx, lib/test/t_Mixture_std.expout, python/test/t_Mixture_std.expout, python/test/t_Mixture_std.py
This PR fixes the bug described in [ticket #952](http://trac.openturns.org/ticket/952) by adding missing Mixture parameter accessors.
=> Fix mixture parameter accessors

lib/src/Uncertainty/Distribution/BurrFactory.cxx, python/test/t_BurrFactory_std.py
sumLogXC cannot be 0 else k is inf,
but now we also check that sumLogXC is not inf (=> k=0, and sumRatio=-nan)
=> Fix BurrFactory error checking

lib/src/Uncertainty/Distribution/HistogramFactory.cxx, python/test/t_HistogramFactory_std.expout, python/test/t_HistogramFactory_std.py
Using the 2nd rule (useQuantile=False) always returns QauntileEpsilon
=> Fix HistogramFactory::computeSilvermanBandwidth

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Stat/HMatrixFactory.cxx, lib/src/Base/Stat/HMatrixImplementation.cxx
The hmat API just changed: https://github.com/jeromerobert/hmat-oss/commit/20e06f22a551b5386e8b78ea5ed98d1861024093
=> hmat: drop maxParallelLeaves

.circleci/config.yml, python/doc/conf.py.in
=> [Doc] Hide sphinx version

ChangeLog, TODO, lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/StatTests/DickeyFullerTest.cxx, lib/src/Uncertainty/StatTests/FittingTest.cxx, lib/src/Uncertainty/StatTests/HypothesisTest.cxx, lib/src/Uncertainty/StatTests/LinearModelTest.cxx, lib/src/Uncertainty/StatTests/NormalityTest.cxx, lib/src/Uncertainty/StatTests/openturns/DickeyFullerTest.hxx, lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx, lib/src/Uncertainty/StatTests/openturns/HypothesisTest.hxx, lib/src/Uncertainty/StatTests/openturns/NormalityTest.hxx, lib/test/t_DickeyFullerTest_std.cxx, lib/test/t_FittingTest_std.cxx, lib/test/t_HypothesisTest_correlation.cxx, lib/test/t_HypothesisTest_std.cxx, python/doc/theory/data_analysis/linear_regression.rst, python/doc/user_manual/statistics_on_sample.rst, python/src/DickeyFullerTest_doc.i.in, python/src/FittingTest_doc.i.in, python/src/HypothesisTest_doc.i.in, python/src/LinearModelTest_doc.i.in, python/src/NormalityTest_doc.i.in, python/src/TestResult_doc.i.in, python/test/t_DickeyFullerTest_std.py, python/test/t_FittingTest_std.py, python/test/t_HypothesisTest_correlation.py, python/test/t_HypothesisTest_std.py, python/test/t_LinearModelTest_std.expout
... instead of 1-risk
follow-up of #812
=> Parametrize statistical tests by first kind risk

ChangeLog, lib/src/Uncertainty/Distribution/ArcsineMuSigma.cxx, lib/src/Uncertainty/Distribution/BetaMuSigma.cxx, lib/src/Uncertainty/Distribution/GumbelAB.cxx, lib/src/Uncertainty/Distribution/GumbelMuSigma.cxx, lib/src/Uncertainty/Distribution/LogNormalMuSigma.cxx, lib/src/Uncertainty/Distribution/LogNormalMuSigmaOverMu.cxx, lib/src/Uncertainty/Distribution/WeibullMuSigma.cxx, lib/src/Uncertainty/Distribution/openturns/ArcsineMuSigma.hxx, lib/src/Uncertainty/Distribution/openturns/BetaMuSigma.hxx, lib/src/Uncertainty/Distribution/openturns/GumbelAB.hxx, lib/src/Uncertainty/Distribution/openturns/GumbelMuSigma.hxx, lib/src/Uncertainty/Distribution/openturns/LogNormalMuSigma.hxx, lib/src/Uncertainty/Distribution/openturns/LogNormalMuSigmaOverMu.hxx, lib/src/Uncertainty/Distribution/openturns/WeibullMuSigma.hxx, python/test/t_Study_saveload.py
This fixes http://trac.openturns.org/ticket/964
=> Allow serialization of DistributionParameters classes

ChangeLog, python/src/MetaModelValidation_doc.i.in
Fix http://trac.openturns.org/ticket/962
=> Minor bugfix in documentation

ChangeLog, python/src/PythonEvaluation.cxx, python/test/t_Function_python.expout, python/test/t_Function_python.py
We have to check for exceptions after the evaluation of each point.
Closes http://trac.openturns.org/ticket/965
=> Fix error handling in operator(Sample)

ChangeLog, python/src/viewer.py, python/test/t_Viewer.py
http://trac.openturns.org/ticket/961
=> Viewer enhancements

lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/MarginalTransformationEvaluation.cxx, lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/openturns/MarginalTransformationEvaluation.hxx
=> Wrong type in MarginalTransformationEvaluation

ChangeLog, lib/src/Base/Graph/DrawableImplementation.cxx, python/doc/conf.py.in, python/src/viewer.py
xref http://trac.openturns.org/ticket/979
I dont know how to modify the hatch linestyle though.
=> Viewer: handle barplot fillstyle

lib/include/installed-OTconfig.h.in, lib/src/Base/Optim/Cobyla.cxx, lib/src/Base/Optim/NLopt.cxx, python/src/AbdoRackwitz_doc.i.in, python/src/Cobyla_doc.i.in, python/src/NLopt_doc.i.in, python/src/OptimizationAlgorithm.i, python/src/OptimizationAlgorithmImplementation.i, python/src/OptimizationAlgorithmImplementation_doc.i.in, python/src/SQP_doc.i.in, python/src/SimulationAlgorithm.i, python/src/SimulationAlgorithm_doc.i.in, python/src/TNC_doc.i.in, python/test/t_NLopt_std.expout, python/test/t_NLopt_std.py
also adds some documentation to optim solvers
=> NLopt: Fix constraint error computation

ChangeLog, python/doc/user_manual/statistics_on_sample.rst, python/test/t_Distribution_chaospy.py
=> Various enhancements

ChangeLog, python/src/DistributionImplementation.i, python/test/t_Distribution_arithmetic.expout, python/test/t_Distribution_arithmetic.py
=> Python: Add Distribution unary minus

ChangeLog, lib/include/openturns/OTdebug.h
=> Drop BOGUS_PTHREAD_LIBRARY define

ChangeLog, python/doc/theory/data_analysis/bic.rst
Fixes http://trac.openturns.org/ticket/989
=> Updated the theoretical documentation of BIC to match the implementation

ChangeLog, lib/src/Base/Optim/Cobyla.cxx, lib/src/Base/Optim/NLopt.cxx, lib/src/Base/Optim/OPTppImplementation.cxx, lib/src/Base/Optim/openturns/Cobyla.hxx, lib/src/Base/Optim/openturns/NLopt.hxx, lib/src/Base/Optim/openturns/OPTppImplementation.hxx
=> Optim: Avoid reevaluating constraints

python/src/CholeskyMethod_doc.i.in, python/src/QRMethod_doc.i.in, python/src/SVDMethod_doc.i.in
This PR create examples for the SVDMethod, QRMethod and CholeskyMethod, three classes related to linear least squares.
=> New linear least squares examples

ChangeLog, lib/src/Base/Type/Point.cxx, lib/src/Base/Type/openturns/Point.hxx, python/doc/examples/data_analysis/bayesian_calibration_flooding.ipynb
- deprecation goes into 1.13
- removal in master
=> Deprecated Point::setDescription 

python/doc/theory/data_analysis/code_calibration.rst, python/doc/theory/data_analysis/data_analysis.rst, python/doc/theory/data_analysis/gaussian_calibration.rst
Created two help pages to present the calibration algorithms.
=> New calibration theory

ChangeLog, cmake/FindCMinpack.cmake, lib/src/Base/Optim/CMinpack.cxx, lib/src/Base/Optim/Ceres.cxx, lib/src/Base/Optim/NLopt.cxx, lib/src/Base/Optim/OPTppImplementation.cxx, lib/src/Base/Optim/openturns/NLopt.hxx, lib/test/t_OPTpp_std.expout, python/src/CMinpack_doc.i.in, python/src/Ceres_doc.i.in, python/src/LeastSquaresProblem_doc.i.in, python/src/OPTpp_doc.i.in, python/test/t_Ceres_std.py, python/test/t_OPTpp_std.expout
- Ceres line search not supporting bounds
- CMinpack not supporting n>m
=> Misc optim fixes

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Process/DiscreteMarkovChain.cxx, lib/src/Uncertainty/Process/openturns/DiscreteMarkovChain.hxx, python/src/DiscreteMarkovChain_doc.i.in, python/test/t_DiscreteMarkovChain_std.expout, python/test/t_DiscreteMarkovChain_std.py
from the test (I the meantime modified the code for nodes numbering to start from 1):
=> Add MarkovChain DOT export

lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Stat/FieldImplementation.cxx, python/test/t_ExponentialModel_std.expout, python/test/t_ExponentialModel_std.py
Closes #1169
Introduced by https://github.com/openturns/openturns/commit/5b216664014843d2814b8a8ef2ccc4f3a26aec79
=> Fix missing ResourceMap keys

ChangeLog, lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Graph/Drawable.cxx, lib/src/Base/Graph/DrawableImplementation.cxx, lib/src/Base/Graph/Text.cxx, lib/src/Base/Graph/openturns/Drawable.hxx, lib/src/Base/Graph/openturns/DrawableImplementation.hxx, lib/src/Base/Graph/openturns/Text.hxx, python/src/DrawableImplementation_doc.i.in, python/src/Drawable_doc.i.in, python/src/viewer.py, python/test/t_Text_std.py
=> Text drawable to handle text size 

ChangeLog, lib/src/Base/Algo/KarhunenLoeveP1Algorithm.cxx, lib/src/Base/Func/LARS.cxx, lib/src/Base/Optim/AbdoRackwitz.cxx, lib/src/Base/Optim/SQP.cxx, lib/src/Base/Type/Point.cxx, lib/src/Base/Type/openturns/Point.hxx, lib/src/Uncertainty/Algorithm/Analytical/SORMResult.cxx, lib/src/Uncertainty/Algorithm/Analytical/StrongMaximumTest.cxx, lib/src/Uncertainty/Algorithm/MetaModel/TensorApproximation/TensorApproximationAlgorithm.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesAlgorithmImplementation.cxx, lib/src/Uncertainty/Algorithm/Simulation/PostAnalyticalControlledImportanceSampling.cxx, lib/src/Uncertainty/Algorithm/Simulation/QuadrantSampling.cxx, lib/src/Uncertainty/Distribution/Normal.cxx, lib/src/Uncertainty/Model/EllipticalDistribution.cxx, lib/test/t_Point_std.cxx, python/src/Point_doc.i.in, python/test/t_Point_std.py
=> Move dot to Point::dot

python/doc/examples/calibration/calibration_flooding.ipynb
This fixes an error in the methodology description of the singular values of the Jacobian matrix in the linear least squares case. 
Other small fixes in the text as well, but not change in the code.
=> Fixed methodology issue in the flooding example.

lib/src/Base/Stat/HMatrix.cxx, lib/src/Base/Stat/HMatrixImplementation.cxx, lib/src/Base/Stat/openturns/HMatrix.hxx, lib/src/Base/Stat/openturns/HMatrixImplementation.hxx, python/src/HMatrixImplementation_doc.i.in, python/src/HMatrix_doc.i.in
Hi,
Please, review and pull if everything ok.
I need this to correctly use HMatrix for kriging applications.
=> Exposing addIdentity method from hmat

python/src/TrendTransform_doc.i.in
Minor fix in TrendTransform documentation
=> Minor fix in doc

ChangeLog, python/src/CalibrationResult_doc.i.in
=> Clarified the attributes of CalibrationResults to match the code

python/src/KrigingResult_doc.i.in
=> Update KrigingResult doc

ChangeLog, python/src/SobolSimulationAlgorithm_doc.i.in
This commit fixes the bug #1004.
It also updates the doc so that it matches the code after commit ec82f9b37b3a.
=> Fix sobol simu algo doc

ChangeLog, lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/CMakeLists.txt, lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelStepwiseAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/openturns/LinearModelStepwiseAlgorithm.hxx, lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/openturns/OTLinearModel.hxx, python/src/CMakeLists.txt, python/src/LinearModelStepwiseAlgorithm.i, python/src/LinearModelStepwiseAlgorithm_doc.i.in, python/src/metamodel_module.i, python/test/CMakeLists.txt, python/test/t_LinearModelAnalysis_std.py, python/test/t_LinearModelStepwiseAlgorithm_std.expout, python/test/t_LinearModelStepwiseAlgorithm_std.py
The objective is to introduce the linear `stepwise` algorithm
We integrate the `otlm` algorithm as it is.
This fixes #1209
=> Integration of Stepwise algorithm from otlm

lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosSobolIndices.cxx
Cosmetic changes after review of the code.
=> Added required const in FunctionalChaosSobolIndices

lib/src/Uncertainty/Distribution/MarshallOlkinCopula.cxx, lib/test/t_MarshallOlkinCopula_std.cxx, lib/test/t_MarshallOlkinCopula_std.expout, python/src/MarshallOlkinCopula_doc.i.in
Added the case alpha=beta=0.
Formatted the code as required in review.
=> Improved MarshallOlkinCopula

python/doc/examples/data_analysis/draw_survival.ipynb, python/doc/examples/data_analysis/kolmogorov_distribution.ipynb, python/doc/examples/data_analysis/kolmogorov_statistics.ipynb, python/doc/examples/meta_modeling/chaos_ishigami_grouped_indices.ipynb, python/doc/examples/meta_modeling/kriging_beam_trend.ipynb, python/doc/examples/meta_modeling/kriging_sequential.ipynb
The lists were not correctly formatted: added a blank new line when necessary.
=> Fixed formatting of itemized list in examples

ChangeLog, distro/debian/changelog, distro/rpm/openturns.spec, lib/src/Base/Func/MonomialFunctionFactory.cxx, lib/src/Base/Func/UniVariateFunctionFactory.cxx, lib/src/Base/Func/UniVariateFunctionFamily.cxx, lib/src/Base/Func/openturns/MonomialFunctionFactory.hxx, lib/src/Base/Func/openturns/ParametricPointToFieldFunction.hxx, lib/src/Base/Func/openturns/UniVariateFunctionFactory.hxx, lib/src/Base/Func/openturns/UniVariateFunctionFamily.hxx, lib/src/Base/Type/openturns/ComplexTensorImplementation.hxx, lib/test/t_ComplexTensor_std.cxx, lib/test/t_DistFunc_binomial.cxx, lib/test/t_DistFunc_hypergeometric.cxx, lib/test/t_KarhunenLoeveSVDAlgorithm_std.cxx, lib/test/t_PlackettCopulaFactory_std.cxx, lib/test/t_PlackettCopula_std.cxx, python/src/LinearModelStepwiseAlgorithm_doc.i.in
Hello @sofianehaddad @regislebrun, did I miss anything else to do besides #1307 for the release ?
If everything is good we can try to set the release for tomorrow.
j
=> Release 1.14

lib/src/Uncertainty/Distribution/MultinomialFactory.cxx, python/src/MultinomialFactory_doc.i.in
The sum parameter N was not corretly estimated.
=> Fixed MultinomialFactory

ChangeLog, lib/src/Base/Graph/Text.cxx
=> Fix Text drawable

lib/src/Base/Stat/HMatrixParameters.cxx, python/src/HMatrixParameters_doc.i.in
In hmat-oss, compression method 4 is AcaRandom.
Please merge to be able to use this feature.
=> enabling ACA random in HMatrix

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Stat/HMatrixImplementation.cxx, lib/src/Base/Stat/HMatrixParameters.cxx, python/src/HMatrixParameters_doc.i.in
=> HMat: Default to ACARandom compression method

ChangeLog, lib/src/Base/Stat/CovarianceModel.cxx
=> CovModel: Missing copyOnWrite in setFullParameter

ChangeLog, lib/src/Base/Algo/ApproximationAlgorithm.cxx, lib/src/Base/Algo/KarhunenLoeveAlgorithm.cxx, lib/src/Base/Algo/openturns/ApproximationAlgorithm.hxx, lib/src/Base/Algo/openturns/KarhunenLoeveAlgorithm.hxx, python/src/TypedInterfaceObject.i
=> Swig: Fix leak in TypedInterfaceObject typemap

CMakeLists.txt, lib/include/OTconfig.h.in, lib/src/Base/Common/TBB.cxx, lib/src/Base/Common/openturns/TBB.hxx, python/src/TBB.i, python/src/TBB_doc.i.in
This disables openblas threading when TBB is enabled.
I need confirmation that this fixes the openblas threading conflict.
=> TBB: Disable OpenBLAS threading

ChangeLog, lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Func/P1LagrangeInterpolation.cxx, lib/src/Base/Geom/Mesh.cxx, python/src/Mesh_doc.i.in, python/test/t_Mesh_std.py
=> Mesh: Fix numerical issue in checkPointInSimplex

python/doc/examples/numerical_methods/optimization_rastrigin.ipynb, python/doc/examples/numerical_methods/optimization_rosenbrock.ipynb
This fixes the formatting issue with these Sphinx itemized lists by inserting the required new lines.
=> Optimization examples: adding a newline for Sphinx formatting

python/doc/theory/data_analysis/kernel_smoothing.rst
Kernel smoothing: fixes the doc part of #1480
=> Update the theory doc of kernel smoothing

ChangeLog, lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelAnalysis.cxx, lib/src/Uncertainty/StatTests/VisualTest.cxx
=> In LinearAnalysis, drawQQPlot relies now on VisualTest::DrawQQplot

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingResult.hxx
Probaby a leftover from the kriging transformation
=> KrigingResult: Drop inputTransformedSample_

cmake/FindPythonModule.cmake
https://gitlab.kitware.com/cmake/cmake/-/issues/21505
=> CMake: Workaround cmake 3.19.1 FPHSA bug

COPYING.ev3, LICENSE, README.rst
Update information about the library available in root-level files.
=> Update README, LICENSE, COPYING.ev3

python/doc/pyplots/LHSExperiment.py
plot a 3-dimensional sample with LHS experiment
=> update figure for LHS experiment

ChangeLog, python/src/viewer.py
=> Minor bugfix

ChangeLog, python/doc/_templates/Distribution.rst_t, python/doc/examples/calibration/least_squares_and_gaussian_calibration/plot_calibration_flooding.py, python/doc/examples/data_analysis/distribution_fitting/plot_fit_extreme_value_distribution.py, python/doc/examples/data_analysis/distribution_fitting/plot_maximumlikelihood_estimator.py, python/doc/examples/data_analysis/manage_data_and_samples/plot_quick_start_point_and_sample.py, python/doc/examples/data_analysis/sample_analysis/plot_visualize_histogram.py, python/doc/examples/meta_modeling/fields_metamodels/plot_karhunenloeve_validation.py, python/doc/examples/reliability_sensitivity/reliability/plot_estimate_probability_form.py, python/src/Brent_doc.i.in, python/src/Normal_doc.i.in, python/src/StationaryFunctionalCovarianceModel_doc.i.in, python/src/Student_doc.i.in, python/src/UserDefined_doc.i.in
This PR contains several doc fixes by @aajenjo @A74579 @JPelamatti @MerlinKeller @ThibaultDelage @vchabri.
- Add example to the [Brent](https://openturns.github.io/openturns/1.16/user_manual/_generated/openturns.Brent.html) API doc page: close #1506.
- Add multivariate examples in the [normal](https://openturns.github.io/openturns/1.16/user_manual/_generated/openturns.Normal.html) and [Student](https://openturns.github.io/openturns/1.16/user_manual/_generated/openturns.Student.html) API doc: close #1497.
- Fix notations in the [maximum likelihood estimation](https://openturns.github.io/openturns/1.16/auto_data_analysis/distribution_fitting/plot_maximumlikelihood_estimator.html) example.
- Create a 1d [UserDefined](https://openturns.github.io/openturns/1.16/user_manual/_generated/openturns. …
=> EDF doc fix session

.circleci/config.yml, CMakeLists.txt
simpler implementation of #1783
=> CI: Store doc pages artifacts

python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_sobol_multivariate.py, python/src/JansenSensitivityAlgorithm_doc.i.in, python/src/MartinezSensitivityAlgorithm_doc.i.in, python/src/MauntzKucherenkoSensitivityAlgorithm_doc.i.in, python/src/SaltelliSensitivityAlgorithm_doc.i.in, python/src/SobolIndicesAlgorithmImplementation_doc.i.in
Fixed the messy aggregated Sobol' indices equations.
Created a new example for Sobol' indices with multiple outputs.
=> Fix aggregated Sobol' doc

ChangeLog, python/src/coupling_tools.py
=> coupling_tools: Drop deprecated arguments

python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_cantilever_beam_hmat.py
Following technical committee meeting.
=> Kriging cantilever beam HMAT: sensible epsilon

ChangeLog, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx, lib/test/t_KrigingAlgorithm_funcmodel.cxx, lib/test/t_KrigingAlgorithm_std.cxx, lib/test/t_KrigingAlgorithm_std_hmat.cxx, python/test/t_KrigingAlgorithm_funcmodel.py, python/test/t_KrigingAlgorithm_std.py, python/test/t_KrigingAlgorithm_std_hmat.py
=> Fixing KrigingResult with StationaryFunctionalCovarianceModel

ChangeLog, python/src/ExpectationSimulationAlgorithm_doc.i.in
=> ExpectationSimulationAlgorithm: Describes the principle and the stopping rule.

ChangeLog, lib/src/Uncertainty/Algorithm/OrthogonalBasis/OrthogonalUniVariatePolynomial.cxx, lib/src/Uncertainty/Algorithm/OrthogonalBasis/OrthogonalUniVariatePolynomialFactory.cxx, lib/src/Uncertainty/Algorithm/OrthogonalBasis/openturns/AdaptiveStieltjesAlgorithm.hxx, lib/src/Uncertainty/Algorithm/OrthogonalBasis/openturns/OrthogonalUniVariatePolynomial.hxx, lib/src/Uncertainty/Algorithm/OrthogonalBasis/openturns/OrthogonalUniVariatePolynomialFactory.hxx, lib/test/t_AdaptiveStieltjesAlgorithm_std.expout, lib/test/t_OrthogonalUniVariatePolynomial_std.cxx, lib/test/t_OrthogonalUniVariatePolynomial_std.expout, lib/test/t_OrthonormalizationAlgorithm_std.expout, lib/test/t_StandardDistributionPolynomialFactory_std.expout, python/src/OrthogonalUniVariatePolynomialFactory_doc.i.in, python/src/OrthogonalUniVariatePolynomial_doc.i.in, python/test/t_AdaptiveStieltjesAlgorithm_std.expout, python/test/t_OrthonormalizationAlgorithm_std.expout, python/test/t_StandardDistributionPolynomialFactory_std.expout
Now the internal representation of the collection of the recurrence coefficients is based on a collection of scalars instead of a collection of coefficients. It is more compact and more efficient. It closes issue #1958.
=> Improved OrthogonalUniVariatePolynomial

python/doc/examples/meta_modeling/fields_metamodels/plot_karhunenloeve_validation.py
Add points at the end of the sentences (cf #1935)
=> Fix some issues on documentation (formatting)

python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_ishigami_grouped_indices.py
=> Fix format in plot_chaos_ishigami_grouped_indices.py

python/doc/examples/meta_modeling/general_purpose_metamodels/plot_create_linear_least_squares_model.py
=> Fixes typo in plot_create_linear_least_square_model.py

python/doc/bibliography.rst, python/doc/theory/reliability_sensitivity/design_experiment.rst
=> Add missing reference in design_experiment.rst

python/doc/bibliography.rst, python/doc/examples/meta_modeling/general_purpose_metamodels/plot_stepwise.py
- Add Rawlings et al. (2001) to bibliography
=> Add Rawlings et al. (2001) to bibliography

python/doc/_static/js/mysearchtools.js
This PR modifies the scorer and the result display in the html part. This is based on Sphinx 4.4.
This customization of the searching engine is equivalent to a small fork (on Sphinx 4.4).
This hopefully solves #1944
=> Update mysearchtools.js file

lib/etc/openturns.conf.in, lib/src/Base/Common/ResourceMap.cxx, lib/src/Base/Stat/CovarianceModelImplementation.cxx, lib/src/Base/Stat/HMatrix.cxx, lib/src/Base/Stat/HMatrixImplementation.cxx, lib/src/Base/Stat/HMatrixParameters.cxx, lib/src/Base/Stat/openturns/HMatrix.hxx, lib/src/Base/Stat/openturns/HMatrixImplementation.hxx, lib/src/Base/Stat/openturns/HMatrixParameters.hxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx, lib/src/Uncertainty/Process/GaussianProcess.cxx, lib/test/t_HMatrix_LDLt.cxx, lib/test/t_HMatrix_LLt.cxx, lib/test/t_HMatrix_LU.cxx, lib/test/t_HMatrix_block_LLt.cxx, lib/test/t_HMatrix_block_LU.cxx, python/src/HMatrixImplementation_doc.i.in, python/src/HMatrixParameters_doc.i.in
This PR contains mainly a (major) bugfix : there is no exception in `hmat` and thus the `factorize` method never catch such ones even if it fails!
Also some others cosmetics, fixes and small changes are proposed in order to prepare the coming `hodlr` development.
=> Some improvements within HMat

lib/src/Uncertainty/Algorithm/WeightedExperiments/TensorProductExperiment.cxx, python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_hyperparameters_optimization.py, python/src/CMakeLists.txt, python/src/MarginalTransformationEvaluation_doc.i.in
This PR includes various updates.
- Indent CMakeLists.txt
- Removes mention and use of DistributionCollection in a script and a API help page.
- Simplifies the implementation of `TensorProductExperiment`after a suggestion from #1963
=> Fix code and doc

lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimator.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorConditionalSensitivity.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorGlobalSensitivity.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorImplementation.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorTargetSensitivity.cxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimator.hxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorConditionalSensitivity.hxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorGlobalSensitivity.hxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorImplementation.hxx, lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorTargetSensitivity.hxx, lib/test/t_HSICEstimatorConditionalSensitivity_std.cxx, lib/test/t_HSICEstimatorGlobalSensitivity_std.cxx, lib/test/t_HSICEstimatorTargetSensitivity_std.cxx, python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_hsic_estimators_ishigami.py, python/src/HSICEstimatorConditionalSensitivity_doc.i.in, python/src/HSICEstimatorGlobalSensitivity_doc.i.in, python/src/HSICEstimatorImplementation_doc.i.in, python/src/HSICEstimatorTargetSensitivity_doc.i.in, python/src/HSICEstimator_doc.i.in, python/test/t_HSICEstimatorConditionalSensitivity_std.py, python/test/t_HSICEstimatorGlobalSensitivity_std.py, python/test/t_HSICEstimatorTargetSensitivity_std.py
=> Rename covarianceList covarianceModelCollection in HSIC

ChangeLog, python/doc/theory/probabilistic_modeling/parametric_spectral_model.rst, python/doc/theory/probabilistic_modeling/stationary_covariance_model.rst, python/src/CauchyModel_doc.i.in
=> Fix CauchyModel documentation

python/doc/theory/reliability_sensitivity/sensitivity_hsic.rst
Minor modification on the HSIC theory documentation to ensure the consistency with the  covarianceModel API
=> minor correction to HSIC theory doc

lib/src/Uncertainty/Distribution/UserDefined.cxx, python/test/t_UserDefined_std.py
=> UserDefined: Fix computeCDF

lib/src/Base/Func/EnumerateFunctionImplementation.cxx, python/src/EnumerateFunctionImplementation_doc.i.in
Fixed comments and documentation of `EnumerateFunctionImplementation`. 
This PR contains an update initially in PR #2039.
=> Fixed doc of EnumerateFunctionImplementation

lib/src/Uncertainty/Process/ConditionedGaussianProcess.cxx
The management of vertices included into the conditioning set was partly wrong.
=> Fixed ConditionedGaussianProcess

python/doc/examples/calibration/least_squares_and_gaussian_calibration/plot_calibration_withoutobservedinputs.py
The goal of this PR is to create a new calibration example without observed inputs:
This PR fixes #2030.
~~The changelog should be updated before merging.~~
=> Calibration doc

lib/src/Uncertainty/Distribution/DistFunc.cxx, lib/src/Uncertainty/Distribution/TruncatedNormal.cxx, lib/src/Uncertainty/Distribution/openturns/DistFunc.hxx, lib/test/t_TruncatedNormal_std.cxx, lib/test/t_TruncatedNormal_std.expout, python/doc/user_manual/probabilistic_modelling.rst, python/src/DistFunc_doc.i.in, python/test/t_TruncatedNormal_std.expout, python/test/t_TruncatedNormal_std.py
Improved TruncatedNormal. Now it is possible to truncate a normal distribution on more extreme truncation intervals. It fixes #2058.
=> Improve truncated normal

python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_wingweight.py, python/doc/usecases/use_case_wingweight.rst
Changes of wingweight example to answer  @regislebrun remarks
=> Wingweight

python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_wingweight.py
Modification of example to have shaded surfaces instead of contours to ease the interpretation of the influence of the variables following past technical committee recomandations.
=> Update plot_sensitivity_wingweight.py - patch RC1

ChangeLog, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingResult.hxx, python/src/GeneralLinearModelResult_doc.i.in, python/src/KrigingResult_doc.i.in
No more collection of {Basis, Point}
No more transformation
=> Fixed Kriging docstrings 

python/doc/examples/meta_modeling/kriging_metamodel/plot_propagate_kriging_ishigami.py, python/doc/theory/probabilistic_modeling/copulas.rst, utils/docfast.py
=> Misc. doc fixes

lib/src/Uncertainty/Distribution/UserDefined.cxx
- Drop the generation of Point when not needed
- Refresh code: now a Sample has a unique dimension
- Improve computeCDF : break early if possible
=> Enhance UserDefined dist

ChangeLog, lib/src/Uncertainty/Distribution/Dirichlet.cxx, python/test/t_Dirichlet_std.py
=> Fixed Dirichlet::computeConditionalPDF

ChangeLog
We forgot to update the ChangeLog in #2259 so here is the missing text.
Poke @MerlinKeller
=> Update ChangeLog with MCMC changes from #2259 [1.21]

python/doc/examples/graphs/plot_graphs_basics.py
=> Minor corrections on graph example

python/doc/theory/reliability_sensitivity/sensitivity_sobol.rst, python/doc/theory/reliability_sensitivity/sensitivity_sobol_from_pce.rst, python/src/FunctionalChaosSobolIndices_doc.i.in
=> Fixed FunctionalChaosSobolIndices API help page.

lib/src/Base/Func/PiecewiseHermiteEvaluation.cxx, lib/src/Base/Func/PiecewiseLinearEvaluation.cxx
Now they can be built with only one value, resulting into constant functions.
=> Fixed PiecewiseLinearEvaluation and PiecewiseHermiteEvaluation

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx, lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingAlgorithm.hxx, python/src/KrigingAlgorithm_doc.i.in, python/test/t_KrigingAlgorithm_std.py
=> Kriging fix

lib/test/t_RandomWalkMetropolisHastings_std.cxx, python/src/RandomWalkMetropolisHastings_doc.i.in, python/test/t_RandomWalkMetropolisHastings_std.py
for the RandomWalkMetropolisHastings class.
EDIT: And add corresponding unit tests.
=> Correct get-setAdaptationRange doc

python/src/Multinomial_doc.i.in, python/src/NonCentralChiSquare_doc.i.in, python/src/P1LagrangeEvaluation_doc.i.in
It covers the Multinomial, NonCentralChiSquare and P1LagrangeEvaluation classes.
=> Added missing doc

python/src/CholeskyMethod_doc.i.in, python/src/DesignProxy_doc.i.in, python/src/KFold_doc.i.in, python/src/LARS_doc.i.in, python/src/LeastSquaresMethodImplementation_doc.i.in, python/src/LeastSquaresMethod_doc.i.in, python/src/QRMethod_doc.i.in, python/src/SVDMethod_doc.i.in, python/src/SparseMethod_doc.i.in
This PR creates new examples for the following PCE related classes:
- DesignProxy
- KFold
- LARS
- LeastSquaresMethod
- SparseMethod
=> Add missing examples

python/doc/examples/data_analysis/manage_data_and_samples/plot_randomize_sample_lines.py, python/doc/examples/graphs/plot_graphs_basics.py, python/doc/examples/numerical_methods/general_methods/plot_pce_design.py, python/doc/examples/reliability_sensitivity/central_dispersion/plot_expectation_simulation_algorithm.py, python/doc/examples/reliability_sensitivity/design_of_experiments/plot_smolyak_merge.py, python/doc/theory/data_analysis/aic.rst, python/doc/theory/meta_modeling/taylor_expansion.rst, python/doc/theory/reliability_sensitivity/taylor_importance_factors.rst, python/doc/theory/reliability_sensitivity/taylor_moments.rst, python/doc/usecases/use_case_ishigami.rst, python/doc/user_manual/probabilistic_modelling.rst, python/src/Function.i, python/src/FunctionImplementation_doc.i.in, python/src/FunctionalChaosAlgorithm_doc.i.in, python/src/KFoldSplitter_doc.i.in, python/src/KPermutationsDistribution_doc.i.in, python/src/KPermutations_doc.i.in, python/src/LeaveOneOutSplitter_doc.i.in, python/src/TaylorExpansionMoments_doc.i.in
This PR gathers various documentation updates
=> Documentation updates

python/src/MethodOfMomentsFactory_doc.i.in
I added the non linear system resolved by the method.
Closes #2419
=> Moments factory

python/src/usecases/fireSatellite_function.py
Hello,
This is a modification of the firesat test case due to an incompatibility between the documentation and the code.
Sincerely,
=> Firesat test case correction

lib/src/Base/Func/EvaluationImplementation.cxx
=> Evaluation 2D draw no longer sets colorbar position

python/src/DrawableImplementation_doc.i.in
Closes #2647
This should go in 1.23 if possible.
=> Document contour colormap norms

python/doc/bibliography.rst, python/doc/examples/data_analysis/manage_data_and_samples/plot_quantile_estimation_wilks.py, python/doc/math_notations.sty, python/doc/theory/data_analysis/quantile_estimation_wilks.rst, python/src/Wilks_doc.i.in
I modified: 
- the API of the class Wilks
- the example using Wilks
- the theory page
It resolves Issue #2707
=> Improved the Wilks documentation

python/doc/bibliography.rst, python/src/GaussLegendre_doc.i.in, python/src/GaussProductExperiment_doc.i.in, python/src/SmolyakExperiment_doc.i.in, python/test/t_GaussLegendre_std.py, python/test/t_GaussProductExperiment_std.py, python/test/t_SmolyakExperiment_std.py, python/test/t_TensorProductExperiment_std.py
Based on a suggestion by J.Peter (ONERA), here are unit tests of quadrature based on their polynomial degree of exactness.
- `GaussProductExperiment`
- `SmolyakExperiment`
- `TensorProductExperiment`
- `GaussLegendre`
Update documentation of polynomial degree of exactness of the same classes.
=> Check polynomial degree of exactness of quadrature

python/doc/examples/meta_modeling/kriging_metamodel/plot_gpr_1d.py
This `quick start` highlights on a 1d use-case the usage of the new `Gaussian Process Regression` classes
It should be integrated to the next release.
=> Add quick start illustrating the usage of GPR

lib/src/Uncertainty/StatTests/VisualTest.cxx, python/doc/pyplots/DrawInsideOutside.py, python/doc/user_manual/statistics_on_sample.rst, python/src/VisualTest_doc.i.in
Fixes an oversight on my part in PR #2759.
=> Reference VisualTest.DrawInsideOutside in doc

python/src/usecases/fireSatellite_function.py, python/src/usecases/wingweight_function.py
This PR closes #2826.
Desicriptions of inputs and outputs have been added to wingweight and Firesat models.
=> Add descriptions to wingweight and firesat models

lib/src/Base/Geom/Mesh.cxx, lib/src/Base/Geom/openturns/Mesh.hxx, python/src/Mesh_doc.i.in, python/test/t_BoundaryMesher_std.py
Now the user has access to the intrinsic dimension and the volumes are computed according to this intrinsic dimension (codimension 1 for now). Fixes #2876.
=> Improved Mesh

lib/src/Uncertainty/Algorithm/Optimization/EfficientGlobalOptimization.cxx, lib/src/Uncertainty/Algorithm/Optimization/openturns/EfficientGlobalOptimization.hxx, python/doc/examples/numerical_methods/optimization/plot_ego.py, python/doc/user_manual/numerical_methods.rst, python/src/CMakeLists.txt, python/src/EfficientGlobalOptimization_doc.i.in, python/src/experimental_module.i, python/src/uncertainty_module.i, python/test/t_EfficientGlobalOptimization_std.py
now EGO has to go to experimental because of GPRResult class
=> EGO: Compatibility with new GPR API

lib/src/Uncertainty/Algorithm/Sensitivity/RankSobolSensitivityAlgorithm.cxx, python/test/t_RankSobolSensitivityAlgorithm_std.py
=> RankSobolSensitivityAlgorithm::setDesign: added attributes reset
