lib/src/Base/Common/Catalog.cxx
lib/src/Base/Common/Catalog.hxx
lib/src/Base/Common/IdFactory.cxx
lib/src/Base/Common/IdFactory.hxx
lib/src/Base/Common/Log.cxx
lib/src/Base/Common/Log.hxx
lib/src/Base/Common/MutexLock.hxx
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Common/ResourceMap.hxx
lib/src/Base/Common/TBB.cxx
lib/src/Base/Common/TBB.hxx
lib/test/t_Catalog_std.cxx
lib/test/t_ResourceMap_std.cxx
python/src/ResourceMap.i
python/src/common_module.i
python/test/t_Catalog_std.py
python/test/t_ResourceMap_std.py

Singletons are challenging in C++, it is very hard to have a thread-safe implementation which takes into account dependencies between singletons.
Current code does not work as expected, we had issues on Windows when loading an Excel plug-in because ResourceMap was not initialized. Current code is difficult to read and debug, mostly because singleton builders (`*_init` structs defined along singletons) are initialized in header files and thus duplicated in each object file.
We propose here a simpler pattern: a `MutexLockSingleton` template class is declared in `MutexLock.hxx`, it is modelled after `ResourceMapInstance`. `Catalog`, `Log`, `ResourceMap` and `TBB` are rewritten to use it. 
A static builder is defined in implementation files, and a second one in `GetInstance()`.  There are no …

Rewrite singleton classes Catalog, Log, ResourceMap and TBB

---

lib/src/Base/Stat/CovarianceModelImplementation.hxx
python/src/CovarianceModelImplementation_doc.i.in
python/src/CovarianceModel_doc.i.in
python/src/ExponentialModel_doc.i.in

All methods of the implementation class should be declared as virtual. Indeed some of these methods might be redefined by derived classes

Minor update in CovarianceModelImplementation

---

python/src/NumericalPoint.i

Fixes swig warning 509 about NP/NS overloads for various methods after wrappers removal.
```
[0m/home/travis/build/openturns/openturns/lib/src/Base/Geom/Mesh.hxx:84: Warning 509: Overloaded method OT::Mesh::getNearestVertexIndex(OT::NumericalSample const &) const effectively ignored,
/home/travis/build/openturns/openturns/lib/src/Base/Geom/Mesh.hxx:78: Warning 509: as it is shadowed by OT::Mesh::getNearestVertexIndex(OT::NumericalPoint const &) const.
```
See discussion in https://github.com/openturns/openturns/pull/19
I chosed to increase the NP priority instead of NS remembering this: http://trac.openturns.org/changeset/2261
Also Field has this set to 3.

Increase NP typecheck priority

---

ChangeLog
lib/src/Uncertainty/Distribution/BetaFactory.cxx
lib/src/Uncertainty/Distribution/BinomialFactory.cxx
lib/src/Uncertainty/Distribution/GammaFactory.cxx
lib/src/Uncertainty/Distribution/PoissonFactory.cxx

When these factories are called with invalid values (either NaN or Inf),
getSample() loops forever.
Fix http://trac.openturns.org/ticket/796

Avoid infinite loops in several distribution factories

---

lib/src/Base/Common/OSS.hxx
lib/src/Base/Common/OStream.cxx
lib/src/Base/Common/OStream.hxx
python/test/t_coupling_tools.py

We update the library API to let the compilation on Debian & OS X systems using clang/libc++
Indeed, native compilation on OS X system uses the last ones as Mac OS X 10.9+ no longer uses GCC/libstdc++. In that case, dependencies such as muParser & tbb are naturally linked to libc++ (using packager like MacPort/Homebrew or ot-superbuild for example)
Following pull request will focus on a detail "How to install with OS X"

Native compilation on OS X

---

ChangeLog
python/src/ComplexMatrix.i
python/src/Matrix.i

http://legacy.python.org/dev/peps/pep-0465/

Support infix operator for matrix multiplication (PEP465)

---

ChangeLog
lib/src/Base/Stat/CovarianceModel.cxx
lib/src/Base/Stat/CovarianceModel.hxx
lib/src/Base/Stat/CovarianceModelImplementation.cxx
lib/src/Base/Stat/CovarianceModelImplementation.hxx
lib/src/Base/Stat/ProductCovarianceModel.cxx
lib/src/Base/Stat/ProductCovarianceModel.hxx
python/src/CovarianceModelImplementation_doc.i.in
python/src/CovarianceModel_doc.i.in

The PR completes  #50 
It renames CovarianceModel::setParameters into CovarianceModel::setParameter

Rename CovarianceModel::setParameters into CovarianceModel::setParameter

---

lib/src/Uncertainty/StatTests/FittingTest.cxx

In several situations, we would like to get at least one model when testing several parametric probabilistic models for given data, even if its p-value is zero (but the model can be estimated from the data).

Improved p-value initialization in FittingTest

---

lib/src/Base/Stat/WelchFactory.cxx

The WelchFactory class made the implicit assumption that the time grid associated to the given process sample was starting from 0, resulting in a wrong estimation if it was not the case. Now, it is fixed.

Extend WelchFactory to time grid with non-zero start

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Type/MatrixImplementation.cxx

Due to rounding errors, sometimes a symmetric matrix (obtained ie as L^tCL with C symmetric) is not exactly symmetric due to rounding errors. A more permissive check is needed in order to enforce the symmetry of the result in Python.

Improved the symmetry check in MatrixImplementation

---

lib/src/Base/Stat/TensorizedCovarianceModel.cxx

TenorizedCovarianceModel::getImplementation is bogus
The PR fixes method and raise exception if could not return the corresponding marginal coariance model.

Fixed TensorizedCovarianceModel::getMarginal

---

ChangeLog
TODO
lib/src/Uncertainty/Model/Distribution.cxx
lib/src/Uncertainty/Model/Distribution.hxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
lib/src/Uncertainty/Model/DistributionImplementation.hxx

It is violently removed by #53.

Restore Distribution::setParametersCollection(NP)

---

python/src/coupling_tools.py
python/test/t_Burr_std.py
python/test/t_ChiFactory_std.py
python/test/t_Chi_std.py
python/test/t_GeneralizedPareto_std.py
python/test/t_Rice_std.py
python/test/t_coupling_tools.py

Python 3.5 throws an exception on windows:
SyntaxError: encoding problem: iso-8859-15

Remove python tests encoding tags

---

lib/include/CMakeLists.txt

This allows to set CMAKE_Fortran_COMPILER through the mingw toolchain file
while not triggering fortran language specifics if not needed.

Rewrite the Fortran language check

---

lib/src/Uncertainty/Model/DistributionImplementation.cxx

When the range of drawDiscreteCDF is disjoint from the support
the size variable is zero and leads to a segfault:
import numpy as np
mysample1 = np.arange(0,10,0.1)
mysample = np.split(mysample1,len(mysample1))
myCDF = ot.VisualTest_DrawEmpiricalCDF(mysample,10,100)

Fix empty range segfault in drawDiscreteCDF

---

lib/src/Base/Stat/FieldImplementation.cxx

Now, for fields with spatial dimension 1 and with dimension 2, the default draw() method plots the second output as a function of the first output.

Improved the draw() method of Field

---

lib/src/Uncertainty/Distribution/ClaytonCopula.cxx
lib/src/Uncertainty/Model/ContinuousDistribution.cxx
lib/test/t_ClaytonCopula_std.cxx
lib/test/t_ClaytonCopula_std.expout
python/test/t_ClaytonCopula_std.expout
python/test/t_ClaytonCopula_std.py

This copula has a CDF/PDF and a random generator badly conditioned for large values of theta (the limit of this copula is the Min copula, which is singular), leading to overflows when implemented naively, and suffers from cancellation for theta close to zero (the limit being the independent copula). The previous implementation was not robust enough to handle these cases with full accuracy.

Improved the numerical stability and accuracy of ClaytonCopula

---

lib/src/Base/Stat/ProductCovarianceModel.cxx

Use of new convention to set the description which is of size spatialDimension + 1

Fix ProductCovarianceModel::getParameterDescription

---

ChangeLog
lib/src/Base/Graph/Contour.cxx

Fixes the default BayesDistribution pdf graph with uniform
distributions with matplotlib.
Matplotlib 1.5.1 now turns this into an error:
https://github.com/matplotlib/matplotlib/pull/5485

Fix duplicate contour levels

---

ChangeLog
lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Uncertainty/StatTests/LinearModelTest.cxx
lib/src/Uncertainty/StatTests/openturns/LinearModelTest.hxx
python/doc/user_manual/statistics_on_sample.rst
python/src/LinearModelTest_doc.i.in

For the ByPass project, I implemented 3 linear model test to check the homoskedasticity of the residuals (Breusch-Pagan and Harrison-McCabe) and to check the autocorrelation (Durbin-Watson).
All codes are adapted from the R code found in the package "lmtest": _bptest_, _hmctest_ and _dwtest_. The docstrings for all tests are also written.

New linear model test

---

lib/src/Base/Stat/NumericalSampleImplementation.cxx

Otherwise TBB overhead may impact performance.
I wrote a benchmark to compare timings for current implementation based on TBB, and a naive one:
```
size=       1 dim=       1 size*dim=        1:    meanTBB=2.704e-05 (*)meanSeq=1.488e-06 (*)varTBB=3.200e-07    varSeq=3.320e-07
size=       1 dim=      10 size*dim=       10:    meanTBB=4.076e-06 (*)meanSeq=4.780e-07    varTBB=1.900e-07 (*)varSeq=1.580e-07
size=       1 dim=     100 size*dim=      100:    meanTBB=4.253e-06 (*)meanSeq=1.118e-06 (*)varTBB=1.570e-07    varSeq=1.890e-07
size=       1 dim=    1000 size*dim=     1000:    meanTBB=1.021e-05 (*)meanSeq=7.029e-06    varTBB=2.510e-07 (*)varSeq=1.610e-07
size=       1 dim=   10000 size*dim=    10000:    meanTBB=1.137e-04 (*)meanSeq=9.377e-05    varTBB=4.080e-07 (*)varSeq=1.380e-07
size= …
```

Use NSI_const_iterator in ReductionFunctor 

---

lib/src/Base/Func/openturns/NumericalMathFunctionImplementation.hxx

It allows to define locally specializations of NumericalMathFunction without sticking on the pattern EvaluationImplementation/GradientImplementation/HessianImplementation, typically to avoid the use of the bindMethod trick which is SLOW.

Made more methods virtual in NumericalMathFunctionImplementation

---

ChangeLog
lib/src/Base/Common/ResourceMap.cxx
python/src/PythonDistributionImplementation.cxx

Python memory management is not thread-safe and parallelization
cannot be used to wrap the callbacks.

Pythondistribution parallel

---

lib/src/Base/Func/NumericalMathEvaluationImplementation.cxx

to use the virtual getParameter method if redefined in inherited classes

Fix NMEvaluation::::getParameterDimension

---

lib/src/Uncertainty/Distribution/CumulativeDistributionNetwork.cxx

..is now properly set avoiding random crashes when generating the sphinx
doc.
The documentation graph example contained a Dirichlet which does not support
parallel sections which made computeCDFParallel crash using TBB.

CumulativeDistributionNetwork parallel flag

---

python/src/CMakeLists.txt

Swig adds several -I flags to c++ command line option, in particular
-I/usr/include on Debian.  If OpenTURNS had already been installed
into /usr/include, headers are then taken from /usr/include/openturns
and not from source directory.
Pass BEFORE option to CMake include_directories() command to ensure
that correct header files are being used.

Fix compilation of Python bindings

---

lib/src/Base/Stat/NumericalSample.cxx
lib/src/Base/Stat/NumericalSampleImplementation.cxx
lib/src/Base/Stat/openturns/NumericalSample.hxx
lib/src/Base/Stat/openturns/NumericalSampleImplementation.hxx
lib/test/t_NumericalSample_std.cxx
lib/test/t_NumericalSample_std.expout
python/src/NumericalSample_doc.i.in
python/test/t_NumericalSample_std.expout
python/test/t_NumericalSample_std.py

Modify partial copy constructor of NumericalSampleImplementation to also work on const objects.
Fix typos in NumericalSample comments and docstrings.

Allow partial copy constructor of NumericalSample

---

lib/src/Uncertainty/Algorithm/WeightedExperiments/GaussProductExperiment.cxx
lib/src/Uncertainty/Algorithm/WeightedExperiments/openturns/GaussProductExperiment.hxx

The bug is due to the incremental way an attribute is built during the construction of the object, which is reused when the distribution underlying this weighted experiment is changed. The reset of the attribute was missing.

Fixed a bug in GaussProductExperiment introduced in PR#222

---

ChangeLog
lib/src/Uncertainty/Distribution/TruncatedDistribution.cxx
lib/test/t_TruncatedDistribution_std.cxx
lib/test/t_TruncatedDistribution_std.expout

The TruncatedDistribution::setParameter method currently crashes due to a bad allocation (cf  http://trac.openturns.org/ticket/837)
This PR fixes this issue.

Fix TruncatedDistribution::setParameter

---

lib/src/Base/Stat/openturns/HMatrixImplementation.hxx

CovarianceModelImplementation::discretizeHMatrix contains this snippet:
```
if (dimension_ == 1)
{
CovarianceAssemblyFunction simple(*this, vertices, nuggetFactor);
covarianceHMatrix.assemble(simple, 'L');
}
```
In fact, `*this` is converted into a local `CovarianceModel` variable,
and `CovarianceAssemblyFunction::covarianceModel_` is a reference to
this local variable.  When exiting from `CovarianceAssemblyFunction`
constructor, this local variable is destroyed, but `covarianceModel_`
is still referencing it and `covarianceHMatrix.assemble()` crashes.
Also remove reference for vertices too, in order to be safe.

Fix a segfault in CovarianceModelImplementation::discretizeHMatrix

---

lib/src/Base/Geom/LevelSet.cxx
lib/src/Base/Geom/openturns/LevelSet.hxx
lib/src/Uncertainty/Process/KarhunenLoeveQuadratureFactory.cxx
python/src/LevelSet_doc.i.in

Improved LevelSet:
Now the user can specify a bounding box by using the setLowerBound()/setUpperBound() methods. The level set is cliped by this bounding box, ie the contains() method will return false as soon as the given point is outside of the user-defined bounding box.
Improved KarhunenLoeveQuadratureFactory:
Now it fully support multidimensional covariance models. It is also more verbose.

Level set bounds

---

lib/src/Uncertainty/Distribution/BernsteinCopulaFactory.cxx
lib/src/Uncertainty/Distribution/Mixture.cxx
lib/src/Uncertainty/Distribution/openturns/Mixture.hxx
lib/src/Uncertainty/Model/CopulaImplementation.cxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
lib/src/Uncertainty/Model/openturns/CopulaImplementation.hxx
lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx

The BernsteinCopulaFactory class produces a Mixture which is a copula but it cannot be deduced from the individual properties of the atoms in the mixture.

Fixed BernsteinCopulaFactory

---

AUTHORS
ChangeLog
python/src/NumericalMathFunction.i
python/test/t_NumericalMathFunction_python.expout
python/test/t_NumericalMathFunction_python.py

This pull request adds the optional argument `n_cpus` to PythonFunction. If it is set, it distributes `func` with multiprocessing on the number of cpus specified by `n_cpus`. If `n_cpus=-1`, it uses all the cores of the machine. if `n_cpus=1`, it does nothing. If `n_cpus` and `func_sample` are both given as arguments, `n_cpus` will be ignored and samples will be handled by `func_sample`.
This function is limited to distributing `func` calls on the machine you are working on. More advanced distribution techniques will be develloped for [otwrapy.Parallelizer](http://felipeam86.github.io/otwrapy/_generated/otwrapy.Parallelizer.html#otwrapy.Parallelizer)

Make ot.PythonFunction (optionally) distributed with multiprocessing

---

.travis.yml

nlopt does not support autotools anymore since the integration of https://github.com/stevengj/nlopt/pull/49

[travis] Use CMake instead of autotools

---

lib/src/Base/Optim/Cobyla/Cobyla.cxx
lib/src/Base/Optim/Cobyla/algocobyla.c
lib/src/Base/Optim/Cobyla/algocobyla.h
lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation/BoxCoxFactory.cxx
lib/src/Uncertainty/Process/ARMALikelihoodFactory.cxx
lib/src/Uncertainty/Process/WhittleFactory.cxx

Another cobyla function is provided by NLopt.
On Windows with MSVC, linking fails with this error:
```
nlopt.lib(cobyla.obj) : error LNK2005: cobyla already defined in algocobyla.obj
```
Since this function is needed only by Cobyla.cxx, we can embed it into Cobyla.cxx with few adjustements so that algocobyla.c compiles with a C++ compiler.
An alternative would be to rename cobyla into ot_cobyla, I can do that if requested.

Make C cobyla function private

---

lib/src/Base/Optim/AbdoRackwitz/AbdoRackwitz.cxx
lib/src/Base/Optim/Cobyla/Cobyla.cxx
lib/src/Base/Optim/Cobyla/openturns/Cobyla.hxx
lib/src/Base/Optim/NLopt.cxx
lib/src/Base/Optim/OptimizationResult.cxx
lib/src/Base/Optim/OptimizationSolverImplementation.cxx
lib/src/Base/Optim/SQP/SQP.cxx
lib/src/Base/Optim/TNC/TNC.cxx
lib/src/Base/Optim/openturns/NLopt.hxx
lib/src/Base/Optim/openturns/OptimizationResult.hxx
lib/src/Base/Optim/openturns/OptimizationSolverImplementation.hxx
python/src/OptimizationResult_doc.i.in

We propose to simplify a bit the API and store the history from start, which was missing for NLopt, which allowed to spare an extra evaluation of the starting point for TNC & Cobyla.
The Cobyla constraint error was not correctly computed for non-violated constraints which prevented to check for feasible points.
Also there's no need to treat nearest-point problems separately in NLopt.

Optimization enhancements

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx

otherwise the confidence interval length is null

Set Sobol positve default boostrap size

---

lib/src/Base/Type/HermitianMatrix.cxx
lib/src/Base/Type/SymmetricMatrix.cxx
lib/src/Base/Type/openturns/HermitianMatrix.hxx
lib/src/Base/Type/openturns/SymmetricMatrix.hxx

In order to fix Trac ticket 822 (PR#187), four constructors had been added:
ComplexMatrix(const HermitianMatrix & hermitian);
Matrix(const SymmetricMatrix & symmetric);
SquareComplexMatrix(const HermitianMatrix & hermitian);
SquareMatrix(const SymmetricMatrix & symmetric);
But they introduce some glitches.  Consider this C++ file:
========================= test.cxx =================================
#include <iostream>
inline void print_msg(const char* msg) { std::cout << msg << std::endl; }
class Derived;
class Base {
public:
Base() { print_msg("Base()"); }
Base(const Derived & a) { print_msg("Base(const Derived &)"); }
Base(const Base & a) { print_msg("Base(const Base &)"); }
};
class Derived: public Base {
public:
Derived() { print_msg("Derived()"); }
};
int main(void)
{
std::cout << …

Add copy constructor for {Symmetric,Hermitian}Matrix

---

lib/src/Uncertainty/Algorithm/Simulation/SubsetSampling.cxx

A condition used is p*N>1, unfortunately N was defined as
N=maximumoutersampling instead of maximumoutersampling * blocksize.

Include block size criteria in Subset condition

---

lib/include/OTconfig.h.in
lib/include/installed-OTconfig.h.in
lib/src/Base/Common/Os.cxx
lib/src/Base/Common/Path.cxx

In Os/Path, unistd.h, sys/types.h and sys/stat.h are systematically included (for rmdir, unlink, stat)
We should first check that OPENTURNS_HAVE_XXX variables are defined to include these last ones.

Conditional include of headers

---

lib/src/Base/Common/Os.cxx
lib/src/Base/Common/Path.cxx
lib/src/Base/Common/openturns/Os.hxx

In particular use IsFile in Path::FindFileByNameInDirectoryList
instead of just 'stat' to check for a regular file.
This allows to work around what seems a bug compiling on conda/osx
with libcpp where this function returns a directory.

Add Os::IsDirectory, IsFile

---

python/src/HMatrix.i

Without this change, swig is confused:
```
>>> cov.compressionRatio()
<Swig Object of type 'std::pair< size_t,size_t > *' at 0x11bb13180>
```
With this change:
```
>>> cov.compressionRatio()
(36L, 36L)
```

Fix Python bindings for HMatrix::compressionRatio

---

ChangeLog
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Common/TBB.cxx
lib/src/Base/Common/openturns/TBB.hxx
python/doc/user_manual/configuration.rst
python/src/CMakeLists.txt
python/src/TBB.i
python/src/TBB_doc.i.in
python/src/common_module.i

Added TBB::SetNumberOfThreads which is called in ResourceMap::SetAsUnsignedInteger.
This can be used to get a deterministic behavior of KrigingAlgorithm with normalization enabled.

Allow to change TBB threads number at runtime

---

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx

When basis_ was of size 0, the matrix F was not correctly initialized.

Fixed GeneralizedLinearModelAlgorithm::computeF()

---

ChangeLog
lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Uncertainty/Distribution/FisherSnedecor.cxx
lib/src/Uncertainty/Distribution/MaximumLikelihoodFactory.cxx
lib/src/Uncertainty/Distribution/Trapezoidal.cxx
lib/src/Uncertainty/Distribution/TruncatedNormal.cxx
lib/src/Uncertainty/Distribution/openturns/FisherSnedecor.hxx
lib/src/Uncertainty/Distribution/openturns/Trapezoidal.hxx
lib/src/Uncertainty/Distribution/openturns/TruncatedNormal.hxx
lib/src/Uncertainty/Model/Distribution.cxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
lib/src/Uncertainty/Model/openturns/Distribution.hxx
lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx
lib/test/t_FisherSnedecor_std.cxx
lib/test/t_FisherSnedecor_std.expout
lib/test/t_TrapezoidalFactory_std.cxx
lib/test/t_Trapezoidal_std.cxx
lib/test/t_Trapezoidal_std.expout
lib/test/t_TruncatedNormal_std.cxx
lib/test/t_TruncatedNormal_std.expout
python/src/DistributionImplementation_doc.i.in
python/src/Distribution_doc.i.in
python/test/t_FisherSnedecor_std.expout
python/test/t_FisherSnedecor_std.py
python/test/t_TrapezoidalFactory_std.py
python/test/t_Trapezoidal_std.expout
python/test/t_Trapezoidal_std.py
python/test/t_TruncatedNormal_std.expout
python/test/t_TruncatedNormal_std.py

This PR implements a generic Distribution::computeLogPDFGradient (defined as PDFGradient/PDF), which purpose is to help for estimating distributions (see #349)
Indeed, when estimating distribution's parameters thanks to the MaximumLikelihoodFactory class, the function to maximize (the log-likelihood) was
previously defined as bind method function (+ difference finite gradient). We rework the internal structure "MaximumLikelihoodFactoryLogLikelihood" as follows:
- It inherits now from NumericalMathEvaluationImplementation;
- It implements the operator() (reuse the previous computeLogLikelihood method)
- A gradient wrapper is added (maps Distribution::computeLogPDFGradient)
Thus we get the function and is exact gradient for the evaluation.
Note that here the separation between …

MaximumLikelihoodFactory enhancements

---

ChangeLog
lib/src/Base/Optim/OptimizationProblem.cxx
lib/src/Base/Optim/OptimizationProblemImplementation.cxx
lib/src/Base/Optim/openturns/OptimizationProblem.hxx
lib/src/Base/Optim/openturns/OptimizationProblemImplementation.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralizedLinearModelAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralizedLinearModelAlgorithm.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingAlgorithm.hxx
lib/src/Uncertainty/Distribution/FisherSnedecorFactory.cxx
lib/src/Uncertainty/Distribution/MaximumLikelihoodFactory.cxx
lib/src/Uncertainty/Distribution/MeixnerDistribution.cxx
lib/src/Uncertainty/Distribution/OrderStatisticsMarginalChecker.cxx
lib/src/Uncertainty/Distribution/TrapezoidalFactory.cxx
lib/src/Uncertainty/Distribution/TruncatedNormalFactory.cxx
lib/src/Uncertainty/Distribution/openturns/MaximumLikelihoodFactory.hxx
lib/test/t_MultiStart_std.cxx
lib/test/t_Study_saveload.cxx
lib/test/t_TNC_std.cxx
python/src/GeneralizedLinearModelAlgorithm_doc.i.in
python/src/KrigingAlgorithm_doc.i.in
python/src/MaximumLikelihoodFactory_doc.i.in
python/src/MultiStart_doc.i.in
python/src/OptimizationProblemImplementation_doc.i.in
python/src/OptimizationSolverImplementation_doc.i.in
python/test/t_MultiStart_std.py
python/test/t_TNC_std.py

Bounds and constraints have always the dimension of the objective.
They are cleared when the objective is set with a different input dimension.
So, we cannot use an OptimizationProblem to pass a partial problem to (eg GLM), so add accessors to set bounds etc.
Fixes http://trac.openturns.org/ticket/875

Keep OptimizationProblem valid

---

.travis.yml

Purpose is to compile both on linux and osx platforms. 
Some differencies in osx are to be noticed compared to linux:
* sphinx (install/compilation) is disabled on osx
* cmake options for compilation of hmat/ot differ
* For osx, we enforce native python
* We use COTIRE for osx compilation to speed the compilation

Travis script to compile both on linux/osx platforms

---

python/doc/sphinxext/execforresourcemap_directive.py
python/src/__init__.py
python/src/viewer.py
python/test/t_Viewer.py

- A fix for svg file bytes conversion to unicode string for html when rendering a graph inside notebook
- View.show to show only current graph, not all queued plots (not available in matplotlib < 1.3.1)
side effect: the block keyword is removed -> use pyplot api for blocking show all in non-interactive mode

Viewer fixes

---

ChangeLog
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingAlgorithm.hxx
lib/src/Uncertainty/Distribution/RiceFactory.cxx
lib/test/t_BasisFactory_std.cxx
lib/test/t_ConditionedNormalProcess_std.cxx
lib/test/t_KrigingAlgorithm_std.cxx
lib/test/t_KrigingAlgorithm_std_hmat.cxx
lib/test/t_KrigingRandomVector_std.cxx
lib/test/t_MetaModelValidation_std.cxx
python/src/ConditionedNormalProcess_doc.i.in
python/src/KrigingAlgorithm_doc.i.in
python/src/KrigingRandomVector_doc.i.in
python/src/KrigingResult_doc.i.in
python/test/t_ConditionedNormalProcess_std.py
python/test/t_KrigingAlgorithm_std.py
python/test/t_KrigingAlgorithm_std_hmat.py
python/test/t_KrigingRandomVector_std.py
python/test/t_MetaModelValidation_std.py

Now KrigingAlgorithm constructors are coherant comparing to the GeneralizedLinearModel ones (data, covModel, basis). It is more coherant since the basis/basisCollection is an 'optionnal' argument
We remove also the useless keepCholesky argument in ctors

More coherant KrigingAlgorithm constructors 

---

.travis.yml

The PR fixes the recent `OS X` failures on the travis-ci platform
Problem is due to the used `tbb` imported thanks to Homebrew. For now, `tbb` sources are compiled

Fix osx failure on travis

---

lib/src/Base/Optim/AbdoRackwitz.cxx
lib/src/Base/Optim/NLopt.cxx
lib/src/Base/Optim/OptimizationAlgorithm.cxx
lib/src/Base/Optim/OptimizationAlgorithmImplementation.cxx
lib/src/Base/Optim/SQP.cxx
lib/src/Base/Optim/TNC.cxx
lib/src/Base/Optim/openturns/NLopt.hxx
lib/src/Base/Optim/openturns/OptimizationAlgorithm.hxx
lib/src/Base/Optim/openturns/OptimizationAlgorithmImplementation.hxx
lib/src/Base/Optim/openturns/TNC.hxx
lib/src/Uncertainty/Algorithm/Simulation/Simulation.cxx
python/src/Cobyla_doc.i.in
python/src/NLopt_doc.i.in
python/src/OptimizationAlgorithm.i
python/src/OptimizationAlgorithmImplementation.i
python/src/OptimizationAlgorithmImplementation_doc.i.in
python/src/OptimizationAlgorithm_doc.i.in
python/src/OptimizationProblemImplementation_doc.i.in
python/src/TNC_doc.i.in

A possible use-case is to control FORM optimization by the number of calls (http://trac.openturns.org/ticket/351)
This is not implemented by all solvers, the behavior of each solver is documented if it doesnt implement one of the callbacks.

Add optimization callbacks

---

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx

When the key "GeneralLinearModelAlgorithm-LinearAlgebra" was set to "HMAT" and the key "KrigingAlgorithm-LinearAlgebra" to "LAPACK" in ResourceMap, then the Cholesky factor produced by GeneralLinearModelAlgorithm was an HMAT one while KrigingAlgorithm was expecting a LAPACK one, resulting into an error.

Fixed GLM method initialization in KrigingAlgorithm.

---

python/src/LinearFunction.i
python/src/QuadraticFunction.i

These are deprecated, and that also fixes the documentation as it shadows the dostrings of LinearFunction, QuadraticFunction

Fix (Linear|Quadratic)NumericalMathFunction aliases

---

CMakeLists.txt
python/test/CMakeLists.txt

nbsphinx is not necessary to enable notebook tests, only nbconvert, mpl...

Allow notebook testing without nbsphinx

---

CMakeLists.txt
lib/src/Base/Stat/HMatrixImplementation.cxx
python/doc/developer_guide/architecture.rst

This progress bar had been added in latest hmat-oss (> 1.5.0).
We can replace calls to factorize by factorize_generic (added in hmat-oss 1.2.0)
to disable this progress bar.

Disable hmat-oss progress bar during factorization

---

lib/src/Uncertainty/Process/ARMAFactoryImplementation.cxx
lib/src/Uncertainty/Process/WhittleFactory.cxx
lib/src/Uncertainty/Process/openturns/ARMAFactoryImplementation.hxx
lib/src/Uncertainty/Process/openturns/WhittleFactory.hxx
lib/test/t_WhittleFactory_std.cxx
python/doc/examples/statistical_estimation/estimate_arma.ipynb
python/src/ARMAFactoryImplementation_doc.i.in
python/src/ARMAFactory_doc.i.in
python/src/WhittleFactory.i
python/src/WhittleFactory_doc.i.in
python/test/t_WhittleFactory_std.py

- Allows to disambiguate whether to return information criteria
- Return it in a tuple instead of by reference
- Removed useless ARMAFactoryImplementation::build with reference

Add WhittleFactory::buildWithCriteria

---

ChangeLog
lib/src/Uncertainty/Distribution/RandomMixture.cxx

This fix http://trac.openturns.org/ticket/887 : the kernel convolution should be performed only if all atoms are continuous.
Fix also a small bug in RandomMixture::isIntegral

Fix RandomMixture::computePDF with 2 atoms

---

lib/src/Uncertainty/Algorithm/MetaModel/TensorApproximation/TensorApproximationResult.cxx

The getMarginal() method failed when called on a TensorApproximationResult meta-model due to a missing implementation of the Hessian

Fixed TensorApproximationResult

---

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingAlgorithm.cxx

The glmAlgo_ attribute was built two times: one using the default constructor and one using the parameter constructor, involving a useless overhead and making the debug tricky

Improved initialization in KrigingAlgorithm constructors

---

.travis.yml

as git version requires to use newer setuptools on the contrary to the wheels package

Install sphinx stable on precise

---

.travis.yml

This should speed up the linux build that timeouts nowadays by not uselessly compiling dependencies.

Use Trusty container in Travis

---

lib/src/Base/Common/Path.cxx

Conda performs prefix substitution within libraries so that packages
are relocatable.  On OSX, line
directory = String(SYSCONFIG_PATH) + PrefixConfigSubdirectory_;
causes trouble.  When compiling, conda makes SYSCONFIG_PATH a very long
string, and it is replaced during installation.
On Linux, it works as expected, string contains the new path, and /openturns
is appended to it afterwards.
On OSX, string also contains the new path, but it keeps its original length,
and thus /openturns is appended after lots of \0.
With
directory = String() + String(SYSCONFIG_PATH).c_str() + PrefixConfigSubdirectory_;
SYSCONFIG_PATH is adjusted to have the new length.

Fix loading configuration file on OSX when installing with conda

---

lib/src/Base/Stat/Sample.cxx
lib/src/Base/Stat/openturns/SampleImplementation.hxx

Call it from Sample::operator()(i,j) to avoid creation of
NSI_point or NSI_const_point objects.

New method SampleImplementation::operator()(i,j)

---

lib/src/Base/Stat/SampleImplementation.cxx
lib/src/Base/Stat/csv_lexer.ll

With this PR:
- the import of CSV files using the flex/yacc parser is much more efficient thanks to the use of atof (and thanks to @dbarbier )
- the export to CSV files is more efficient 
- the streaming to R format and the export to temporary file are also slightly improved
On a 6x10000000 (ie 800Mo) file, with OT 1.9 I get:
> Text import
t= 56.2426171303 s, speed= 1.06680668613 Mvalues/s
CSV import via Text
t= 77.4492180347 s, speed= 0.774701172232 Mvalues/s
CSV import
t= 72.4423568249 s, speed= 0.828244726287 Mvalues/s
CSV export
t= 45.195127964 s, speed= 1.3275767257 Mvalues/s
Stream to R format
t= 44.9941790104 s, speed= 1.33350582941 Mvalues/s
Store to temporary file
t= 41.1363098621 s, speed= 1.45856544258 Mvalues/s
Pandas import CSV
t= 10.5111160278 s, speed= 5.70824257302 …

Improve Sample I/O

---

python/src/Sample.i

Currently print(ot.Sample) generates an HTML table of the full sample in a notebook environment, which is incoherant regarding the str method.
Furthermore, the full representation makes sometimes the kernel crash if sample is 'huge' 
This PR fixes the issue by setting an html repr similar to the standard str one

Perform sample html repr

---

ChangeLog
lib/src/Base/Algo/PenalizedLeastSquaresAlgorithm.cxx
lib/src/Base/Stat/CovarianceMatrix.cxx
lib/src/Base/Stat/openturns/CovarianceMatrix.hxx
lib/src/Base/Type/IdentityMatrix.cxx
lib/src/Base/Type/MatrixImplementation.cxx
lib/src/Base/Type/openturns/IdentityMatrix.hxx
lib/src/Base/Type/openturns/MatrixImplementation.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx
lib/src/Uncertainty/Distribution/Normal.cxx
lib/src/Uncertainty/Model/EllipticalDistribution.cxx
python/src/CovarianceMatrix_doc.i.in

Drop its argument.
No code actually calls this method with keepIntact=false, and this is
normal since it does not make sense to overwrite the matrix.

Make MatrixImplementation::isPositiveDefinite const

---

ChangeLog
lib/src/Base/Stat/ProcessSample.cxx
python/src/Field.i

This method is called from `ProcessSample::__getitem__`.
OTexception.i transforms OutOfBoundException into IndexError,
which is needed by Python to end its for loops.
Fix http://trac.openturns.org/ticket/896
For consistency reason, the same change is applied to setField and operator[].
In `Field::__getitem__`, call `at()` method instead of `getValueAtIndex()`;
the former checks its argument and will thus generate an IndexError.
Copy `FieldImplementation::__setitem__` into Field class, there is no reason
to have different implementations.

Let ProcessSample::getField() method throw OutOfBoundException

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Stat/SampleImplementation.cxx
lib/src/Base/Stat/openturns/SampleImplementation.hxx
python/src/Sample_doc.i.in
python/test/t_Sample_csv.expout
python/test/t_Sample_csv.py

PR #508 broke otpmml which relied on ImportFromTextFile to ignore comments.
Now lines starting with one of the chars contained in Sample-CommentMarkers setting are ignored.
This means the initial check for dimension has to look for the first data or description line.
This makes ImportFromTextFile closer to the behavior of numpy.loadtxt.
Also there was a small bug in ParseStringAsValues not eating blank spaces when the separator is ' '.

Handle comments in BuildFromTextFile

---

.travis.yml

The objective here is to reenable c ++ tests on travis since sphinx documentation is disabled.
We speed up also some builds & disable useless install (sphinx, numpydoc, matplotlib, texlive)

Reenable cxx tests in travis

---

python/src/Field.i
python/src/FieldImplementation.i
python/src/ProcessSample.i
python/src/Sample.i

This PR performs some {set,get}item methods : index in python should be in [-size, size-1].
The current implementation throws an OutOfBoundException in case index not in the previous interval. However there is a confusion between SignedInteger/UnsignedInteger and thus leads to a *strange* message error, which is fixed here.

Minor swig improvement

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Func/GradientImplementation.cxx
lib/src/Base/Func/HaarWavelet.cxx
lib/src/Base/Func/HessianImplementation.cxx
lib/src/Base/Func/SymbolicEvaluation.cxx
lib/src/Base/Func/SymbolicGradient.cxx
lib/src/Base/Func/SymbolicHessian.cxx
lib/src/Base/Func/openturns/HaarWavelet.hxx
lib/src/Base/Func/openturns/SymbolicEvaluation.hxx
lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/MarginalTransformationEvaluation.cxx
lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/openturns/MarginalTransformationEvaluation.hxx

We should not use '*this = ...' in ::load to loose attributes from parent class

Avoid using *this= in ::load

---

python/src/Function.i

On some platforms, Python multiprocessing module is not working.  In this case, gracefully fallback to sequential execution.

Fix Function._exec_sample for exotic platforms

---

lib/src/Uncertainty/Algorithm/Simulation/ProbabilitySimulationAlgorithm.cxx
lib/src/Uncertainty/Algorithm/Simulation/Simulation.cxx
lib/src/Uncertainty/Algorithm/Simulation/openturns/ProbabilitySimulationAlgorithm.hxx
python/src/ProbabilitySimulationAlgorithm_doc.i.in
python/test/t_ProbabilitySimulationAlgorithm_std.py

ProbabilitySimulation was able to handle only composite events (Y=f(X)) now added a ctor without experiment that handles general events. Also reverts the Simulation change to make it abstract.

ProbabilitySimulation to handle general events

---

ChangeLog
lib/src/Uncertainty/Distribution/MarginalDistribution.cxx
lib/src/Uncertainty/Model/SklarCopula.cxx
python/test/t_Distribution_python.py

The SklarCopula and MarginalDistribution classes were not taking into account the isParalel flag of their underlying distribution

Fixed ticket #899

---

CMakeLists.txt

Fixes a warning about RPATH settings on macOS that do not affect install_name:
https://cmake.org/cmake/help/v3.9/policy/CMP0068.html

[cmake] Set POLICY CMP0068

---

lib/src/Base/Optim/OptimizationResult.cxx
python/test/t_Viewer.py

We dont want the axis to go into negative values, the minimum is very close to zero.
before:
after:

Tighten error history graph Y axis bbox

---

lib/src/Base/Func/ComposedEvaluation.cxx
lib/src/Base/Func/ComposedFunction.cxx
lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/MarginalTransformationEvaluation.cxx
lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/openturns/MarginalTransformationEvaluation.hxx
lib/src/Uncertainty/Distribution/ComposedDistribution.cxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
python/src/MarginalTransformationEvaluation_doc.i.in
python/test/t_FunctionalChaos_ishigami.py

- In DistributionTransformation we use the MarginalTransformationEvaluation(DistributionCollection, DistributionCollection) ctor
in this case the direction flag is not initialized to something valid (FROMTO), so I added it to that ctor.
- In MarginalTransformationEvaluation::parameterGradient when there are no parameters the matrix is empty; exit sooner so as to avoid range exception in matrix.
This fixes computing FORM sensitivities on a FCE metamodel.
cc @aurelieladier

Fix MarginalTransformationEvaluation

---

ChangeLog
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/ProjectionStrategy.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/ProjectionStrategyImplementation.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/openturns/ProjectionStrategy.hxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/openturns/ProjectionStrategyImplementation.hxx
lib/test/t_FunctionalChaos_ishigami_database.cxx
python/src/ProjectionStrategyImplementation_doc.i.in
python/src/ProjectionStrategy_doc.i.in

Add accessors to the ProjectionStrategy interface to fix the reference counting in FunctionalChaosAlgorithm.
Fixes http://trac.openturns.org/ticket/927 (Functional chaos is memory hungry)
Note that now the projection strategy passed as argument of FCA is not modified in-place hence the modification to t_FunctionalChaos_ishigami_database.expout
I kept the friendship of ProjectionStrategyImplementation to FCA only for the updateBasis method and not to copy the Proxy at that moment. But this remains a bad design.
I also think that we shouldnt build metamodel algorithms without passing the actual input/output data: in FCA we do lots of complicated stuff to override the data.

Fix chaos memory usage

---

ChangeLog
lib/src/Base/Stat/CovarianceModelImplementation.cxx
python/test/t_ExponentialModel_std.py

Consistently only enable scale & amplitude whatever ctor is used
see http://trac.openturns.org/ticket/926

Covariance model: only activate scale & amplitude parameters by default

---

lib/src/Base/Func/EvaluationImplementation.cxx

If sample size is larger than cache size, there is no need to store first points, they will be thrown away.

Speed-up EvaluationImplementation::addCacheContent

---

python/src/viewer.py

Instead of ignoring contours with too few levels we catch the clablel exception.
See https://github.com/matplotlib/matplotlib/issues/9742
That way function plots that contain a contour per level are not ignored.

Catch pyplot.clabel exception

---

ChangeLog
lib/etc/openturns.conf.in
lib/src/Uncertainty/Distribution/BernsteinCopulaFactory.cxx
lib/src/Uncertainty/Distribution/openturns/BernsteinCopulaFactory.hxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx

The default value of BernsteinCopulaFactory-Parallel is *false* and the resulting Mixture has its parallel_ flag set to *false*
The return type of BernsteinCopulaFactory::build() is now a Pointer to a DistributionImplementation instead of an actual distribution in order to conform to the other distribution factories.

Worked around bug #864 (parallel BernsteinCopulaFactory segfault)

---

lib/src/Base/Type/openturns/Cache.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralLinearModelAlgorithm.hxx

We are only interested to find its maximum value, and thus we did not care to add the constant part, but user may be interested by the exact value.
Let loglikelihood function really uses its cache, it was enabled but not used.

Compute the exact log-likelihood in computeReducedLogLikelihood

---

lib/src/Base/Stat/AbsoluteExponential.cxx
lib/src/Base/Stat/CovarianceModelImplementation.cxx
lib/src/Base/Stat/ExponentialModel.cxx
lib/src/Base/Stat/ExponentiallyDampedCosineModel.cxx
lib/src/Base/Stat/GeneralizedExponential.cxx
lib/src/Base/Stat/MaternModel.cxx
lib/src/Base/Stat/ProductCovarianceModel.cxx
lib/src/Base/Stat/SampleImplementation.cxx
lib/src/Base/Stat/SphericalModel.cxx
lib/src/Base/Stat/SquaredExponential.cxx
lib/src/Base/Stat/openturns/AbsoluteExponential.hxx
lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx
lib/src/Base/Stat/openturns/ExponentialModel.hxx
lib/src/Base/Stat/openturns/ExponentiallyDampedCosineModel.hxx
lib/src/Base/Stat/openturns/GeneralizedExponential.hxx
lib/src/Base/Stat/openturns/MaternModel.hxx
lib/src/Base/Stat/openturns/ProductCovarianceModel.hxx
lib/src/Base/Stat/openturns/SampleImplementation.hxx
lib/src/Base/Stat/openturns/SphericalModel.hxx
lib/src/Base/Stat/openturns/SquaredExponential.hxx

Overload CovarianceModelImplementation::computeStandardRepresentative() method with arguments being iterators on Collection<Scalar>, instead of Point. This avoids the creation of temporary Point instances.

Speed-up computeStandardRepresentative() when called on a Sample

---

lib/src/Base/Func/PiecewiseHermiteEvaluation.cxx
lib/src/Base/Func/PiecewiseLinearEvaluation.cxx
lib/src/Base/Func/openturns/PiecewiseHermiteEvaluation.hxx
lib/src/Base/Func/openturns/PiecewiseLinearEvaluation.hxx

When interpolating on a Sample, it is likely than points are looked at in ascending order, bisection search can then be greatly fastened.
Use Sample::operator() instead of operator[].

Speed-up Piecewise{Hermite,Linear}Evaluation on a Sample

---

lib/src/Base/Type/openturns/Cache.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralLinearModelAlgorithm.hxx
lib/test/t_Cache_std.expout

With the previous implementation, when the Cache is full, the least recently used element is searched by traversing all elements whenever a new element is inserted.
This new implementation is more standard, it stores keys in a doubly-linked list, and uses a map to store the position of each key in this iterator. Key is moved at the beginning at the list when it is accessed, so tail list always contains the last recently used key.
Since the cache size is fixed, it would be better to use a hash map, but OT does not use hash map anywhere.

Alternate implementation of Cache

---

lib/src/Base/Func/PiecewiseHermiteEvaluation.cxx
lib/src/Base/Func/PiecewiseLinearEvaluation.cxx

Values are unchanged if locations are already sorted, and sort is faster.
Fix PiecewiseHermiteEvaluation::setLocations, it did not reorder values and derivatives.

Speed-up PiecewiseLinearEvaluation::setLocations

---

circle.yml

In the git version links to sphinx must be absolute and will need to be changed:
https://github.com/spatialaudio/nbsphinx/pull/136
failling build:
https://circleci.com/gh/openturns/openturns/1152?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Use nbsphinx stable

---

lib/src/Base/Stat/HMatrixImplementation.cxx

Replace by another expression which is stable.

rk_size semantics has changed in hmat-oss

---

python/src/openturns/PythonWrappingFunctions.hxx

Trying to convert a DataFrame to a sample crashes instead of raising an exception.
(a DataFrame mixes labels and values so it cannot yet be converted into a Sample directly, maybe TODO)
```
import pandas as pd
d = {'col1': [1.0, 2.0, 3.0], 'col2': [4.0, 5.0, 6.0]}
df = pd.DataFrame(data=d)
s = ot.Sample(df) # should throw
s = ot.Sample(df.values) # ok
```

Check pointer value in sequence helper

---

TODO
lib/src/Base/Func/LinearEvaluation.cxx
lib/src/Base/Geom/Mesh.cxx
lib/src/Base/Stat/openturns/Sample.hxx
lib/src/Base/Stat/openturns/SampleImplementation.hxx
lib/src/Base/Type/Matrix.cxx
lib/src/Base/Type/MatrixImplementation.cxx
lib/src/Base/Type/openturns/Matrix.hxx
lib/src/Base/Type/openturns/MatrixImplementation.hxx
lib/src/Uncertainty/Distribution/RandomMixture.cxx
lib/test/t_Matrix_std.cxx
lib/test/t_Matrix_std.expout
python/test/t_Matrix_std.expout
python/test/t_Matrix_std.py

New method `MatrixImplementation::genSampleProd()` to compute `matrix*sample`
or `sample*matrix` multiplications as if sample was a `MatrixImplementation`
stored in row-major order.  Result is directly stored into a `Sample`, thus
two copies are avoided.
Add `Matrix::operator*(Sample)`.
Deprecate `Sample{,Implementation}::operator*(SquareMatrix)` and
`operator/(SquareMatrix)`.

Multiply a matrix by a sample

---

ChangeLog
lib/src/Base/Func/P1LagrangeEvaluation.cxx
lib/src/Base/Geom/Mesh.cxx
lib/src/Base/Geom/RegularGrid.cxx
lib/src/Base/Geom/openturns/Mesh.hxx
lib/src/Base/Geom/openturns/RegularGrid.hxx
lib/src/Base/Stat/FieldImplementation.cxx
lib/src/Base/Stat/UserDefinedCovarianceModel.cxx
lib/test/t_Mesh_std.cxx
python/src/Mesh_doc.i.in
python/test/t_Mesh_std.py

In Mesh constructor, do not build KDTree by default anymore.
Building a KDTree is useful only if getNearest* methods are called.

New Mesh::computeKDTree method

---

lib/src/Base/Stat/SampleImplementation.cxx

TBB is useful only when performing heavy computations, as in computeKendallTau.

   Remove TBB from simple SampleImplementation methods

---

lib/src/Base/Geom/IntervalMesher.cxx
lib/src/Base/Geom/LevelSetMesher.cxx

Due to a bug, gradient was always falling back to
CenteredFiniteDifferenceGradient.
Rewrite IntervalMesher to not allocate objects in loops.
Avoid unnecessary Mesh assignments.
Replace Sample[i][j] by Sample(i, j).

Let LevelSetMesher::build really use gradient

---

ChangeLog
TODO
lib/src/Base/Geom/Domain.cxx
lib/src/Base/Geom/DomainImplementation.cxx
lib/src/Base/Geom/Interval.cxx
lib/src/Base/Geom/Mesh.cxx
lib/src/Base/Geom/openturns/Domain.hxx
lib/src/Base/Geom/openturns/DomainImplementation.hxx
lib/src/Base/Geom/openturns/Interval.hxx
lib/src/Base/Geom/openturns/Mesh.hxx
lib/src/Base/Stat/LowDiscrepancySequenceImplementation.cxx
lib/src/Uncertainty/Distribution/ConditionalDistribution.cxx
python/src/DomainImplementation_doc.i.in
python/src/Domain_doc.i.in
python/src/Interval_doc.i.in
python/src/Mesh_doc.i.in

Deprecate numericallyContains, isEmpty, isNumericallyEmpty, getVolume,
getNumericalVolume and computeVolume.
Some of these methods are defined in derived classes, when they make sense:
* Interval: isEmpty, isNumericallyEmpty, numericallyContains,
getVolume, computeVolume
* Mesh: isNumericallyEmpty, getVolume, computeVolume
Rename DomainImplementation::volume_ member into volumeOld_ to avoid name
conflict with derived classes, likewise for isAlreadyComputedVolume_.
In order to support these deprecated methods, protected method
DomainImplementation::computeVolume has been modified to return a Scalar.
When it is dropped, {Mesh,Interval}::computeVolume can be modified again
to not return a value.

Deprecate several Domain methods

---

lib/src/Base/Geom/Mesh.cxx
lib/src/Base/Geom/openturns/Mesh.hxx

Several tests have been added to Mesh::contains in order to exit early if
result is known to be false:
* If point is outside Mesh bounding box, result is false
* Simplices containing the nearest vertex are searched first; if point is
not contained in any such simplices, all simplices are searched for.
* checkPointInSimplexWithCoordinates() is modified too to return false
early if point is not contained in simplex bounding bounds.  Those
bounding boxes are precomputed.

Speed-up Mesh::contains

---

lib/src/Base/Common/openturns/TypedInterfaceObject.hxx

This operator is already defined in PersistentObject.hxx, but
interface classes inherit from TypedInterfaceObject.
Without this operator, we could have have (a==b) and (a!=b) both
return true (either in C++ or Python).

Add TypedInterfaceObject::operator!=

---

python/src/viewer.py

Calling OT methods within a for-loop is very expensive.

Convert hex code to RGBA in Python

---

lib/src/Uncertainty/Algorithm/Sensitivity/SaltelliSensitivityAlgorithm.cxx
lib/test/t_SobolIndicesAlgorithm_std.expout
python/src/JansenSensitivityAlgorithm_doc.i.in
python/src/SaltelliSensitivityAlgorithm_doc.i.in
python/test/t_SobolIndicesAlgorithm_std.expout
python/test/t_SobolIndicesAlgorithm_std.py

The numerator constant of the Saltelli first order index was computed as mean of product of G(A), G(B) whereas it should be the product of means as recommended by saltelli02
This was not consistent with the documentation either where noted as G_0^2, so we explicited it also.
The variance is larger (the estimator is worse after), but it is not a duplicate of Mauntz anymore.
before:
after:

Fix Saltelli estimator

---

lib/src/Base/Func/SymbolicEvaluation.cxx
lib/src/Base/Func/SymbolicParser.cxx
lib/src/Base/Func/openturns/SymbolicParser.hxx

This speeds up SymbolicEvaluation::operator()(Sample).
On a script Python with a Sample of size 32M and dimension 3, evaluation takes 1.5s instead of 5.2s.  I did not make more benchmarks, I expect gain to be larger with C++, but smaller with smaller size, which is more typical.

Add SymbolicParser::operator()(Sample)

---

lib/src/Base/Algo/KDTree.cxx
lib/src/Base/Algo/NaiveNearestNeighbour.cxx
lib/src/Base/Algo/NearestNeighbourAlgorithmImplementation.cxx
lib/src/Base/Algo/openturns/KDTree.hxx
lib/src/Base/Algo/openturns/NaiveNearestNeighbour.hxx

It must match `NearestNeighbourAlgorithmImplementation::__str__`.
Also fix a compiler warning about unused argument in
`NearestNeighbourAlgorithmImplementation::__str__`.

Fix {KDTree,NaiveNearestNeighbour}::__str__ definition

---

lib/src/Base/Algo/KarhunenLoeveP1Algorithm.cxx
lib/src/Base/Algo/KarhunenLoeveSVDAlgorithm.cxx
lib/src/Uncertainty/Process/KarhunenLoeveQuadratureAlgorithm.cxx
lib/test/t_PointToPointConnection_std.expout
python/doc/math_notations.sty
python/src/KarhunenLoeveAlgorithmImplementation_doc.i.in
python/src/KarhunenLoeveSVDAlgorithm_doc.i.in
python/test/t_PointToPointConnection_std.expout

The selection of the cut-off eigenvalue is now based on the full sum of eigenvalues, as they are already computed before the selection.
Several improvements have been made in the various Karhunen-Loeve algorithms:
* now the sorting is done without moving the eigenvectors
* the reuse of computations has been improved in the quadrature method
* the log messages are more consistent from one algorithm to the other
I also propose to switch to a more conventional notation for vectors and matrices, using boldface instead of underline. This commit can be dropped if it causes more trouble than others.

Improve kl algorithms

---

ChangeLog
lib/src/Base/Algo/KarhunenLoeveP1Algorithm.cxx
lib/src/Base/Algo/KarhunenLoeveResult.cxx
lib/src/Base/Algo/KarhunenLoeveResultImplementation.cxx
lib/src/Base/Algo/KarhunenLoeveSVDAlgorithm.cxx
lib/src/Base/Algo/openturns/KarhunenLoeveResult.hxx
lib/src/Base/Algo/openturns/KarhunenLoeveResultImplementation.hxx
lib/src/Base/Func/P1LagrangeEvaluation.cxx
lib/src/Base/Func/openturns/P1LagrangeEvaluation.hxx
lib/src/Uncertainty/Process/KarhunenLoeveQuadratureAlgorithm.cxx
python/src/KarhunenLoeveResultImplementation_doc.i.in

Computations with TBB were buggy.
Rewrite project() to perform matrix-matrix multiplications without TBB,
this is much faster than TBB wih matrix-vector multiplications, and as
a bonus gives the right result.
Remove project(Basis), it is very likely that it was buggy too because
of TBB usage, and it was also very slow.

Improve KarhunenLoeveResult::project(ProcessSample)

---

lib/src/Base/Stat/RankMCovarianceModel.cxx

Functions on t were evaluated several times, and remove matrix scaling.
Fix RankMCovarianceModel for input or output dimension > 1.

Speed-up RankMCovarianceModel::operator()(s,t)

---

ChangeLog
TODO
lib/src/Base/Func/EvaluationImplementation.cxx
lib/src/Base/Func/FunctionImplementation.cxx
lib/src/Base/Func/GradientImplementation.cxx
lib/src/Base/Func/HessianImplementation.cxx
lib/src/Base/Func/ParametricEvaluation.cxx
lib/src/Base/Func/ParametricGradient.cxx
lib/src/Base/Func/ParametricHessian.cxx
lib/src/Base/Func/openturns/Evaluation.hxx
lib/src/Base/Func/openturns/EvaluationImplementation.hxx
lib/src/Base/Func/openturns/EvaluationProxy.hxx
lib/src/Base/Func/openturns/Function.hxx
lib/src/Base/Func/openturns/FunctionImplementation.hxx
lib/src/Base/Func/openturns/Gradient.hxx
lib/src/Base/Func/openturns/GradientImplementation.hxx
lib/src/Base/Func/openturns/Hessian.hxx
lib/src/Base/Func/openturns/HessianImplementation.hxx
lib/src/Base/Func/openturns/ParametricEvaluation.hxx
lib/src/Base/Func/openturns/ParametricGradient.hxx
lib/src/Base/Func/openturns/ParametricHessian.hxx

Likewise for gradient and hessian.
Changing parameters has a cost, functions must be cloned, this should not
be hidden.

Deprecate Evaluation::operator()(inP,parameter)

---

lib/src/Base/Algo/EnclosingSimplexAlgorithm.cxx

When there are no simplices, Mesh::isRegular() does not check
vertex position, and thus always return true.

Fix EnclosingSimplexAlgorithm constructor

---

lib/src/Base/Algo/KDTree.cxx
lib/src/Base/Algo/openturns/KDTree.hxx

Allocation and deallocation of KDNode take time.
Use a single Indices member instead to store the list of
node index, left and right children.

Linearize KDTree in an Indices

---

lib/src/Base/Func/openturns/FieldFunctionImplementation.hxx

Otherwise derived classes cannot redefine it.

Make FieldFunctionImplementation::getOutputMesh virtual

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Func/SymbolicParserExprTk.cxx
lib/src/Base/Func/SymbolicParserImplementation.cxx
lib/src/Base/Func/SymbolicParserMuParser.cxx
lib/src/Base/Func/openturns/SymbolicParserImplementation.hxx
lib/test/t_SymbolicFunction_muparser.cxx
lib/test/t_SymbolicFunction_muparser.expout
lib/test/t_SymbolicFunction_std.cxx
lib/test/t_SymbolicFunction_std.expout
python/test/t_SymbolicFunction_muparser.expout
python/test/t_SymbolicFunction_muparser.py
python/test/t_SymbolicFunction_std.expout
python/test/t_SymbolicFunction_std.py

In some circumstances it is desirable to let symbolic parsers produce NaNs or Infs when they are evaluated over a sample and then to filter out the result afterward instead of throwing an exception at the first nonnoral result encountered.

Added a flag to tell if the symbolic parsers have to check their output

---

ChangeLog
lib/src/Uncertainty/Distribution/EmpiricalBernsteinCopula.cxx
lib/src/Uncertainty/Distribution/openturns/EmpiricalBernsteinCopula.hxx
lib/src/Uncertainty/Distribution/openturns/Mixture.hxx
lib/src/Uncertainty/Model/CopulaImplementation.cxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
lib/src/Uncertainty/Model/SklarCopula.cxx
lib/src/Uncertainty/Model/openturns/CopulaImplementation.hxx
lib/test/t_EmpiricalBernsteinCopula_std.expout
python/test/t_EmpiricalBernsteinCopula_std.expout

This PR fixes ticket #947. It allows to build an EmpiricalBernsteinCopula object even if the resulting distribution is not a copula, for statistical estimation purpose. It may be strange to name a distribution an EmpiricalBernsteinCopula even when it is not a proper copula, but the name is in the literature since 2004 and the fact that an arithmetic condition is mandatory to get a proper copula has been proved only in 2017!
I finally succeeded in fixing the circular dependency between CopulaImplementation and DistributionImplementation, so the PR should be ok now...

Relax empirical bernstein copula

---

lib/src/Base/Func/SymbolicParserExprTk.cxx
lib/src/Base/Func/SymbolicParserMuParser.cxx

Show up on Fedora 28 (gcc 8.0.1) with the distro compilation options:
CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
-fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic
-fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection'

Fix segfault in symbolic parser

---

lib/src/Base/Func/MemoizeFunction.cxx

We use that to detect if default finite difference method is used

Memoize to preserve useDefaultGrad|Hess attributes

---

lib/src/Base/Func/LinearCombinationEvaluation.cxx

Attributes are reset in setFunction... as it's a ref we cannot pass them

Fix segfault in LinearCombinationEval::load

---

lib/src/Base/Stat/Sample.cxx
lib/src/Base/Stat/SampleImplementation.cxx
lib/src/Base/Stat/openturns/Sample.hxx
lib/src/Base/Stat/openturns/SampleImplementation.hxx
lib/test/t_Sample_computation.cxx
lib/test/t_Sample_computation.expout
python/src/Sample_doc.i.in
python/test/t_Sample_computation.expout
python/test/t_Sample_computation.py

Use std::nth_element, this is faster than sorting the whole Sample, even with TBB on very large Sample.
Add method Sample::computeQuantilePerComponent(Point). This allows to compute several quantiles at once, this is a little faster than consecutive calls.
<s>Argument must be sorted in ascending order, otherwise an exception is raised.</s> EDITED: argument can now be unsorted

Speed-up Sample::computeQuantilePerComponent

---

lib/src/Base/Stat/ProcessSample.cxx
lib/src/Base/Stat/ProcessSampleImplementation.cxx
lib/src/Base/Stat/openturns/ProcessSample.hxx
lib/src/Base/Stat/openturns/ProcessSampleImplementation.hxx
python/src/ProcessSampleImplementation_doc.i.in

In master, each trajectory is extracted from the ProcessSample, copied into a Sample, and Sample::computeQuantilePerComponent is called.
In this PR, the ProcessSample is duplicated and transposed so that trajectories become contiguous in memory.  This is faster, benchmarks are provided below, but requires more memory since ProcessSample is duplicated.
A new method ProcessSample::computeQuantilePerComponent(Point) is added, so that this copy is performed only once when computing several quantiles.

Speed-up ProcessSample::computeQuantilePerComponent

---

lib/src/Base/Diff/CenteredFiniteDifferenceHessian.cxx
lib/src/Base/Diff/NonCenteredFiniteDifferenceGradient.cxx

We currently evaluate functions on shifted points, and last on center point.
This commit switches evaluation order to first evaluate on center point.
The reason is that the most common case is to perform evaluation then
gradient at the same location, so new evaluation order is better in order
to benefit from an LRU cache, or from a cache with a very small size.

Change evaluation order in NonCenteredFiniteDifferenceGradient::gradient

---

lib/src/Base/Stat/CovarianceModelImplementation.cxx
lib/src/Base/Stat/HMatrix.cxx
lib/src/Base/Stat/HMatrixImplementation.cxx
lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx
lib/src/Base/Stat/openturns/HMatrix.hxx
lib/src/Base/Stat/openturns/HMatrixImplementation.hxx
python/src/HMatrix.i
python/src/HMatrixImplementation_doc.i.in
python/src/HMatrix_doc.i.in

`CovarianceModel::discretize` method had been made faster in PR #492 and #599.  This PR applies similar tricks for HMatrix, and timings look much better now.

Speed-up CovarianceModel::discretizeHMatrix

---

lib/src/Base/Stat/SampleImplementation.cxx

size_ must be used, not data.getSize(), which is the global number of
elements, also chose to use '>=' instead of '>'.

Fix Sample.__str__ ellipsis condition

---

lib/src/Base/Graph/GraphImplementation.cxx
python/src/GraphImplementation_doc.i.in

In log-scale, check that the margin would not exceed the range
This is needed in the spectral estimation example from doc branch.

Graph: apply margins within log bounds

---

lib/src/Uncertainty/Distribution/ComposedCopula.cxx
lib/src/Uncertainty/Distribution/ComposedDistribution.cxx

The warning from (https://github.com/openturns/openturns/pull/794/commits/4a0012a109d2b33552f86abc1484df967e32cccf) is really common with ComposedDistribution.

Fix composed distributions description warnings

---

lib/src/Base/Graph/DrawableImplementation.cxx

the value field is computed with a slight difference

Fix Drawable::BuildDefaultPalette in 32 bits

---

lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/MarginalTransformationEvaluation.cxx
lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation/openturns/MarginalTransformationEvaluation.hxx

The improvement of ResourceMap (direct access to a Scalar instead of a systematic conversion from a String) lead to an improvement of x1.94 wrt OT 1.11 on the benchmark (Uniform, Triangular)->(Normal, Normal). In this PR, the introduction of a specific attribute to switch to tail evaluation gives an improvement of x2.48 wrt OT 1.11.

Improved the performance of MarginalTransformationEvaluation

---

lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosSobolIndices.cxx
lib/src/Uncertainty/Algorithm/MetaModel/MetaModelValidation.cxx
lib/test/t_MetaModelValidation_std.expout
python/doc/theory/reliability_sensitivity/taylor_importance_factors.rst
python/src/MetaModelValidation_doc.i.in
python/src/SobolIndicesAlgorithmImplementation_doc.i.in
python/test/t_MetaModelValidation_std.expout

In #836 , we set a wrong definition of predictive factor in `MetaModelValidation` docstring.
The previous one was more accurate and requires updating the library.
It is done here.
We also fix SobolIndicesAlgorithm/Taylor importance factors docstrings

Docstring fixes

---

ChangeLog
lib/src/Uncertainty/Distribution/NormalCopula.cxx
lib/src/Uncertainty/Distribution/openturns/NormalCopula.hxx
python/test/t_NormalCopula_std.expout
python/test/t_NormalCopula_std.py

It's better to use DistributionImplementation::getParametersCollection
as it relies on getParameter which returns an empty point in NormalCopula.
Now NormalCopula(1).getParametersCollection() returns a collection with
an empty point instead of an empty collection and fixes http://trac.openturns.org/ticket/970

Fix 1-d NormalCopula::getParametersCollection

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx

On a side note I noticed the types are inconsistent with the xml tags:
```
static const char * XMLTag_value                  = "value_string";
static const char * XMLTag_value_scalar           = "value_scalar";
static const char * XMLTag_value_unsigned_integer = "value_unsigned_integer";
static const char * XMLTag_value_bool             = "value_bool";
```
vs
```
if (it != mapString_.end()) return "string";
if (it != mapScalar_.end()) return "float";
if (it != mapUnsignedInteger_.end()) return "unsigned int";
if (it != mapBool_.end()) return "bool";
```
I propose to use Python types instead: "str", "float", "int", "bool", it will show more nicely in the ResourceMap doc, what do you think ?

Typo in openturns.conf

---

.circleci/config.yml

IPython 7 only supports Python 3.5+, and trusty uses 3.4, so examples
are disabled

CI: Use IPython <7

---

lib/src/Base/Stat/openturns/SampleImplementation.hxx
python/src/openturns/PythonWrappingFunctions.hxx
python/test/t_Matrix_numpy.expout
python/test/t_Matrix_numpy.py

Fixes empty array conversions crashes with GLIBCXX_ASSERTIONS when accessing &std::vector[0]

Fix crash in Python conversions

---

CMakeLists.txt
cmake/TargetLinkLibrariesWithDynamicLookup.cmake
distro/debian/rules
python/src/CMakeLists.txt

On osx/py3 we have to weak link the python libs otherwise we get:
Fatal Python error: PyThreadState_Get: no current thread
On windows undefined symbols are not allowed and on
osx a specific flag is required (-undefined dynamic_lookup) so we add
the macro from vtk: https://gitlab.kitware.com/vtk/vtk/merge_requests/1511

Link swig modules with dynamic lookup

---

python/doc/examples/meta_modeling/viscous_fall_metamodel.ipynb
python/doc/examples/numerical_methods/logistic_growth_model.ipynb
python/src/DistributionImplementation_doc.i.in

Turns out we cannot use citations cleanly in inherited docsrtings:
https://github.com/sphinx-doc/sphinx/issues/5528
We can simply remove these as the docstring already points to the
theoric section where citations are.

Remove citations from DI::getIsoPT docstring

---

ChangeLog
lib/src/Uncertainty/Distribution/EmpiricalBernsteinCopula.cxx
python/test/t_BernsteinCopulaFactory_std.expout
python/test/t_BernsteinCopulaFactory_std.py

When building the EmpiricalBernsteinCopula, if provided sample is not a  "copula sample", we
enforce sample size to be multiple of binNumber, thus is becomes a copula.
This fixes http://trac.openturns.org/ticket/975

Bugfix in EmpiricalBernsteinCopula

---

lib/src/Base/Optim/AbdoRackwitz.cxx
lib/src/Base/Optim/Cobyla.cxx
lib/src/Base/Optim/MultiStart.cxx
lib/src/Base/Optim/NLopt.cxx
lib/src/Base/Optim/SQP.cxx
lib/src/Base/Optim/TNC.cxx
python/test/t_MultiStart_std.py

In SQP, Abdorackwitz the number of iterations was used.
It was missing from TNC, Cobyla, NLopt.
For multistart the budget is the total of local searches.

Optim: Track progress wrt eval number

---

ChangeLog
lib/src/Uncertainty/StatTests/LinearModelTest.cxx
python/src/LinearModelTest_doc.i.in
python/test/t_LinearModelTest_std.expout
validation/src/ValidDurbinWatson.py
validation/src/ValidDurbinWatson.txt

I forgot to take into account several factors when building the regression matrix.
I noticed also an error when computing the p-value, that I corrected.
A validation python file, comparing result with OT and R is provided in validation/src/ValidDurbinWatson.py
As an improvement, it could be nice to have the statistic value in the result object.

fix bug 982 : durbin watson for several inputs

---

lib/src/Uncertainty/StatTests/LinearModelTest.cxx
lib/src/Uncertainty/StatTests/openturns/LinearModelTest.hxx
lib/test/t_LinearModelTest_std.expout
python/src/LinearModelTest_doc.i.in
python/test/t_LinearModelTest_std.expout

We remove dependency to `rot` statistical test. `rot` is used only when using `LinearModelFactory` class
The `rot` implementation is bogus. Indeed Fisher test relies on the statistic which is a ratio of SSExplained and SSResiduals. This is now fixed

Remove rot dependency in LinearModelTest

---

python/src/viewer.py

This changes calls to matplolibs to use 1-d arrays (Point) instead of 2-d arrays (Sample), eg:
```
x = data.getMarginal(0).asPoint()
Axes.pie(x)
```
This works around an issue in matplotlib with latest numpy: https://github.com/matplotlib/matplotlib/issues/13286, cc @pcaclin

Viewer: Dont use matplotlib 2-d input

---

lib/src/Uncertainty/Distribution/TruncatedDistribution.cxx
python/test/t_TruncatedDistribution_std.expout
python/test/t_TruncatedDistribution_std.py

It was not updating (c|p)df(Lower|Upper)Bound_ attributes

Fix TruncatedDistribution::setBounds

---

ChangeLog
python/src/openturns/PythonWrappingFunctions.hxx
python/test/t_Sample_std.expout
python/test/t_Sample_std.py

Python: Avoid empty throws in conversion primitives

---

lib/test/CMakeLists.txt
python/test/CMakeLists.txt
python/test/t_coupling_tools.expout
python/test/t_coupling_tools.py

t_coupling_tools may fail on conda-forge docker images where /bin/kill is not available

 t_coupling_tools: /bin/kill may not exist 

---

lib/src/Uncertainty/Distribution/ComposedCopula.cxx
lib/src/Uncertainty/Distribution/MarginalDistribution.cxx
lib/src/Uncertainty/Distribution/openturns/MarginalDistribution.hxx
python/test/t_ComposedCopula_std.expout
python/test/t_ComposedCopula_std.py
python/test/t_DistributionTransformation_std.expout
python/test/t_DistributionTransformation_std.py

* Now ComposedCopula::getMarginal handles the copulas blocs to be visited
in any order:
```
copula = ComposedCopula([IndependentCopula(2), NormalCopula(2)])
print(copula.getMarginal([3, 2, 1, 0]))
ComposedCopula(NormalCopula(R = [[ 1 0 ]
[ 0 1 ]]), IndependentCopula(dimension = 2))
```
* Also we Implement MarginalDist;::getParametersCollection to handle the non-contiguous case when used in iso-probabilistic transformations:
Else the parameters of the isoprobabilistic transformations involving
MarginalDistribution (from a ComposedCopula with non-contiguous blocs) cannot be retrieved:
```
copula = ot.ComposedCopula([ot.IndependentCopula(2), ot.IndependentCopula(2)])
distribution = ot.ComposedDistribution([ot.Normal()]*4, copula) …
```

getMarginal-related enhancements

---

lib/src/Base/Func/AggregatedEvaluation.cxx
lib/src/Uncertainty/Algorithm/Transformation/Rosenblatt/InverseRosenblattEvaluation.cxx
lib/src/Uncertainty/Algorithm/Transformation/Rosenblatt/RosenblattEvaluation.cxx
python/test/CMakeLists.txt
python/test/t_InverseRosenblattEvaluation_std.py

I fixed the parameter gradient of the iso-transformation with the current state of marginal/copula parameters in transformation, as it failed on this example that uses the rosenblatt transformation:
```
model = ot.SymbolicFunction(['x0', 'x1', 'x2', 'x3'], ['-(6+x0^2-x1+x2+3*x3)'])
dim = model.getInputDimension()
marginals = [ot.Normal(5.0, 3.0) for i in range(dim)]
distribution = ot.ComposedDistribution(marginals, ot.ComposedCopula([ot.ClaytonCopula(), ot.NormalCopula()]))
#distribution = ot.Normal([5]*dim, [3]*dim, ot.CorrelationMatrix(dim))
#distribution = ot.ComposedDistribution(marginals, ot.IndependentCopula(dim))
distribution.setDescription(['marginal'+str(i) for i in range(dim)])
vect = ot.RandomVector(distribution)
output = ot.CompositeRandomVector(model, …
```

Fix iso-transformation parameter gradient

---

ChangeLog
python/src/PythonDistribution.cxx
python/src/PythonEvaluation.cxx
python/src/PythonExperiment.cxx
python/src/PythonFieldFunction.cxx
python/src/PythonFieldToPointFunction.cxx
python/src/PythonGradient.cxx
python/src/PythonHessian.cxx
python/src/PythonPointToFieldFunction.cxx
python/src/PythonRandomVectorImplementation.cxx
python/src/openturns/PythonWrappingFunctions.hxx
python/test/t_Distribution_python.expout
python/test/t_Distribution_python.py

Fix openturns#1099 
* Fix `PythonDistribution::setParameter` : need to compute the new range
* Fix  `PythonDistribution::clone` : copy constructor PythonDistribution(other) should duplicate the internal attribut
* Apply fix to `PythonEvaluation`, `PythonExperiment`, `PythonFieldToFunction`, `PythonGradient`, `PythonHessian`, `PythonRandomVectorImplementation` classes

Improve cloning python wrappers

---

.circleci/run_docker_linux.sh
.circleci/upload_github_io.sh

The previous logic was not working as tagged jobs are filtered by default:
https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
I did not include tag jobs neither as the date will be overwritten by the new commit
in the release branch, so only setting a fake date in master will do.

CircleCI: Use real doc date on release branches

---

lib/src/Base/Diff/Ev3/expression.cxx
python/test/t_SymbolicFunction_std.expout
python/test/t_SymbolicFunction_std.py

Fixes the Joe copula formula derivation: "1-((0.5*(1-t))^(-1.0/0.5)+(0.5*t)^(-1.0/0.5))^(-0.5)"

Fix ev3 exponent var node derivation

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Stat/FieldImplementation.cxx

Now the user can choose between an automatic scaling of the arrows for R^2->R^2 fields (the default) or a fully manual scaling (eg to compare fields on the same mesh). It fixes issue #1160.

Improved Field::draw()

---

python/src/FAST_doc.i.in
python/src/JansenSensitivityAlgorithm_doc.i.in
python/src/MartinezSensitivityAlgorithm_doc.i.in
python/src/MauntzKucherenkoSensitivityAlgorithm_doc.i.in
python/src/SaltelliSensitivityAlgorithm_doc.i.in
python/src/SobolIndicesExperiment_doc.i.in

This PR considers the Sobol' sampling examples
* simplifies the Ishigami formula with the power operator
* removes the unnecessary independent copula (which is independent, by default)
* provides examples for the second order indices, removing the unnecessary computations when they are not required

Fixed Sobol' indices examples

---

ChangeLog
lib/src/Uncertainty/StatTests/FittingTest.cxx
lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx
python/doc/examples/data_analysis/kolmogorov_test.ipynb
python/src/FittingTest.i
python/src/FittingTest_doc.i.in
python/src/TestResult_doc.i.in

Now we return the estimated distribution when the `factory` is provided as input argument.
It fixes #1130

Fix FittingTest class

---

ChangeLog
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingResult.hxx
lib/src/Uncertainty/Algorithm/Optimization/EfficientGlobalOptimization.cxx
lib/test/t_KrigingAlgorithm_std.cxx
lib/test/t_KrigingAlgorithm_std_hmat.cxx
python/src/KrigingResult_doc.i.in
python/test/t_KrigingAlgorithm_std.py
python/test/t_KrigingAlgorithm_std_hmat.py

The main objective is to provide new methods for kriging post-processing.
Here 2 methods are implemented :
- `getConditionalMarginalCovariance` : which acts on a `n-Sample` and provide a n-`CovarianceMatrixCollection`. Each element of the collection corresponds to the conditional covariance evaluated on the `ith` element of sample conditionally to all observations
- `getConditionalMarginalVariance` : which acts on a `n-Sample` and provide a `n-Point` (if marginal of interest is 1D) or `(n*d)-Sample`, `d` being the size of marginal interests.
The method might be seen as the restriction of the previous one on specific marginal of interests.
This fixes #1184 
We also made benefit of this PR to update the API ( coding rules ).

Kriging improvements

---

lib/src/Base/Stat/ProductCovarianceModel.cxx
lib/src/Base/Stat/openturns/ProductCovarianceModel.hxx
python/test/CMakeLists.txt
python/test/t_ProductCovarianceModel_std.expout
python/test/t_ProductCovarianceModel_std.py

We fix It fixes openturns#1264
* Now the parameter attribut take into account potential external parameters : `getFullParameter`, `getFullParameterDescription` and `setFullParameter` have the expected behaviour
* `getActiveParameter`and `setActiveParameter` are fixed
* A specific test is added

Bugfix in ProductCovarianceModel

---

lib/src/Uncertainty/Distribution/FisherSnedecorFactory.cxx
lib/src/Uncertainty/Distribution/openturns/FisherSnedecorFactory.hxx
lib/test/t_FisherSnedecorFactory_std.cxx
lib/test/t_FisherSnedecorFactory_std.expout
python/src/FisherSnedecorFactory_doc.i.in
python/src/FisherSnedecor_doc.i.in
python/src/LogNormalFactory_doc.i.in

The goal of this proposal is to increase the speed of the Kolmogorov-Smirnov test when the parameters of the distribution are estimated from a sample. Although the ultimate goal is to fix #1061, it only partially solves it and more work would be required. 
Since the FisherSnedecor was shown to have the least performance, this proposal creates a new FisherSnedecorFactory::buildMethodOfMoments method. 
* This method is used as a starting point for the likelihood maximization. This is, in general, better than using the parametersLowerBound in the current implementation. As a result, when the buildMethodOfMoments fails, the default "build" method fails: I consider that this is a reasonable behavior, but this might be discussed. 
* In the KS test experiments that I did, this increases the …

Improve Kolmogorov-Smirnov test

---

lib/src/Uncertainty/Model/DistributionImplementation.cxx
python/test/t_Distribution_arithmetic.expout
python/test/t_Distribution_arithmetic.py

The weight was not taken into account if a simplification had occured in a sum or a difference.

Fixed distribution arithmetic

---

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx

This way its consistent with the lapack variant
cc @josephmure

GLM: Use LogMaxScalar for logdet hmat variant

---

lib/src/Uncertainty/Distribution/Hypergeometric.cxx
python/src/Distribution.i
python/src/SystemFORM_doc.i.in
python/test/t_Hypergeometric_std.py

There are several combinations of parameters {n,k,m} where the distribution
is equivalent to a dirac (k=0, m=0).
In these configurations computeScalarQuantile can exit early to avoid
freezes.

Hypergeometric: Fix computeScalarQtle when dirac

---

lib/src/Uncertainty/Distribution/EmpiricalBernsteinCopula.cxx
lib/src/Uncertainty/Distribution/Uniform.cxx
lib/src/Uncertainty/Distribution/openturns/EmpiricalBernsteinCopula.hxx
lib/src/Uncertainty/Distribution/openturns/Uniform.hxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
lib/test/t_EmpiricalBernsteinCopula_std.expout
python/test/t_EmpiricalBernsteinCopula_std.expout

Now the range is set using a unit interval instead of relying on the default algorithm (computation of many quantiles). On the following benchmark, typical from what append in graphical models:
```
dim = 6
size = 10000
binNumber = 5
sample = ot.IndependentCopula(dim).getSample(size)
copula = ot.EmpiricalBernsteinCopula(sample, binNumber)
t0 = time()
for k in range(1, dim + 1):
permutations = ot.KPermutations(k, dim).generate()
for indices in permutations:
d = copula.getMarginal(indices)
t1 = time()
print("t=", t1 - t0, "s")
```
the speed-up is more than 12x

Improve bernstein copula

---

lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingEvaluation.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingResult.hxx

This PR improves significantly the `KrigingResult::getMarginalVariance`method
With this basic benchmark : 
```
from __future__ import print_function
model = ot.SymbolicFunction(["E", "F", "L", "I"], ["F*L^3/(3*E*I)"])
E = ot.Beta(0.9, 3.5, 2.5e7, 5.0e7)  # in N/m^2
F = ot.LogNormal()  # in N
F.setParameter(ot.LogNormalMuSigma()([30.e3, 9e3, 15.e3]))
L = ot.Uniform(250., 260.)  # in cm
I = ot.Beta(2.5, 4, 310, 450)  # in cm^4
dist = ot.ComposedDistribution([E, F, L, I])
sampleSize_train = 2000
X_train = dist.getSample(sampleSize_train)
Y_train = model(X_train)
dimension = dist.getDimension()
basis = ot.ConstantBasisFactory(dimension).build()
covarianceModel = ot.SquaredExponential([1.]*dimension, [1.0])
tic = time()
algo = …
```

Improving KrigingResult post processing methods

---

python/doc/examples/meta_modeling/kriging_advanced.ipynb

In the [Advanced Kriging](https://github.com/josephmure/openturns/blob/master/python/doc/examples/meta_modeling/kriging_advanced.ipynb) example (cell 8), in order to draw confidence intervals, Samples are converted to numpy arrays of shape (1000,) with the `np.hstack` command and then added to a numpy array with shape (1,1000). The resulting array has shape (1000,1000). This is not the desired behavior.
It turns out that this conversion is useless, because the sum of a Sample with size 1000 and dimension 1 and of a numpy array with shape (1,1000) is a Sample with size 1000 and dimension 1 which can be drawn by matplotlib.

Fix numpy broadcasting error in example

---

ChangeLog
python/doc/examples/probabilistic_modeling/user_stationary_covmodel.ipynb
python/src/UserDefinedStationaryCovarianceModel_doc.i.in

UserDefinedStationaryCovarianceModel takes a RegularGrid as input, so the input space must be of dimension n=1.
Correct API doc and example notebook.
Closes #1421.

Correct UserDefinedStationaryCovarianceModel doc

---

ChangeLog
TODO
lib/src/Uncertainty/StatTests/VisualTest.cxx
lib/src/Uncertainty/StatTests/openturns/VisualTest.hxx
python/src/FittingTest_doc.i.in
python/src/Log_doc.i.in
python/src/VisualTest_doc.i.in

This question "How can I turn warnings off?" has now come up several times in discussions.
The first commit documents this and also wrote how to direct warnings to a log file. Closes #1578.
The second commit fixes #1586 and removes a leftover reference to R in the `FittingTest_BestModelChiSquared` doc.
The third commit undoes part of PR #1576: there are cases where the long version of `VisualTest_DrawLinearModel(Residual)` can be useful, which justifies undeprecating it (one could want to perform the test on a different sample than the training sample). However, the short version is useful for testing with the training sample, so it is kept as well. The doc is updated to reflect this.

Document how to turn warnings off and other changes

---

python/doc/_static/css/custom.css

Append custom.css to disable the sphx-glr-download-link-note class. Fixes #1619.
I simply applied https://github.com/sphinx-gallery/sphinx-gallery/issues/757

Remove top box with download link in doc pages

---

ChangeLog
lib/src/Uncertainty/StatTests/FittingTest.cxx
python/doc/examples/py_graphs/plot_graphs_loglikelihood_contour.py

* Improved FittingTest::BestModelLilliefors: now a first pass is done using the biased Kolmogorov p-value to sort the proposed factories. Then, as soon as a given factory leads to a distribution with an unbiased p-value greater than the biased p-value of another factory, this last one can be disgarded. It allows for massive savings in computation time while remaining exact.
* Fixed the loglikelihood function example: the loglikelihood function implemented in plot_graphs_loglikelihood_contour.py was wrong, leading to a theoretically infinite loglikelihood for any value of its input. It closes issue #1624.
The following script takes 167s to complete with this PR, while it is still running (>5h) with the current master:
``` …
```

Improve lilliefors model selection

---

lib/src/Uncertainty/Distribution/Frechet.cxx
lib/src/Uncertainty/Distribution/openturns/Frechet.hxx
lib/test/t_FrechetFactory_std.cxx
lib/test/t_FrechetFactory_std.expout
python/test/t_FrechetFactory_std.expout
python/test/t_FrechetFactory_std.py

This fixes a bug with `FrechetFactory::buildAsFrechet`.
Consider the following script. We try to fit a Frechet distribution on a sample obtained from a mixture of a Frechet and a Gumbel distribution. The optimization currently fails because the gradient of the logPDF is not implemented. Implementing it fixes the issue.
```
myFrechet = ot.Frechet(1.0, 1.0, 0.0)
myGumbel = ot.Gumbel(1.0,3.0)
mixtureSample = ot.Sample()
sampleFrechet = myFrechet.getSample(1000)
sampleGumbel = myGumbel.getSample(1000)
mixtureSample.add(sampleFrechet)
mixtureSample.add(sampleGumbel)
typedEstimatedFromMixtureSample = factory.buildAsFrechet(mixtureSample)
print('Estimated dist from mixture sample=', typedEstimatedFromMixtureSample)
print('Average logPDF of mixture sample=', …
```

Implement Frechet computeLogPDFGradient [1.16]

---

ChangeLog
lib/src/Uncertainty/Distribution/EmpiricalBernsteinCopula.cxx
lib/src/Uncertainty/Distribution/MaximumDistribution.cxx
lib/src/Uncertainty/Distribution/openturns/EmpiricalBernsteinCopula.hxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
python/test/t_EmpiricalBernsteinCopula_std.expout
python/test/t_EmpiricalBernsteinCopula_std.py

This PR fixes several problems:
+ the bad performance of conditional PDF/CDF/Quantile computations in EmpiricalBernsteinCopula, making it useless for e.g. FORM/SORM analyses
+ a bug in MaximumDistribution::computePDF(), see #1643 
+ more check in Distribution methods
the following benchmark:
```
from openturns import *
sample = NormalCopula(20).getSample(1000)
copula = EmpiricalBernsteinCopula(sample, 5)
size = 1000
u = copula.getSample(size)
t0 = time()
for x in u:
res = copula.computeConditionalPDF(x[-1], x[:-2])
t1 = time()
print("speed conditional PDF=", size / (t1 - t0), "evals/s")
t0 = time()
for x in u:
res = copula.computeConditionalCDF(x[-1], x[:-2])
t1 = time()
print("speed conditional CDF=", size / (t1 - t0), "evals/s")
t0 = time()
for q in u:
res = …
```

Improve empirical bernstein copula & other fixes

---

ChangeLog
TODO
lib/src/Uncertainty/Bayesian/MCMC.cxx
lib/src/Uncertainty/Bayesian/RandomWalkMetropolisHastings.cxx
lib/src/Uncertainty/Bayesian/openturns/MCMC.hxx
lib/src/Uncertainty/Bayesian/openturns/RandomWalkMetropolisHastings.hxx
python/doc/_static/css/custom.css
python/test/t_RandomWalkMetropolisHastings_std.expout
python/test/t_RandomWalkMetropolisHastings_std.py

- ~~Turn the old `computeLogLikelihood` public method
into a `computeLogLikelihoodPlusLogPrior` protected method.~~ Compute the sum of loglikelihood and logprior every time the class needs it.
- ~~Create a new~~ Make sure the public `computeLogLikelihood` method ~~that~~ actually
computes the log-likelihood. Fixes #1647.
- Deprecate `currentLogLikelihood_` attribute and replace it with
`currentLogLikelihoodPlusLogPrior_`.
- Update ChangeLog and TODO.
~~The method  `computeLogLikelihoodPlusLogPrior` is necessary, otherwise the class cannot work. Since 1.16rc1 is already out, however, I have chosen not to expose it. That way, if we decide to expose it in 1.17, we can change the name of the method without deprecating anything.~~
From the point of view of a user, nothing changes with this PR …

Correct the formula of MCMC::computeLogLikelihood [1.16]

---

ChangeLog
lib/src/Base/Geom/LevelSetMesher.cxx
python/test/t_LevelSetMesher_std.py

Now, it takes into account the comparison operator of the underlying LevelSet. Fixes #1668.

Fixed LevelSetMesher

---

python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_beam_trend.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_cantilever_beam.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_cantilever_beam_hmat.py
python/doc/examples/reliability_sensitivity/reliability/plot_subsetSampling.py

It is possible to play with the bounds of the optimization algorithm instead.
This is more elementary in my opinion.

Remove IsoProbabilisticTransform in Kriging examples

---

ChangeLog
lib/src/Base/Stat/Sample.cxx
lib/src/Base/Stat/openturns/Sample.hxx
python/src/Sample_doc.i.in

In a previous [commit](https://github.com/openturns/openturns/pull/1467/commits/3dc8c299293ed256fd77da21510bb436ad0bf7a9), we dropped `Sample(seq, dim)` ctor. Even if this is a small feature with small impact, according to [that discussion](https://github.com/openturns/openturns/issues/1465#issuecomment-688673243), it might be considered as a regression.
Thus we propose here a small fix.

New Sample::BuildFromSequence feature in python biding

---

ChangeLog
lib/test/t_KrigingAlgorithm_funcmodel.cxx
lib/test/t_KrigingAlgorithm_std.cxx
python/test/t_KrigingAlgorithm_funcmodel.py
python/test/t_KrigingAlgorithm_std.py

New unit test: make sure the Kriging log-likelihood of a squared exponential kernel created as a StationaryFunctionalCovarianceModel is the same as that of the actual SquaredExponential kernel.
Closes #1752.

Non-regression StationaryFunctionalCovarianceModel

---

ChangeLog
lib/src/Base/Stat/AbsoluteExponential.cxx
lib/src/Base/Stat/CovarianceModel.cxx
lib/src/Base/Stat/CovarianceModelImplementation.cxx
lib/src/Base/Stat/DiracCovarianceModel.cxx
lib/src/Base/Stat/ExponentialModel.cxx
lib/src/Base/Stat/ExponentiallyDampedCosineModel.cxx
lib/src/Base/Stat/GeneralizedExponential.cxx
lib/src/Base/Stat/MaternModel.cxx
lib/src/Base/Stat/ProductCovarianceModel.cxx
lib/src/Base/Stat/SphericalModel.cxx
lib/src/Base/Stat/SquaredExponential.cxx
lib/src/Base/Stat/StationaryFunctionalCovarianceModel.cxx
lib/src/Base/Stat/TensorizedCovarianceModel.cxx
lib/src/Base/Stat/openturns/AbsoluteExponential.hxx
lib/src/Base/Stat/openturns/CovarianceModel.hxx
lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx
lib/src/Base/Stat/openturns/DiracCovarianceModel.hxx
lib/src/Base/Stat/openturns/ExponentialModel.hxx
lib/src/Base/Stat/openturns/ExponentiallyDampedCosineModel.hxx
lib/src/Base/Stat/openturns/GeneralizedExponential.hxx
lib/src/Base/Stat/openturns/MaternModel.hxx
lib/src/Base/Stat/openturns/ProductCovarianceModel.hxx
lib/src/Base/Stat/openturns/SphericalModel.hxx
lib/src/Base/Stat/openturns/SquaredExponential.hxx
lib/src/Base/Stat/openturns/StationaryFunctionalCovarianceModel.hxx
lib/src/Base/Stat/openturns/TensorizedCovarianceModel.hxx
lib/test/t_CovarianceModel_std.cxx
python/src/CovarianceModelImplementation_doc.i.in
python/test/t_CovarianceModel_std.py

Purpose is to introduce `CovarianceModelImplementation.computeAsScalar(Scalar tau)` in case input/output dimension are 1!
It will be helpful for the new `isotropic` feature!

New specific method to CovarianceModel

---

ChangeLog
python/doc/examples/data_analysis/statistical_tests/plot_kolmogorov_distribution.py
python/doc/examples/data_analysis/statistical_tests/plot_kolmogorov_statistics.py

This fixes a bug in:
openturns.github.io/openturns/master/auto_data_analysis/statistical_hypothesis_testing/plot_kolmogorov_statistics.html
The wrong figure is:
The figure is obviously wrong, because the location where the maximum distance occurs cannot be where the green line is represented. Actually, the code for the index of the observation which achieves the maximum distance is wrong, because it does not take into account for the sorted sample (the value of the statistics is correct).
A correct figure is:

Improved example for Kolmogorov statistics: take sort into account.

---

lib/src/Uncertainty/StatTests/VisualTest.cxx

It is useless to generate Point when not necessarly, especially inside
for loop/nested for loops
Performances are significantly improved. As an example, with the following test:
```
import time
ot.RandomGenerator.SetSeed(0)
copula1 = ot.FrankCopula(1.5)
copula2 = ot.GumbelCopula(4.5)
for size in [100, 200, 1000, 2000]:
sample1 = copula1.getSample(size)
sample1.setName('data 1')
sample2 = copula2.getSample(size)
sample2.setName('data 2')
tic = time.time()
kendallPlot1 = ot.VisualTest.DrawKendallPlot(sample1, copula2)
toc = time.time()
print("size=%d, dt=%1.3g"%(size,toc - tic))
```
Outputs are the following:
```
size=100, dt=0.271
size=200, dt=0.753
size=1000, dt=18.4
size=2000, dt=73.4
size=100, dt=0.00919
size=200, dt=0.0201
size=1000, dt=0.37
size=2000, dt=1.36 …
```

Improve VisualTest::DrawKendallPlot

---

ChangeLog
python/doc/examples/functional_modeling/link_to_an_external_code/plot_link_computer_code_coupling_tools.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_1D.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_advanced.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_cantilever_beam.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_cantilever_beam_hmat.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_chose_trend.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_sequential.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_simulate.py
python/doc/examples/probabilistic_modeling/stochastic_processes/plot_kronecker_covmodel.py
python/src/BootstrapExperiment_doc.i.in
python/src/CovarianceModelImplementation_doc.i.in
python/src/ExperimentImplementation_doc.i.in
python/src/Sample_doc.i.in

This PR fixes a few issues:
- The [CovarianceModel.discretize docstring](https://openturns.github.io/openturns/1.16/user_manual/_generated/openturns.CovarianceModel.html#openturns.CovarianceModel.discretize) does not mention that this method can take a `Sample` as input.
- Formatting issues in the [Link to a computer code with coupling tools](https://openturns.github.io/openturns/1.16/auto_functional_modeling/link_to_an_external_code/plot_link_computer_code_coupling_tools.html) example: together with @jschueller's PR #1766, this closes #1781. 
- More appealing thumbnail pictures for Kriging examples.
- Correct the description of the `Sample::add` method, which can admit either a `Point` or a `Sample` as argument.
- Add trajectory sampling to @sofianehaddad's [KroneckerCovarianceModel …

Small doc fixes

---

lib/test/t_LinearModelAlgorithm_std.cxx
python/test/t_LinearModelAlgorithm_std.py

Unit tests were missing. Thanks to @sofianehaddad for explaining how Cook's distance is implemented.

LinearModelResult tests

---

lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelAnalysis.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelResult.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/openturns/LinearModelResult.hxx
lib/src/Uncertainty/StatTests/LinearModelTest.cxx
python/src/LinearModelResult_doc.i.in
python/test/t_LinearModelAlgorithm_std.expout
python/test/t_LinearModelAlgorithm_std.py

Allows cases whese basis size == sample size, (not just sample size > basis size).
In that case, we throw when user asks for the noise distribution which is not defined, also for the R^2

LinearModelAlgorithm: Allow null DOF

---

python/doc/examples/calibration/bayesian_calibration/plot_rwmh_python_distribution.py

- Change the order of the beta/alpha parameters in CensoredWeibull to make it consistent with the WeibullMin parametrization (beta before alpha)
- Correct docstring inaccuracy

Corrections to the MCMC/PythonDistribution example

---

ChangeLog
lib/src/Base/Stat/CovarianceModel.cxx
lib/src/Base/Stat/CovarianceModelImplementation.cxx
lib/src/Base/Stat/openturns/CovarianceModel.hxx
lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/KrigingResult.cxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/KrigingResult.hxx
lib/test/t_CovarianceModel_std.cxx
python/src/CovarianceModelImplementation_doc.i.in
python/src/CovarianceModel_doc.i.in
python/test/t_CovarianceModel_std.py

This allows to compute the covariance interaction between X & Y samples.
or X/p where X is a `Sample`, p a `Point`
It was already implemented (but private) in `KrigingResult` for `Kriging`
variance purposes. Now we implement the method in the CovarianceModel
class as the service is mandatory for some applications such as `HSIC`
We also implement unit tests in `CovarianceModel_std` tests and made tests less time consuming for continuous integration purposes

Implement CovarianceModel::computeCrossCovariance

---

ChangeLog
TODO
lib/src/Uncertainty/StatTests/VisualTest.cxx
lib/src/Uncertainty/StatTests/openturns/VisualTest.hxx
lib/test/t_VisualTest_std.cxx
python/doc/examples/data_analysis/graphics/plot_sensitivity_par_coo_ishigami.py
python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_par_coo.py
python/doc/pyplots/VisualTest_DrawParallelCoordinates.py
python/doc/user_manual/statistics_on_sample.rst
python/src/VisualTest.i
python/src/VisualTest_doc.i.in
python/test/t_Viewer.py
python/test/t_VisualTest_std.py

CobWeb plot is for iterated function plots: https://en.wikipedia.org/wiki/Cobweb_plot
We want https://en.wikipedia.org/wiki/Parallel_coordinates
cc @adutfoy @mbaudin47

VisualTest: Rename DrawCobWeb to DrawParallelCoordinates

---

ChangeLog
python/doc/pyplots/ProductFunction.py
python/src/FunctionImplementation_doc.i.in
python/src/InterfaceObject_doc.i.in
python/src/ProductFunction_doc.i.in
python/src/SpaceFillingImplementation.i
python/src/TemperatureProfileImplementation.i
python/src/TypedInterfaceObject.i
python/test/t_CovarianceModel_std.py
python/test/t_SymbolicFunction_muparser.py
python/test/t_SymbolicFunction_std.py

An alternative version of `TypedInterfaceObject.getImplementation` is implemented as a SWIG extension of the class`TypedInterfaceObject`.
It returns a handle with type the output of the C++ command  `getImplementation()->getClassName()`.
Fixes #1931 since it lets objects obtained from the Python version of `getImplementation` access all methods of the actual implementation class.
As an example, here is a code snippet:
```python
mat = ot.MaternModel()
cov = ot.CovarianceModel(mat)
imp = cov.getImplementation()
print(type(imp))
```
With OT version 1.18, the output is
```python
<class 'openturns.statistics.CovarianceModelImplementationPointer'>
```
With this PR, it is
```python
<class 'openturns.statistics.MaternModel'>
```
As a result, the following code now works: …

Python getImplementation performs dynamic casting

---

python/doc/theory/data_analysis/metropolis_hastings.rst

Suppressed superfluous blank line and translated some mathematical notations in plain English for clarity's sake. 
This contributes to fixing issue #1935.

Fix formatting issues in metropolis_hastings.rst

---

python/src/FunctionalChaosSobolIndices_doc.i.in

This PR documents the `FunctionalChaosSobolIndices` class.
The doc of the `getSobolIndex` and `getSobolTotalIndex` methods document the optional `out_marginal` input argument:
but `getSobolGroupedIndex` and `getSobolGroupedTotalIndex` methods do not:
This PR fixes that issue.
- Adds doc of `marginalIndex` for grouped Sobol' indices. 
- Uses consistent notations across the methods.

getSobolGroupedIndex does not document the marginal index

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Uncertainty/Algorithm/Simulation/openturns/NAIS.hxx

Hello,
This PR proposes a modification of the default value for `rhoQuantile` parameter ofNAIS algorithm : from 0.7 to 0.25.
Parameter value above 0.5 is  unproper for the algorithm convergence. 
This PR does not change the test files and the examples as the default value of  `rhoQuantile` is overided in the corresponding files.
Regards,
Loïc and Mathieu

Modification of NAIS default rhoQuantile parameter

---

python/src/Function.i

Hello,
In the doc of PythonFunction, the two first parameters are indicated as "n" and "p" in the signature of the class `class PythonFunction(n, p, func=None, func_sample=None, gradient=None, hessian=None, n_cpus=None, copy=False, functionLinearity=None, variablesLinearity=None)` whereas they are specified as `inputDim` and `outputDim` in the description of parameters. This pull request proposes to make the two consistent.
https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.PythonFunction.html

Modification of parameters name of PythonFunction to be consistent with the documentation

---

lib/src/Uncertainty/Algorithm/Simulation/NAIS.cxx
lib/test/t_NAIS_std.cxx
python/test/t_NAIS_std.py

Hello,
We propose a modification of the auxiliary density in NAIS algorithm in order to use a multivariate gaussian mixture instead of a product of univariate gaussian mixture. It improves the generation of relevant samples with respect to the failure domains.
We modified two files: NAIS.cxx with the proposed enhancements and the corresponding test file.
The documentation file stays valid. 
Regards,
Mathieu & Loïc

Update NAIS algorithm

---

ChangeLog
python/doc/_templates/Copula.rst_t
python/doc/_templates/CovarianceModel.rst_t
python/doc/_templates/Distribution.rst_t
python/doc/_templates/DistributionFactory.rst_t
python/doc/_templates/DistributionHighDimension.rst_t
python/doc/_templates/FilteringWindow.rst_t
python/doc/_templates/LowDiscrepancySequence.rst_t
python/doc/_templates/ODESolver.rst_t
python/doc/_templates/OrthogonalUniVariateFunctionFamily.rst_t
python/doc/_templates/Process.rst_t
python/doc/_templates/Solver.rst_t
python/doc/_templates/SpectralModel.rst_t
python/doc/_templates/StratifiedExperiment.rst_t
python/doc/_templates/class.rst_t
python/doc/_templates/classWithPlot.rst_t
python/doc/_templates/function.rst_t
python/doc/_templates/functionWithPlot.rst_t
python/doc/conf.py.in

Following the discussion at yesterday's meeting, I have implemented @mdelozzo's suggestion of adding minigalleries of exampls in API doc pages.
It seems to me there is no need to exclude often used classes like Point and Sample, because the minigallery is at the end of the page and thus unobstrusive. The minigallery is however mentioned in the table of contents at the top right-hand corner, so it can be quickly accessed if needed.
As an example, here is the top of the KrigingAlgorithm page:
And here the bottom of the KrigingAlgorithm page:
Closes #2115

Automatic example galleries in API pages

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Uncertainty/Bayesian/Gibbs.cxx
lib/src/Uncertainty/Bayesian/openturns/Gibbs.hxx
lib/src/Uncertainty/Bayesian/openturns/OTBayesian.hxx
lib/test/t_Gibbs_regression.cxx
python/src/Gibbs_doc.i.in
python/test/t_Gibbs_std.py

Fixes a bug that could cause an error in the detection of samplers which do not need to recompute the log-posterior density in the case where the overall dimension differs from the number of samplers.
Add the option to randomly pick the next MetropolisHastings block to sample from instead of using the specified order. This variant is actually the original Gibbs algorithm.

Gibbs-related stuff

---

ChangeLog
lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation/BoxCoxFactory.cxx

As `GLM(BasisCollection)` is already deprecated, we do the same here for `BoxCoxFactory::build(...,BasisCollection)`.
`BoxCoxFactory::build(...Basis)` was relying on the previous method thus we reimplement this method to not rely anymore on the deprecated method and to avoid useless `deprecate warning msg`

Deprecate BoxCoxFactory::build(..., BasisCollection)

---

lib/src/Uncertainty/Algorithm/Classification/MixtureClassifier.cxx
lib/src/Uncertainty/Distribution/KernelMixture.cxx
lib/src/Uncertainty/Distribution/Mixture.cxx
lib/src/Uncertainty/Distribution/ParametrizedDistribution.cxx
lib/src/Uncertainty/Distribution/RandomMixture.cxx
lib/src/Uncertainty/Distribution/TruncatedDistribution.cxx
lib/src/Uncertainty/Distribution/openturns/ParametrizedDistribution.hxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
lib/src/Uncertainty/Model/openturns/DistributionImplementation.hxx
lib/test/t_CumulativeDistributionNetwork_std.expout
python/src/DistributionImplementation.i

This is an attempt to solve the issues described in detail [here](https://github.com/openturns/openturns/issues/2157). The main points are:
* A modification of Mixture, which does not use anymore the weight of the individual atoms
* A reorganization of the different computeProbability() algorithms to avoid the cost of creating intervals for 1D distributions

Improve distributions

---

lib/src/Base/Func/SpecFunc/SpecFunc.cxx
lib/src/Base/Func/SpecFunc/openturns/SpecFunc.hxx
lib/src/Uncertainty/Algorithm/Analytical/SystemFORM.cxx
lib/src/Uncertainty/Model/DistributionImplementation.cxx
python/doc/user_manual/functions.rst
python/src/SpecFunc_doc.i.in
python/test/t_SpecFunc_std.py

This method allows to compute the sum of a sequence of floats with an extended precision, using either MPFR or Kahan's method.

Added SpecFunc::AccurateSum

---

lib/src/Base/Func/LARS.cxx
python/test/t_FieldFunctionalChaosSobolIndices_std.py
python/test/t_FieldToPointFunctionalChaosAlgorithm_std.py
python/test/t_LeastSquaresMethod_std.expout

The constant function, which has the index 0 in any orthogonal basis by convention, must be accepted first in the sequential exploration otherwise the correlation computation through a matrix/vector product is wrong. One easy way to enforce this is to deactivate the selection step based on correlation at the first iteration.
This fix is quite urgent as CERFACS partners are blocked by the bug...

Fixed LARS

---

lib/src/Uncertainty/Distribution/KernelSmoothing.cxx
lib/test/t_KernelSmoothing_std.cxx
lib/test/t_KernelSmoothing_std.expout
python/test/t_KernelSmoothing_std.expout
python/test/t_KernelSmoothing_std.py

When the bounding option is activated and the bound is given, the algorithhm may consider that the sample has constant values due to a wrong initialization of variables.

Fixed KernelSmoothing

---

ChangeLog
lib/src/Base/Func/BoxCoxEvaluation.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelAlgorithm.cxx
lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation/BoxCoxFactory.cxx
lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation/openturns/BoxCoxFactory.hxx
lib/test/CMakeLists.txt
lib/test/t_BoxCoxFactory_lm.cxx
python/doc/pyplots/BoxCoxFactory.py
python/doc/theory/probabilistic_modeling/boxcox_transformation.rst
python/src/BoxCoxFactory.i
python/src/BoxCoxFactory_doc.i.in
python/test/CMakeLists.txt
python/test/t_BoxCoxFactory_glm.py
python/test/t_BoxCoxFactory_lm.py
python/test/t_BoxCoxFactory_std.py

This PR allows to apply BoxCoxFactory with LinearModel
Before this PR, it was possible to do it using the GLM case + DiracCovarianceModel
Now  we implement this well known usage using directly DesignProxy/LeastSquaresMethod classes instead of LinearModelAlgorithm in order to have only one factorization and solve linear systems for each new lambda value. 
It allows having an efficient algorithm

BoxCox & LinearModel

---

ChangeLog
lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Type/MatrixImplementation.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorConditionalSensitivity.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorGlobalSensitivity.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorImplementation.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorTargetSensitivity.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICStat.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICStatImplementation.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICUStat.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/HSICVStat.cxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorConditionalSensitivity.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorGlobalSensitivity.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorImplementation.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICEstimatorTargetSensitivity.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICStat.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICStatImplementation.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICUStat.hxx
lib/src/Uncertainty/Algorithm/Sensitivity/openturns/HSICVStat.hxx
lib/test/t_HSICEstimatorTargetSensitivity_std.cxx
lib/test/t_HSICStat_std.cxx
python/src/HSICStatImplementation_doc.i.in
python/test/t_HSICEstimatorConditionalSensitivity_std.py
python/test/t_HSICEstimatorGlobalSensitivity_std.py
python/test/t_HSICEstimatorTargetSensitivity_std.py
python/test/t_HSICStat_std.py

The aim of this PR is to speed up drastically `HSIC` implementations. It relies on the work started by @JPelamatti and @regislebrun (see for example  #2053 and 
many axes were considered to boost the performances : 
- Factorization of covariance matrices computations : many often we need to compute these matrices once! 
- Parallelization of `PValues` evaluation (permutation) using TBB
- Boosting low level methods (`computeSumElements`)
- Rewriting `HSICVStat` :  don't use an inline product matrix (with 6 matrices) to get the trace but perform manually the computation of the trace!
With these changes, we can now perform easily a `getPValuesPermutation` in a reasonable CPU time.
For example, considering the following use-case (wing_weight) :
```python
from …
```

Boost performances in HSIC

---

lib/src/Base/Common/ResourceMap.cxx
lib/src/Uncertainty/Algorithm/Simulation/NAIS.cxx
lib/src/Uncertainty/Algorithm/Simulation/openturns/NAIS.hxx
lib/test/t_NAIS_std.cxx
python/doc/examples/reliability_sensitivity/reliability/plot_nais.py
python/src/NAIS_doc.i.in
python/test/t_NAIS_std.py

Hello,
In the PR #2272 about Importance Sampling by Cross Entropy, it was agreed that the name of the attribute "rhoQuantile" is not meaningful for the user. So, it has been changed by "quantileLevel".
This PR proposes to propagate this change to the NAIS algorithm, as NAIS and Cross Entropy Importance Sampling have similar API.
Furthermore, the sphinx gallery thumbnail picture of the NAIS example has been changed to set a graph that is more representative of the algorithm behavior.

Modification of NAIS API

---

ChangeLog
lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Stat/DiracCovarianceModel.cxx

Now the sample given to the discretize() and discretizeAndFactorize() methods is checked against repeated points. This behavior is controlled by the "DiracCovarianceModel-CheckUnique" boolean entry.
With this PR, the script given in #2296 produces:
```
[ v0 ]
0 : [ 1  ]
1 : [ 2  ]
2 : [ 3  ]
3 : [ 1  ]
4 : [ 1  ]
5 : [ 3  ]
6 : [ 3  ]
7 : [ 3  ]
8 : [ 1  ]
9 : [ 1  ]
0.0
1.0
10x10
[[ 1 0 0 1 1 0 0 0 1 1 ]
[ 0 1 0 0 0 0 0 0 0 0 ]
[ 0 0 1 0 0 1 1 1 0 0 ]
[ 1 0 0 1 1 0 0 0 1 1 ]
[ 1 0 0 1 1 0 0 0 1 1 ]
[ 0 0 1 0 0 1 1 1 0 0 ]
[ 0 0 1 0 0 1 1 1 0 0 ]
[ 0 0 1 0 0 1 1 1 0 0 ]
[ 1 0 0 1 1 0 0 0 1 1 ]
[ 1 0 0 1 1 0 0 0 1 1 ]]
```
as expected.
The impact on the performance is not large as soon as the sample size is of order 500:
```
dimIn = 5
dimOut = 4 …
```

Fixed DiracCovarianceModel

---

python/doc/examples/data_analysis/distribution_fitting/plot_smoothing_mixture.py
python/doc/examples/meta_modeling/fields_metamodels/plot_fieldfunction_metamodel.py
python/doc/examples/meta_modeling/general_purpose_metamodels/plot_create_linear_least_squares_model.py
python/doc/examples/meta_modeling/general_purpose_metamodels/plot_taylor_approximation.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_enumeratefunction.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_exploitation.py
python/doc/theory/data_analysis/bic.rst
python/doc/theory/probabilistic_modeling/process_definitions.rst
python/doc/theory/probabilistic_modeling/random_mixture.rst
python/doc/usecases/use_case_viscous_fall.rst
python/src/AdaptiveStieltjesAlgorithm_doc.i.in
python/src/DistFunc_doc.i.in
python/src/EnumerateFunctionImplementation_doc.i.in
python/src/FejerAlgorithm_doc.i.in
python/src/FunctionImplementation_doc.i.in
python/src/GaussianLinearCalibration_doc.i.in
python/src/GaussianNonLinearCalibration_doc.i.in
python/src/SymbolicFunction_doc.i.in

This PR fixes several bugs.
- The BIC help page has issues: #2199 
- Improved KS example #2138 
- Fixed correlation function #2104 
- Fixed linear least squares model as a part of #1935
- Improved example of Taylor expansion as a part of #1935
- Fixed SymbolicFunction draw method doc as a part of #1935
- Fixed the AdaptiveStieljesAlgorithm doc as a part of #1935
- Fixed the viscous free fall example, as a part of #1935
- Fixed the "Random Mixture: affine combination of independent univariate distributions" as a part of #1935
- Fixed the Fejer help page as a part of #1935
- Improved "Metamodel of a field function" as a part of #1935

Improve doc

---

lib/src/Uncertainty/Algorithm/Simulation/CrossEntropyImportanceSampling.cxx
lib/src/Uncertainty/Algorithm/Simulation/PhysicalSpaceCrossEntropyImportanceSampling.cxx
lib/src/Uncertainty/Algorithm/Simulation/StandardSpaceCrossEntropyImportanceSampling.cxx
lib/src/Uncertainty/Algorithm/Simulation/openturns/CrossEntropyImportanceSampling.hxx
lib/src/Uncertainty/Algorithm/Simulation/openturns/PhysicalSpaceCrossEntropyImportanceSampling.hxx
lib/src/Uncertainty/Algorithm/Simulation/openturns/StandardSpaceCrossEntropyImportanceSampling.hxx

As discussed in the previous meeting, after a run, current versions of Cross Entropy algorithms (StandardSpace and PhysicalSpace) keep in memory the auxiliary density as default auxiliary distribution. This may have impact in case of multiple runs. Furthermore, this behavior is not the same as Subset Sampling. 
This PR proposes to automatically reset the auxiliary distribution with default values in case of multiple runs of StandardSpaceCrossEntropyImportanceSampling and PhysicalSpaceCrossEntropyImportanceSampling. 
To do so, a new method  `resetAuxiliaryDistribution` has been created in order to reinitialize the auxiliary distribution to the default one in case of multiple runs of Importance Sampling.

Reset auxiliary distribution of Cross Entropy Importance Sampling before use

---

ChangeLog
lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation/BoxCoxFactory.cxx
lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation/openturns/BoxCoxFactory.hxx
lib/test/t_BoxCoxFactory_glm.cxx
lib/test/t_BoxCoxFactory_lm.cxx
lib/test/t_BoxCoxFactory_std.cxx
python/doc/pyplots/BoxCoxFactory.py
python/src/BoxCoxFactory_doc.i.in
python/test/t_BoxCoxFactory_glm.py
python/test/t_BoxCoxFactory_lm.py
python/test/t_BoxCoxFactory_std.py

Since https://github.com/openturns/openturns/pull/2244 it seems BoxCoxFactory::build(Sample, Point) does not return a Graph anymore
This is because SWIG does not know which variant to call, with or without graph return argument.
To disambiguate the API, I propose to introduce new signatures depending on the result type:
```
BoxCoxTransform build(const Field & timeSeries) const;
BoxCoxTransform build(const Field & timeSeries,
const Point & shift) const;
BoxCoxTransform buildWithGraph(const Field & timeSeries,
const Point & shift,
Graph & graph) const;
BoxCoxTransform build(const Sample & sample) const;
BoxCoxTransform build(const Sample & sample,
const Point & shift) const;
BoxCoxTransform buildWithGraph(const Sample & sample,
const Point & shift,
Graph & graph) const;
/** Build the …
```

BoxCoxFactory: Split build method

---

python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_beam_arbitrary_trend.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_beam_trend.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_chose_trend.py
python/doc/math_notations.sty
python/src/EnumerateFunctionImplementation_doc.i.in
python/src/SmolyakExperiment_doc.i.in
python/src/TensorProductExperiment_doc.i.in

This PR improves several examples.
- The [plot-kriging-chose-trend-py](http://openturns.github.io/openturns/master/auto_meta_modeling/kriging_metamodel/plot_kriging_chose_trend.html#sphx-glr-auto-meta-modeling-kriging-metamodel-plot-kriging-chose-trend-py) has issues :
- The [EnumerateFunction](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.EnumerateFunction.html#openturns.EnumerateFunction) is unclear.
- The `vect` macro is not always used.

Improve examples

---

python/doc/bibliography.rst
python/doc/theory/data_analysis/kernel_smoothing.rst
python/src/HistogramFactory_doc.i.in
python/src/KernelSmoothing_doc.i.in

This PR improves the kernel smoothing API and theory help pages.
This fixes #1979.
This PR improves two help pages:
- [KernelSmoothing](https://output.circle-artifacts.com/output/job/57a3c07f-4da4-43e8-a41c-a8ca276c48ef/artifacts/0/html/user_manual/_generated/openturns.KernelSmoothing.html#openturns.KernelSmoothing) API help page
- [kernel_smoothing](https://output.circle-artifacts.com/output/job/57a3c07f-4da4-43e8-a41c-a8ca276c48ef/artifacts/0/html/theory/data_analysis/kernel_smoothing.html) theory help page.
To do this, I had access to slides generously given by @adutfoy : thank you for this!
The theory help page had many bugs that are now fixed.
The Silverman rule of KDE does not make use of the estimated standard deviation. It uses the exact standard deviation. Then several rules can …

KernelSmoothing: Fix doc.

---

ChangeLog
lib/src/Base/Algo/ApproximationAlgorithmImplementation.cxx
lib/src/Base/Algo/LeastSquaresMetaModelSelection.cxx
lib/src/Base/Algo/PenalizedLeastSquaresAlgorithm.cxx
lib/src/Base/Algo/openturns/ApproximationAlgorithmImplementation.hxx
lib/src/Base/Algo/openturns/LeastSquaresMetaModelSelection.hxx
lib/src/Base/Algo/openturns/PenalizedLeastSquaresAlgorithm.hxx
lib/src/Base/Func/BasisSequenceFactoryImplementation.cxx
lib/src/Base/Func/LARS.cxx
lib/src/Base/Func/openturns/BasisSequenceFactoryImplementation.hxx
lib/src/Base/Func/openturns/LARS.hxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosResult.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/IntegrationStrategy.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/LeastSquaresStrategy.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/ProjectionStrategyImplementation.cxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/openturns/FunctionalChaosResult.hxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/openturns/IntegrationStrategy.hxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/openturns/LeastSquaresStrategy.hxx
lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/openturns/ProjectionStrategyImplementation.hxx
python/doc/pyplots/LARS.py
python/doc/user_manual/response_surface/functional_chaos_expansion.rst
python/src/ApproximationAlgorithmImplementation.i
python/src/BasisSequenceFactoryImplementation.i
python/src/FunctionalChaosResult_doc.i.in
python/src/ProjectionStrategyImplementation.i
python/test/t_FunctionalChaos_mixed.py

Adds new methods to retrieve selection history from a FCE result
```
result = algo.getResult()
print(result.getIndicesHistory())
print(result.getCoefficientsHistory())
graph = result.drawSelectionHistory()
```
notes:
- sofiane script does not account that LARS eventually works in a local selection of the basis
- might want to add Q2 history too
- only returns the last selection history & marginal
see also:
https://gist.github.com/sofianehaddad/0011686ed5eb917f1201383ee5069cbf
https://gist.github.com/sofianehaddad/a6f94bf992f8bde3810f9013bb1f3665

Chaos selection history

---

lib/etc/openturns.conf.in
lib/src/Base/Algo/EnclosingSimplexAlgorithm.cxx
lib/src/Base/Algo/EnclosingSimplexAlgorithmImplementation.cxx
lib/src/Base/Algo/openturns/EnclosingSimplexAlgorithm.hxx
lib/src/Base/Algo/openturns/EnclosingSimplexAlgorithmImplementation.hxx
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Geom/LevelSetMesher.cxx
lib/src/Uncertainty/Distribution/UniformOverMesh.cxx
lib/src/Uncertainty/Process/SpectralGaussianProcess.cxx
lib/src/Uncertainty/Process/openturns/SpectralGaussianProcess.hxx
python/src/EnclosingSimplexAlgorithmImplementation_doc.i.in
python/src/EnclosingSimplexAlgorithm_doc.i.in

This PR proposes the following fixes/improvements:
* SpectralNormalProcess sampling is now almost twice faster
* ~~XMLH5StorageManager can now deal with very large datasets~~
* MeshDomain and EnclosingSimplexAlgorithm now have a user-tunable tolerance for the inclusion test.
* UniformOverMesh was generating samples without description, fixed now.
* ~~VisualTest::DrawParallelCoordinates was using ranks instead of the actual values to select highlighted paths, leading to spurious selection due to roundoff~~
The third point is of uttermost importance, as the sampling of the boundary of a given mesh produces points which are mostly rejected when tested against the interior of the mesh.

Various improvements

---

python/doc/usecases/use_case_fireSatellite.rst
python/src/usecases/fireSatellite_function.py

Hello,
Closes  #2527
This PR proposed a modification of the probability distribution of input parameters of the firesatellite use case, to avoid non realistic samples (negative for positive quantities). 
Truncated  Normal distribution is used instead of Normal distribution.

Modification of input distribution for firesatellite use case

---

lib/src/Base/Stat/CovarianceModel.cxx
lib/src/Base/Stat/CovarianceModelImplementation.cxx
lib/src/Base/Stat/DiracCovarianceModel.cxx
lib/src/Base/Stat/FractionalBrownianMotionModel.cxx
lib/src/Base/Stat/IsotropicCovarianceModel.cxx
lib/src/Base/Stat/KroneckerCovarianceModel.cxx
lib/src/Base/Stat/LatentVariableModel.cxx
lib/src/Base/Stat/ProductCovarianceModel.cxx
lib/src/Base/Stat/StationaryFunctionalCovarianceModel.cxx
lib/src/Base/Stat/TensorizedCovarianceModel.cxx
lib/src/Base/Stat/openturns/CovarianceModel.hxx
lib/src/Base/Stat/openturns/CovarianceModelImplementation.hxx
lib/src/Base/Stat/openturns/KroneckerCovarianceModel.hxx
lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx
lib/test/t_CovarianceModel_std.cxx
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_advanced.py
python/src/CovarianceModelImplementation_doc.i.in
python/src/CovarianceModel_doc.i.in
python/src/StationaryFunctionalCovarianceModel_doc.i.in
python/test/t_CovarianceModel_std.py
python/test/t_ExponentialModel_std.expout
python/test/t_ProductCovarianceModel_std.expout
python/test/t_ProductCovarianceModel_std.py
python/test/t_StationaryFunctionalCovarianceModel_std.py

This PR adds the `nuggetFactor` to the list of parameters of a `CovarianceModel` so it can be optimized by `GeneralLinearModelAlgorithm`.
It changes the parameter order (size in parentheses) from:
1. scale (inputDimension usually)
2. amplitude (outputDimension)
3. output correlation (outputDimension * (outputDimension-1) / 2)
4. extra parameters (?)
to:
1. scale (inputDimension usually)
2. **nuggetFactor** (1)
3. amplitude (outputDimension)
4. output correlation (outputDimension * (outputDimension-1) / 2)
5. extra parameters (?)
Furthermore, in `GeneralLinearModelAlgorithm`, the default optimization lower bound for the `nuggetFactor` is set to `0.0`. It has the same upper bound as the other parameters (`1e2`).
EDIT: in addition, this PR implements new methods to make activation and …

CovarianceModel: Add nuggetFactor to optimizable parameters

---

python/doc/examples/calibration/bayesian_calibration/plot_bayesian_calibration.py
python/doc/examples/data_analysis/manage_data_and_samples/plot_quick_start_point_and_sample.py
python/doc/examples/functional_modeling/vectorial_functions/plot_parametric_function.py
python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_hyperparameters_optimization.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_build_distribution.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_ishigami_grouped_indices.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_database.py
python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_functional_chaos_sensitivity.py
python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_ancova.py
python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_wingweight.py
python/src/KrigingAlgorithm_doc.i.in
python/src/OptimizationAlgorithmImplementation_doc.i.in
python/src/OrthogonalFunctionFactory_doc.i.in
python/src/OrthogonalProductPolynomialFactory_doc.i.in
python/src/ParametricFunction_doc.i.in

This PR fixes two bugs:
- the first kriging example mentioned by @mdelozzo in #2364
- the bugs mentioned in the API doc of  `KrigingAlgorithm` by @mdelozzo in #2361 
- the bugs mentioned on `Sample` example in #2359
This PR also fixes other doc bugs.
- This PR also fixes bugs in the Bayesian calibration doc:
- This PR provides more detailed explanations on the `ParametricFunction` class.
- It provides an improved example to set a column or a row of a `Sample`.
- It removes unnecessary casts (i.e. class conversions) in some examples.
To do this, I used `docfast.py` with the following parameters:
```bash
$ git add . && cd build && make -j8 && make install && cd .. && python3 utils/docfast.py build-sphinxonly response_surface.rst kriging.rst KrigingAlgorithm.rst …
```

Fixes doc issues

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Func/LinearEvaluation.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelAlgorithm.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelAnalysis.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/LinearModelResult.cxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/openturns/LinearModelAnalysis.hxx
lib/src/Uncertainty/Algorithm/MetaModel/LinearModel/openturns/LinearModelResult.hxx
lib/test/t_LinearModelAlgorithm_std.cxx
lib/test/t_LinearModelAlgorithm_std.expout
python/doc/bibliography.rst
python/doc/examples/meta_modeling/general_purpose_metamodels/plot_distribution_linear_regression.py
python/doc/examples/meta_modeling/general_purpose_metamodels/plot_linear_model.py
python/doc/theory/data_analysis/data_analysis.rst
python/doc/theory/data_analysis/linear_regression.rst
python/doc/theory/data_analysis/regression_analysis.rst
python/doc/theory/meta_modeling/meta_modeling.rst
python/doc/theory/meta_modeling/polynomial_least_squares.rst
python/src/FunctionalChaosAlgorithm_doc.i.in
python/src/FunctionalChaosResult_doc.i.in
python/src/LinearFunction_doc.i.in
python/src/LinearModelAnalysis.i
python/src/LinearModelAnalysis_doc.i.in
python/src/LinearModelResult_doc.i.in
python/test/t_LinearModelAlgorithm_std.expout
python/test/t_LinearModelAlgorithm_std.py

The goal of this PR is to improve the features and documentation of the linear model.
PS
The PR contains the sub-part of #2373 which does not have any link to the `FunctionalChaosAlgorithm`.
- `LinearModelAnalysis`:
- Creates a new `LinearModelAnalysis::getResidualsStandardError()` method.
- New HTML Python pretty-print.
- `LinearModelResult`
- Creates new `LinearModelResult.getDesign()` and `LinearModelResult.getSigma2()` methods. These are attributes of the class which had no corresponding `get` methods.
- Creates a new `LinearModelResult::__repr_markdown__()` method.
- A new example of a `PythonRandomVector` is created: `plot_distribution_linear_regression.py`. It plots the distribution of the estimators of the variance and standard deviation of linear regression. This example uses the …

Improve linear model

---

python/doc/bibliography.rst
python/doc/examples/numerical_methods/general_methods/plot_pce_design.py
python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_sobol.py
python/doc/math_notations.sty
python/src/FunctionImplementation_doc.i.in
python/src/FunctionalChaosRandomVector_doc.i.in
python/src/ImportanceSamplingExperiment_doc.i.in
python/src/LHSExperiment_doc.i.in
python/src/MonteCarloExperiment_doc.i.in
python/src/PostAnalyticalImportanceSampling_doc.i.in
python/src/WeightedExperimentImplementation_doc.i.in

This PR improves some help pages.
I introduced a set of macro in `math_notations.sty` to solve #2366. The goal is to consistently use them across the help pages. This is because I notice that the `FunctionalChaosResult` and `FunctionalChaosAlgorithm` help pages do not use the same notations consistently. Indeed, we should use consistent notations not only within a single page, but also across pages on the same topic. Moreover, because some help pages are inherited from mother classes, several help pages must be updated accordingly. For example, `FunctionalChaosResult` inherits from `MetaModelResult`. Hence, both pages must be updated accordingly. Otherwise, the sample size, for example, is denoted $n$ in some pages, but $N$ in the inherited page. The only way to consistently use the same …

Improve doc of polynomial chaos expansion

---

python/src/AdaptiveStrategyImplementation_doc.i.in
python/src/CleaningStrategy_doc.i.in
python/src/FixedStrategy_doc.i.in
python/src/IntegrationStrategy_doc.i.in
python/src/LeastSquaresMetaModelSelection_doc.i.in
python/src/LinearModelAlgorithm_doc.i.in
python/src/PenalizedLeastSquaresAlgorithmFactory_doc.i.in
python/src/PenalizedLeastSquaresAlgorithm_doc.i.in

The goal of this PR is to create API help sections of existing methods.
- CleaningStrategy::updateBasis (see [here](http://openturns.github.io/openturns/master/user_manual/response_surface/_generated/openturns.CleaningStrategy.html) for the current version)
- CleaningStrategy::setVerbose
- FixedStrategy::updateBasis (see [here](http://openturns.github.io/openturns/master/user_manual/response_surface/_generated/openturns.FixedStrategy.html) for the current version)
- LeastSquaresMetaModelSelection::getBasisSequenceFactory (see [here](http://openturns.github.io/openturns/master/user_manual/response_surface/_generated/openturns.LeastSquaresMetaModelSelection.html) for the current version)
- LeastSquaresMetaModelSelection::setBasisSequenceFactory
- …

Add API help sections of existing methods

---

lib/include/openturns/GSobolUseCase.hxx
lib/include/openturns/IshigamiUseCase.hxx
lib/test/t_FunctionalChaosSobolIndices_ishigami.cxx
lib/test/t_FunctionalChaos_gsobol.cxx
lib/test/t_FunctionalChaos_ishigami.cxx
lib/test/t_FunctionalChaos_ishigami_database.cxx
lib/test/t_FunctionalChaos_ishigami_database.expout
lib/test/t_FunctionalChaos_ishigami_sparse.cxx

This PR creates two C++ use cases for unit tests: Ishigami and GSobol. The goal is to factor these two use cases which implementation is spread across several C++ unit tests.
The new `IshigamiUseCase` unit test class is created in OTtestcode.hxx. We can use this class to get the model, the input distribution and the Sobol' indices.
```cpp
IshigamiUseCase ishigami;
Function model(ishigami.getModel());
JointDistribution distribution(ishigami.getInputDistribution());
Scalar mean = ishigami.getMean();
Scalar variance = ishigami.getVariance();
Scalar S1 = ishigami.getFirstOrderSobolIndices();
Scalar S12 = ishigami.getFirstOrderInteractionSobolIndex({0, 1});
```
The new `GSobolUseCase` provides similar features.
```cpp
GSobolUseCase gsobol(dimension, a);
Function model(gsobol.getModel()); …
```

Create two C++ use cases for unit tests: Ishigami and GSobol

---

lib/src/Base/Type/MatrixImplementation.cxx
lib/src/Base/Type/SquareMatrix.cxx
lib/src/Base/Type/SymmetricMatrix.cxx
lib/src/Base/Type/openturns/MatrixImplementation.hxx
lib/src/Base/Type/openturns/SquareMatrix.hxx
lib/src/Base/Type/openturns/SymmetricMatrix.hxx
lib/test/t_SquareMatrix_std.cxx
lib/test/t_SymmetricMatrix_std.cxx
python/src/Matrix_doc.i.in
python/src/SquareMatrix_doc.i.in
python/src/SymmetricMatrix_doc.i.in
python/test/t_SquareMatrix_std.py
python/test/t_SymmetricMatrix_std.py

- The new `SquareMatrix.inverse()` and `SymmetricMatrix.inverse()` methods are created.
Example:
```python
sqMatrix = ot.SquareMatrix([[1.0, 2.0, 3.0], [3.0, 2.0, 1.0], [2.0, 1.0, 3.0]])
sqInverse = sqMatrix.inverse()
```
This is a part of PR #2330.

New inversion methods for a Matrix

---

lib/src/Base/Stat/IsotropicCovarianceModel.cxx
lib/test/t_KrigingAlgorithm_isotropic_std.cxx
python/test/t_KrigingAlgorithm_isotropic_std.py

Everything is in the title. It was previously possible to construct an IsotropicCovarianceModel with null input dimension, which makes no sense.

IsotropicCovarianceModel throw if inputDimension=0

---

python/src/Contour_doc.i.in
utils/docfast.py

- [Link Contour doc to corresponding matplotlib page](https://github.com/openturns/openturns/commit/5920d5484db798ac33a8844ccf1d44dd963752d9) to document vmin and vmax. Closes #2669 
- [Update docfast requirements](https://github.com/openturns/openturns/commit/07e57effbc52b7224c2414c53f23b7e8d1dd89d7)

Improve Contour vmin and vmax doc

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Uncertainty/Distribution/KernelSmoothing.cxx
lib/src/Uncertainty/Distribution/openturns/KernelSmoothing.hxx
python/doc/bibliography.rst
python/doc/examples/data_analysis/distribution_fitting/plot_estimate_non_parametric_distribution.py
python/doc/theory/data_analysis/data_analysis.rst
python/doc/theory/data_analysis/kernel_smoothing.rst
python/src/KernelSmoothing_doc.i.in
python/test/t_KernelSmoothing_std.py

Improved KernelSmoothing
Now, a log transformation can be applied to ease the reconstruction of skewed distributions.
This new capability has been thoroughly documented thanks to @adutfoy

Improve kernel smoothing

---

lib/src/Uncertainty/Bayesian/RandomWalkMetropolisHastings.cxx

This reverts commit 52c9554eb6d7c8b7911b51ff32e6f6fc352907df. This check was not included by design in the MCMC overhaul because it creates problems in higher dimensions
and fails to actually block senseless proposal distributions.

Revert "RWMH: Check proposal contains zero with enough margin"

---

lib/src/Uncertainty/StatTests/VisualTest.cxx
lib/src/Uncertainty/StatTests/openturns/VisualTest.hxx
python/doc/examples/data_analysis/graphics/plot_visualize_input_output_sample.py
python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_ishigami.py
python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_sobol.py
python/doc/pyplots/DrawPairsXY.py
python/doc/user_manual/statistics_on_sample.rst
python/src/VisualTest_doc.i.in

This PR closes #1749 
It is proposed a new usage of DrawPairs that depends on two samples `inputSample` and `outputSample`
This method draw pairs between the marginal samples of the two given sample. It could be useful to analyze the relationships between inputs and outputs of a code. 
An example of application is provided.

Draw pairs between two samples

---

python/doc/bibliography.rst
python/doc/examples/numerical_methods/optimization/plot_ego.py

This PR closes #1302.
The EGO example has been modified to enhance convergence of the algorithm without increasing the number of iteration. To do so, the kernel has been changed to Matern which is mored adapted than SquareExponential in order to deal with Ackley function.

modification of kernel to speed up EGO example and converge

---

lib/src/Uncertainty/Distribution/JointByConditioningDistribution.cxx
lib/src/Uncertainty/Distribution/openturns/JointByConditioningDistribution.hxx
python/test/t_JointByConditioningDistribution_std.expout
python/test/t_JointByConditioningDistribution_std.py

Now, the compute[Sequential]Conditional[PDF|CDF[Quantile] methods have a dedicated implementation, resulting into a huge performance boost.
The main goal is to allow the use of JointByConditioningDistribution in FORM/SORM algorithms.

Improved JointByConditioningDistribution

---

python/doc/bibliography.rst
python/doc/examples/calibration/least_squares_and_gaussian_calibration/plot_calibration_chaboche.py
python/doc/examples/data_analysis/distribution_fitting/plot_model_singular_multivariate_distribution.py
python/src/BernsteinCopulaFactory_doc.i.in
python/src/EmpiricalBernsteinCopula_doc.i.in
python/src/InverseChiSquare_doc.i.in
python/src/KernelMixture_doc.i.in

I modified the doc of the : 
1. EmpiricalBernsteinCopula: I gave the expression of the empirical Bernstein copula  as a Mixture of multivariate beta distributions. I precised that it is not always a copula (it is a copula only if the bin number divides the sample size). I detailed the argument isRankSample.
2. BernsteinCopulaFactory: I improved the doc to explain all the arguments. As it is implemented, it is always produce a copula.
3. I improved the example 'Model a singular multivariate distribution' in order to better explain the use of the EmpiricalBernsteinCopula.
4. I added the reference to the reference paper of Segers on the empirical Bernstein copula.
5. I fixed two typos in the InverseChiSquare and KernelMixture documentations.

Doc of the EmpiricalBernsteinCopula and the BernsteinCopulaFactory

---

lib/etc/openturns.conf.in
lib/src/Base/Common/ResourceMap.cxx
lib/src/Base/Func/PiecewiseHermiteEvaluation.cxx
lib/src/Base/Func/PiecewiseLinearEvaluation.cxx
lib/src/Base/Func/openturns/PiecewiseHermiteEvaluation.hxx
lib/src/Base/Func/openturns/PiecewiseLinearEvaluation.hxx
python/src/PiecewiseHermiteEvaluation_doc.i.in
python/src/PiecewiseLinearEvaluation_doc.i.in
python/test/t_PiecewiseHermiteEvaluation_std.py
python/test/t_PiecewiseLinearEvaluation_std.py

This PR closes #2856 
A boolean has been added to enable (or not) the extrapolation of PieceWiseEvaluation algorithms. If this boolean is set to False, a documented error is retrieved.

Fix extrapolation of PieceWise Hermite and Linear Evaluation

---

python/doc/examples/reliability_sensitivity/reliability/plot_estimate_probability_randomized_qmc.py

Hi,
This PR proposes a slight change of the [Use a randomized QMC algorithm](https://openturns.github.io/openturns/latest/auto_reliability_sensitivity/reliability/plot_estimate_probability_randomized_qmc.html?highlight=qmc) example.
Indeed, the current example describes the use of QMC for reliability on the cantilever beam example. However, since the target probability of this reliability example is very low (around 1e-7), the algorithm fails  with the considered simulation budget and retrieves 0.
In this PR, the test case is switched to the simple beam example with a target probability of  around 0.03. With this test case, the QMC reliability method succeeds to estimate the failure probability with a reasonable budget.

Change of QMC reliability example
